### ISSUE TITLE
system.c: integer and string overflow

### ISSUE THREAD

**Issue by mca0001** [net-snmp/net-snmp#1]
net-snmp-5.7.3/snmplib/system.c: long get_uptime(void)
....
  long uptim = 0, a, b;
  uptim = a * 100 + b;  **<<< possible integer overflow**
....
    struct timeval  now;
    long   boottime_csecs, nowtime_csecs;
....
  nowtime_csecs = (now.tv_sec * 100) + (now.tv_usec / 10000); **<<< possible integer overflow**

net-snmp-5.7.3/snmplib/system.c: int mkdirhier(const char *pathname, mode_t mode, int skiplast)
....
  strcat(buf, entry);  **<<< possible string overflow**
....
  strcat(buf, entry);  **<<< possible string overflow**

**Comment by bvanassche** [comment]
Please report Net-SNMP bugs on https://sourceforge.net/p/net-snmp/bugs/
