### ISSUE TITLE
snmpd.conf proc with name containing spaces ignores values for Max and Min

### ISSUE THREAD

**Issue by michelhandleitnl** [net-snmp/net-snmp#10]
snmpd.conf proc with name containing spaces ignores values for Max and Min
e.q.

proc "Plex Media Serv" 1 1

triggers an snmp trap with too many "Plex Media Serv" processes. Processes which don't contain a whitespace are not affected

**Comment by michelhandleitnl** [comment]
proc "Plex Media Serv" 1 1 in snmpd.conf, this is the trap that is send --> Process should not be running
V2 Trap received: Enterprise value: DISMAN-EVENT-MIB::mteTriggerFired ¶
DISMAN-EVENT-MIB::mteHotTrigger value: process table ¶
DISMAN-EVENT-MIB::mteHotOID value: UCD-SNMP-MIB::prErrorFlag.3 ¶
DISMAN-EVENT-MIB::mteHotValue value: 1 ¶
(Description:The value of the object at mteTriggerValueID when a trigger fired.)
UCD-SNMP-MIB::prNames.3 value: Plex Tuner Serv ¶
UCD-SNMP-MIB::prErrMessage.3 value: Plex Tuner Serv process should not be running. ¶

**Comment by bvanassche** [comment]
Which Net-SNMP version are you using?

**Comment by michelhandleitnl** [comment]
5.7.3

**Comment by bvanassche** [comment]
The v5.7 branch is no longer supported. A candidate fix has been checked in on the v5.8 and master branches. Please retest.
