### ISSUE TITLE
running configure on Mac OS Catalina, fails on missing constants

### ISSUE THREAD

**Issue by briantmeyer** [net-snmp/net-snmp#101]
Using catalina 10.15.4 (19E287)
Installing net-snmp-5.8 ( the current release )

I got the following errors compiling.
/Users/brianmeyerdesign/agility/src/net-snmp-5.8/agent/mibgroup/mibII/tcp.c:343:21: error: use of undeclared identifier 'TCPTV_MIN'
        ret_value = TCPTV_MIN / PR_SLOWHZ * 1000;
                    ^
/Users/brianmeyerdesign/agility/src/net-snmp-5.8/agent/mibgroup/mibII/tcp.c:351:21: error: use of undeclared identifier 'TCPTV_REXMTMAX'
        ret_value = TCPTV_REXMTMAX / PR_SLOWHZ * 1000;

I read someone noting that they didn't have a darwinXX.h file for their specific version of darwin, these seem to just include the previous file, so I duplicated darwin17.h, made a darwin18.h and a darwin19.h ( not really sure the darwin version ), adjusted each to just include the previous header file, doing that the code compiles.

You might want to do 20 an 21 so it deals with a few more versions, or solve this in some other way.

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.8 and master branches. Please retest.

**Comment by briantmeyer** [comment]
Seems to work, using my script as is didn't as its downloading from 
https://gigenet.dl.sourceforge.net/project/net-snmp/net-snmp/5.8/net-snmp-5.8.tar.gz
I am assuming that isn't updated yet, the new files are not there.

But just going in to the git code repository here, downloading the master, and using that code instead works fine instead, compiles with no problems with my having to adjust any of the files.

Thank you.

**Comment by briantmeyer** [comment]
5.8-patches, from the git hub repository also compiles without issues, I'd say this issues is closed.
