### ISSUE TITLE
build_oid can smash stack

### ISSUE THREAD

**Issue by flipper33** [net-snmp/net-snmp#110]
build_oid calls build_oid_noalloc() with in_len of sizeof(tmpout).  With 8 byte oid, that's 1024.
build_oid_noalloc() takes in_len to be a count of oid, not count of bytes.

We found an oid of length 134 triggers the stack protector.

We believe that the value passed down should be MAX_OID_LEN.

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.8 and master branches. Please review and/or retest.

**Comment by flipper33** [comment]
On Mon, 4 May 2020, Bart Van Assche wrote:

> A candidate fix has been checked in on the v5.8 and master branches. Please review and/or retest.

looks good to me.  This came from a customer, so I don't have the 
environment to retest.

thanks for the quick turnaround.
