### ISSUE TITLE
Is there any default SNMP user available

### ISSUE THREAD

**Issue by manojv-infoblox** [net-snmp/net-snmp#114]
Is there any default SNMP user is available for snmpv1,snmpv2 and snmpv3 versions?. Like snmp3vuser as default user name and default password as system defined password.

**Comment by hardaker** [comment]
No, it is very unsafe to ship default usernames and passwords.  You must create one yourself.

Note that for the client-side applications you can do this in your ~/.snmp.conf file (see the snmp.conf manual page).
