### ISSUE TITLE
Applying patch 0002-snmplib-snmp_api-Remove-the-request-on-the-session-w.patch on net-snmp_5.8.tgz resulting to multiple SEGFAULTs in snmpwalk, snmpget, etc.

### ISSUE THREAD

**Issue by Umakumar01** [net-snmp/net-snmp#118]
To solve https://sourceforge.net/p/net-snmp/patches/1391/?limit=25 this issue, I have applied 0002-snmplib-snmp_api-Remove-the-request-on-the-session-w.patch and Bug#2914 patch. But it results to SEGFAULT when snmpwalk is executed. Could anyone please confirm whether this patch alone is enough to solve corrupted-double-linked-list error. 

BT for snmpwalk crash with the patches:
`[ukumar362@ip-96-114-220-237 ~]$ getbt -i AX013AN_VBN_stable2_20200514104145sdy -c  https://crashportal.stb.r53.xcal.tv/coredumps/AX013AN/c5//094f59e6b710763814259e95de1e4c67109ba66f_macA811FC82CCE1_dat2020-05-14-11-51-06_boxXG1_modAX013AN_1589452992_core.prog_snmpwalk.signal_11.core.tgz
Downloading file               [==================================================] 100%
crashed_binary_name :  snmpwalk
jenkins_project_regex :  (((AX013AN)|(ARRISXG1V3)).Yocto-Build(-2-1)?)$
jenkins_projects ['ARRISXG1V3-Yocto-Build']
build_names :  [['AX013AN_VBN_stable2_20200514104145sdy.tgz', 'AX013AN_VBN_stable2_20200514104145sdy.rootfs.tar.gz'], ['AX013AN_VBN_stable2_20200514104145sdy-dbg.rootfs.tar.gz']]
build_path :  /mnt/RTWF/STB/builds/AX013AN_VBN_stable2_20200514104145sdy/
crashed_binary_path /mnt/RTWF/STB/builds/AX013AN_VBN_stable2_20200514104145sdy/usr/bin/snmpwalk

BT

Core was generated by `snmpwalk -OQ -v 2c -c  localhost 1.3.6.1.4.1.17270.9225.2.1.9.1.2'.
Program terminated with signal 11, Segmentation fault.
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997
#1  0x76f11660 in __GI___libc_free (mem=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:2982
#2  0x7702f098 in snmp_free_var_internals (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5429
#3  0x7702f148 in snmp_free_var (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5445
#4  0x7702f1b0 in snmp_free_varbind (var=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5455
#5  0x770341ec in snmp_free_pdu (pdu=0x51ef08) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5495
#6  0x77036ee0 in remove_request (rp=0x51c020, orp=<optimized out>, isp=0x521dd0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6698
#7  snmp_sess_timeout (sessp=0x51eb28) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6865
#8  0x77036f78 in snmp_timeout () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6683
#9  0x7700d154 in snmp_synch_response_cb (ss=0x526448, pdu=<optimized out>, response=0x7f90bfd0, pcb=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1085
#10 0x7700d1d8 in snmp_synch_response (ss=<optimized out>, pdu=<optimized out>, response=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1126
#11 0x004010c0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/apps/snmpwalk.c:315

BT FULL

Core was generated by `snmpwalk -OQ -v 2c -c  localhost 1.3.6.1.4.1.17270.9225.2.1.9.1.2'.
Program terminated with signal 11, Segmentation fault.
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997
__oldval = 0
__futex = 0x0
size = 1918985056
fb = <optimized out>
nextchunk = <optimized out>
nextsize = <optimized out>
nextinuse = <optimized out>
prevsize = <optimized out>
bck = <optimized out>
fwd = <optimized out>
errstr = 0x0
locked = 0
__func__ = "_int_free"
#1  0x76f11660 in __GI___libc_free (mem=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:2982
ar_ptr = <optimized out>
p = <optimized out>
hook = <optimized out>
#2  0x7702f098 in snmp_free_var_internals (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5429
No locals.
#3  0x7702f148 in snmp_free_var (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5445
No locals.
#4  0x7702f1b0 in snmp_free_varbind (var=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5455
ptr = 0x76ff4744 <main_arena+48>
#5  0x770341ec in snmp_free_pdu (pdu=0x51ef08) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5495
sptr = <optimized out>
#6  0x77036ee0 in remove_request (rp=0x51c020, orp=<optimized out>, isp=0x521dd0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6698
No locals.
#7  snmp_sess_timeout (sessp=0x51eb28) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6865
slp = 0x51eb28
sp = 0x526448
isp = 0x521dd0
rp = 0x51c020
orp = 0x0
freeme = 0x0
now = {tv_sec = 109, tv_usec = 958054}
callback = <optimized out>
magic = <optimized out>
sptr = <optimized out>
__func__ = "snmp_sess_timeout"
#8  0x77036f78 in snmp_timeout () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6683
slp = 0x51eb28
#9  0x7700d154 in snmp_synch_response_cb (ss=0x526448, pdu=<optimized out>, response=0x7f90bfd0, pcb=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1085
lstate = {waiting = 0, status = 2, reqid = 453709859, pdu = 0x0}
state = 0x7f90b800
cbsav = 0x0
cbmagsav = 0x0
numfds = 4
count = 0
fdset = {lfs_setsize = 1024, lfs_setptr = 0x7f90b758, lfs_set = {fds_bits = {0 <repeats 32 times>}}}
timeout = {tv_sec = 0, tv_usec = 0}
tvp = <optimized out>
block = 0
#10 0x7700d1d8 in snmp_synch_response (ss=<optimized out>, pdu=<optimized out>, response=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1126
No locals.
#11 0x004010c0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/apps/snmpwalk.c:315
session = {version = 1, retries = -1, timeout = -1, flags = 256, subsession = 0x0, next = 0x0, peername = 0x7f90ce7e "localhost", remote_port = 0, localname = 0x0, local_port = 0, authenticator = 0x0, callback = 0x0, callback_magic = 0x0, s_errno = 0, s_snmp_errno = 0, sessid = 0, community = 0x416080 "", community_len = 0, rcvMsgMaxSize = 65507, sndMsgMaxSize = 65507, isAuthoritative = 0 '\000', contextEngineID = 0x0, contextEngineIDLen = 0, engineBoots = 0, engineTime = 0, contextName = 0x0, contextNameLen = 0, securityEngineID = 0x0, securityEngineIDLen = 0, securityName = 0x0, securityNameLen = 0, securityAuthProto = 0x0, securityAuthProtoLen = 0, securityAuthKey = '\000' <repeats 63 times>, securityAuthKeyLen = 0, securityAuthLocalKey = 0x0, securityAuthLocalKeyLen = 0, securityPrivProto = 0x0, securityPrivProtoLen = 0, securityPrivKey = '\000' <repeats 63 times>, securityPrivKeyLen = 0, securityPrivLocalKey = 0x0, securityPrivLocalKeyLen = 0, securityModel = -1, securityLevel = 0, paramName = 0x0, trap_stats = 0x0, securityInfo = 0x0, transport_configuration = 0x0, myvoid = 0x0}
ss = 0x526448
pdu = 0x51ef08
response = 0x4d70e0
vars = <optimized out>
arg = <optimized out>
name = {1, 3, 6, 1, 4, 1, 17270, 9225, 2, 1, 9, 1, 2, 1998036984, 1, 0, 1, 4096, 1, 1997935220, 0, 10, 2140191952, 2140193084, 1998069760, 0, 4199712, 0, 10, 2140193230, 1997954432, 0, 1998037736, 2140192096, 2140193008, 1997841168, 1997840384, 3, 0, 126, 2140192016, 1997845796, 0, 1997848344, 0, 0, 1998069760, 0, 0, 0, 0, 2140192928, 2140192096, 0, 127, 1997846828, 0, 0, 0, 0, 1998069760, 0, 1997840384, 0, 1997840744, 0, 0, 0, 0, 0, 0, 0, 0, 1997840792, 1997840752, 1997840760, 1997840768, 0, 0, 0, 1997840776, 1997840784, 0, 0, 1997840744, 0, 0, 1997840800, 1997840808, 1997840816, 0 <repeats 15 times>, 1997840824, 0, 0, 0, 1997840832, 1997840840, 0, 0, 0, 1997840848, 0, 0, 0, 0, 0, 0, 1997840856, 1997840864, 1997840872, 0, 0, 0, 0}
name_length = 13
root = {1, 3, 6, 1, 4, 1, 17270, 9225, 2, 1, 9, 1, 2, 1998036720, 2, 0, 1997841168, 1997963408, 1997955296, 1997842156, 1997887376, 1997887376, 0, 1997841168, 1998037736, 1998036720, 0, 1998020608, 0, 4294901759, 1998069760, 0, 1998037736, 1997860720, 0, 0, 0, 0, 0, 0, 0, 0, 1998069760, 0, 1, 0 <repeats 65 times>, 2140193060, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1997887908, 1998039040, 1, 1997981520, 1998036992, 1998020608, 1, 0}
rootlen = 13
end_oid = {1, 3, 6, 1, 4, 1, 17270, 9225, 2, 1, 9, 1, 3, 4294967295, 4294967295, 4294967295, 0, 4294967295, 4294967295, 4294967295, 1998069760, 4294967295, 1998069760, 124019232, 0, 2140191192, 1998027300, 1997841786, 2140191204, 1997880892, 1998024384, 1998020608, 2140191096, 2140191296, 0, 1997841680, 32, 1997841696, 1998039040, 2140191000, 2140191004, 0, 1998069760, 1997896632, 0, 0, 7, 1997841696, 1997879384, 0, 3875601, 1998036720, 2140191004, 2140191000, 1997956588, 32, 1998069760, 1998025304, 1998039040, 124019232, 1998037736, 1998021264, 1998028608, 1997841786, 0, 2140191320, 2140191096, 1997882456, 1998069760, 1998023480, 1992951608, 1997841680, 2140191192, 1998021172, 5, 1998028608, 1, 0, 0, 1998039040, 1998069760, 1997947872, 1992951608, 1997937112, 1992950320, 1992950336, 1992952504, 1998026312, 1998069760, 1992952456, 2140191192, 1997912368, 1997841680, 1998039040, 1998022456, 156797908, 2140191204, 2140191192, 0, 0, 1998069760, 1998022288, 1998040064, 0, 1998037736, 1997841696, 1998021264, 1997842220, 1998037732, 0, 1998069760, 1998039040, 1997945452, 1997895868, 0, 1998036708, 1998069760, 1998021264, 1998028608, 0, 1, 0, 1998069760, 2140191512, 0, 0, 0, 0}
end_len = 13
count = <optimized out>
running = 1
status = 1
check = 1
exitval = 0
tv1 = {tv_sec = 2, tv_usec = 0}
tv2 = {tv_sec = 0, tv_usec = 1998021172}
tv_a = {tv_sec = 1996475904, tv_usec = 4196448}
tv_b = {tv_sec = 0, tv_usec = 0}

THREAD APPLY ALL BT

Core was generated by `snmpwalk -OQ -v 2c -c  localhost 1.3.6.1.4.1.17270.9225.2.1.9.1.2'.
Program terminated with signal 11, Segmentation fault.
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997

Thread 1 (LWP 8085):
#0  0x76f0e098 in _int_free (av=0x0, p=0x51eef8, have_lock=0) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:3997
#1  0x76f11660 in __GI___libc_free (mem=<optimized out>) at /usr/src/debug/glibc/2.24-r0/git/malloc/malloc.c:2982
#2  0x7702f098 in snmp_free_var_internals (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5429
#3  0x7702f148 in snmp_free_var (var=0x525ed0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5445
#4  0x7702f1b0 in snmp_free_varbind (var=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5455
#5  0x770341ec in snmp_free_pdu (pdu=0x51ef08) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:5495
#6  0x77036ee0 in remove_request (rp=0x51c020, orp=<optimized out>, isp=0x521dd0) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6698
#7  snmp_sess_timeout (sessp=0x51eb28) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6865
#8  0x77036f78 in snmp_timeout () at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_api.c:6683
#9  0x7700d154 in snmp_synch_response_cb (ss=0x526448, pdu=<optimized out>, response=0x7f90bfd0, pcb=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1085
#10 0x7700d1d8 in snmp_synch_response (ss=<optimized out>, pdu=<optimized out>, response=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/snmplib/snmp_client.c:1126
#11 0x004010c0 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/net-snmp/5.8-r0/net-snmp-5.8/apps/snmpwalk.c:315
`

**Comment by bvanassche** [comment]
Please use https://github.com/net-snmp/net-snmp/archive/V5-8-patches.zip instead of applying patches to an old Net-SNMP version.
