### ISSUE TITLE
Undefined reference to snmp_enable_calllog when trying to compile tutorial code

### ISSUE THREAD

**Issue by Ecordonnier** [net-snmp/net-snmp#119]
Hi all,
I tried to compile the example code on http://www.net-snmp.org/wiki/index.php/TUT:Writing_a_Subagent , using "make example-demon", on my Debian 9 PC. This was throwing some errors about undefined reference until I renamed the file from "Makefile.txt" to "Makefile". Also "make -n" was showing that the variable assignment was not working in the Makefile before the rename. This is an old issue apparently: https://sourceforge.net/p/net-snmp/mailman/message/32932236/

I would be happy to fix the Makefile, however this code is not in the github repository at the moment (as far as I understand the migration from the sourceforge wiki to github is work in progress?).

**Comment by bvanassche** [comment]
Can you have a look at the files at https://github.com/net-snmp/subagent-example? I will update the wiki once I have figured out how to add new links to the wiki.

**Comment by Ecordonnier** [comment]
Thanks, I sent a tiny pull request removing Werror to make the files compile.
