### ISSUE TITLE
Unnecessary use of keyword register prevent compiling with newer C++ versions

### ISSUE THREAD

**Issue by jbulow** [net-snmp/net-snmp#128]
The use of the keyword "register" causes error when compiling with newer C++ standards (C++17 and higher). 

Also, the use of the register keyword does not add any value.

https://github.com/net-snmp/net-snmp/blob/41553b0cb6cf4ccca7edf7eca471b46724664e6c/include/net-snmp/library/mib.h#L484

**Comment by hardaker** [comment]
Yeah, it's long past time.  "back in my day" it actually did make a difference.
