### ISSUE TITLE
context name  is not handled properly in  the snmpv3_verify_msg() function

### ISSUE THREAD

**Issue by xiero** [net-snmp/net-snmp#131]
When using SNMPv3, if a context name is not provided using the -n switch, net-snmp silently assumes that a context name of zero length was provided.

If an SNMPv3-capable device returns a non-empty context name and this was not specified on the command line, this causes net-snmp to silently discard the response packet, even though it is valid. Only a timeout warning is given when the -DALL switch is used to diagnose the problem.

I do not think this is the expected behaviour. The context name is not a security feature, the user is not required to know it to be allowed to make queries. It could even change between requests (e.g. if an OID is found in a different context), so it would be very tedious (and in some cases difficult) for the user to specify it for every request.

This could be solved by modifying the test for context name in snmpv3_verify_msg:

	/* Only validate the context name if the user supplied one.*/
    if (rpdu->contextName && 	
		(rpdu->contextNameLen != pdu->contextNameLen ||
        memcmp(rpdu->contextName, pdu->contextName, pdu->contextNameLen)))
        return 0;

If the user does not specify a context name using the -n switch on the command line, rpdu->contextName will be NULL and the check will not be carried out.

The other problem is that net-snmp gives no indication of why the response packet was discarded. It just says at the very end of the log that the PDU was unhandled and there was a timeout:

trace:  ..\..\snmplib\snmp_api.c, 5489:
sess_process_packet: received message id#2474 reqid#1836 len 169
trace:  ..\..\snmplib\snmp_api.c, 5709:
sess_process_packet: unhandled PDU
trace:  ..\..\snmplib\snmp_api.c, 6283:
sess_select: for all sessions: 600 (to in 1591165267.970000 sec)
verbose:sess_select: timer due *real* soon. 717000 usec
verbose:sess_select: setting timer to 0.717000 sec, clear block (was 1)
trace:  ..\..\snmplib\snmp_client.c, 175:
snmp_synch: Response (ReqID: 1836 - Cmd 161)
Timeout: No Response from 192.168.1.3

This could be improved by adding debug messages to each failed check in snmpv3_verify_msg.

**Comment by hardaker** [comment]
So the SNMP specifications state (when processing a response):

```
   (1) If the received values of messageProcessingModel, securityModel,
       securityName, contextEngineID, contextName, and pduVersion are
       not all equal to the values used in the original request, the
       response is discarded.
```
(RFC3413)

I believe that the contextName actually is supposed to be supplied exactly, with "" being the default context.  I don't believe the agent should be returning a different value in the contextName field when "" is given.

Closing, but feel free to reopen if you think this is wrong.
