### ISSUE TITLE
netsnmp version 5.8  v2c  unable to  handle $ symbol

### ISSUE THREAD

**Issue by leechenbo** [net-snmp/net-snmp#134]
Hi,
I set the snmp v2c community to Monitor77#I111$$, use the below command
snmpwalk  -v2c -c Monitor77#I111$$ 8.46.1.108 1.3.6.1.2.1.1.5
objdump capture the udp Datagram ，the community is Monitor77#I11132037 ， the picture as below:
![image](https://user-images.githubusercontent.com/49008960/84342469-36dd9b80-abd8-11ea-9bb1-63682c6ccdf2.png)
root@zabbix:~/install/bin# ./snmpwalk --version
NET-SNMP version: 5.8
Have you ever encountered this problem?

**Comment by nielsb** [comment]
Hi,
your shell expands $$ to its PID

/Niels

**Comment by leechenbo** [comment]
Why is the 5.7.3 version not restricted?
