### ISSUE TITLE
net-snmp doesn't work for V3

### ISSUE THREAD

**Issue by hrachyam** [net-snmp/net-snmp#138]
Hi All,

I have installed and configure net-snmp 5.8.1.pre2 to send and get snmptrap on port 162.
It works for v3 SHA and AES but it doesn't work for v3 SHA-512 and AES-256.
I noticed strange behavior when specifying SHA-512 and AES-256 in the config file "snmptrapd.conf " and SHA and AES for snmptrap it works but it doesn't work when specifying SHA-512 and AES-256 for snmptrap command.

Please note that I have installed the net-snmp tool from sources:
(./configure --enable-blumenthal-aes --with-openssl).

Here are some information about my environments:

uname -a
Linux hrach-virtual-machine 4.4.0-184-generic #214-Ubuntu SMP Thu Jun 4 10:14:11 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

hrach@ubuntu:~$ snmptrapd --version
NET-SNMP Version:  5.8.1.pre2

hrach@ubuntu:~$ snmptrap --version
NET-SNMP version: 5.8.1.pre2

snmptrap --help
USAGE: snmptrap [OPTIONS] AGENT TRAP-PARAMETERS

  Version:  5.8.1.pre2
  Web:      http://www.net-snmp.org/
  Email:    net-snmp-coders@lists.sourceforge.net

OPTIONS:
  -h, --help		display this help message
  -H			display configuration file directives understood
  -v 1|2c|3		specifies SNMP version to use
  -V, --version		display package version number
SNMP Version 1 or 2c specific
  -c COMMUNITY		set the community string
SNMP Version 3 specific
  -a PROTOCOL		set authentication protocol (MD5|SHA|SHA-224|SHA-256|SHA-384|SHA-512)
  -A PASSPHRASE		set authentication protocol pass phrase
  -e ENGINE-ID		set security engine ID (e.g. 800000020109840301)
  -E ENGINE-ID		set context engine ID (e.g. 800000020109840301)
  -l LEVEL		set security level (noAuthNoPriv|authNoPriv|authPriv)
  -n CONTEXT		set context name (e.g. bridge1)
  -u USER-NAME		set security name (e.g. bert)
  -x PROTOCOL		set privacy protocol (DES|AES|AES-192|AES-256)
  -X PASSPHRASE		set privacy protocol pass phrase
  -Z BOOTS,TIME		set destination engine boots/time

grep -v '^#' /usr/local/etc/snmp/snmptrapd.conf | grep -v '^$'
createUser -e 68756A67005909494F088099FBF7BE692EC1 testuser SHA-512 mySecureAuthPassword AES-256 mySecurePrivPassword
authUser log,execute,net testuser
createUser -e 0x090807060504030201 the_user_name SHA the_SHA_string AES the_AES_string
authUser log,execute,net the_user_name

snmptrapd -f -Lo

sudo snmptrap -e 0x68756A67005909494F088099FBF7BE692EC1 -v 3 -u testuser -a SHA -A mySecureAuthPassword -x AES -X mySecurePrivPassword -l authPriv < HOST IP ADDRESS > 1 1.3.6.1.6.3.1.1.5.1      **(WORKS: Data is received from snmptrap)**

sudo snmptrap -e 0x68756A67005909494F088099FBF7BE692EC1 -v 3 -u testuser -a SHA -A mySecureAuthPassword -x AES -X mySecurePrivPassword -l authPriv < HOST IP ADDRESS > 1 1.3.6.1.6.3.1.1.5.1      **(ERROR: Authentication failed for testuser)**

Please let me know if you need additional information.

Thanks,
Hrach

**Comment by hardaker** [comment]
In that last command you're not telling it to use the right algorithms.  It should be:

sudo snmptrap -e 0x68756A67005909494F088099FBF7BE692EC1 -v 3 -u testuser -a SHA-512 -A mySecureAuthPassword -x AES-256 -X mySecurePrivPassword -l authPriv < HOST IP ADDRESS > 1 1.3.6.1.6.3.1.1.5.1

If this doesn't fix the problem, let us know.
