### ISSUE TITLE
how to find actual physical interface of a device in the list of OIDs

### ISSUE THREAD

**Issue by alisiddiqui1987** [net-snmp/net-snmp#139]
Hi Team,

My developer is having difficulty in finding the physical interfaces of the devices in Net-SNMP.

It is providing OIDs and from the list of OIDs it is getting very difficult for us to find out the interfaces.

There is no documentation available for syntax of sub commands like iftype etc and where to use and where and what arguments to pass or receive via them.

A quick assistance will be much appreciated as my project completion is stuck on the last few steps due to this.

Thanks & Best Regards,
Ali

**Comment by alisiddiqui1987** [comment]
any update please?

**Comment by hardaker** [comment]
I'm afraid i can't quite follow what you're trying to do or what you're missing.  Which physical interfaces are you referring to?  The interfaces table's list of network interfaces?  Are you missing the types themselves?  Are you missing where the code is fetching iftypes from?

I'm going to take a random guess and say you might want the definition of IANAifType found in mibs/IANAifType-MIB.txt

I'm going to close this but feel free to reopen if you want  to provide more details on what you're missing exactly.
