### ISSUE TITLE
About syslog priority of the message "truncating integer value >32 bits"

### ISSUE THREAD

**Issue by miztake** [net-snmp/net-snmp#144]
"Truncating integer value >32 bits" is output 497 days after booting.
The reason is that hrSystemUptime exceeds 32 bits after 497 days.
A similar issue occurs with sysUpTime.

If these values exceed 497 days after booting,
the error message will be outputted each time these are accessed.
However, there is no way to deal with this error message (No action is required.).

If the priority is LOG_ERR, the user will mistakenly recognize that
the system has entered an abnormal state.
So, I think the priority of this message is LOG_INFO rather than LOG_ERR.
because the user does not need to take any action for the message.

**Comment by BenoitPel** [comment]
same for me ...
