### ISSUE TITLE
configure is broken for re-runs of config.status due to pcre changes

### ISSUE THREAD

**Issue by hardaker** [net-snmp/net-snmp#152]
The configure script is failing to remember that -lpcre should be in LAGENTLIBS.

./configure ...

grep LAGENTLIBS agent/Makefile
LAGENTLIBS	=  -lpcre 

./configure (leaving config.cache around)

grep LAGENTLIBS agent/Makefile
LAGENTLIBS	=   

haven't chased down where the LAGENTLIBS is failing to get, but this is a release blocker.

**Comment by hardaker** [comment]
fixed in bbd53ed4a42929d0c93645e069b466daa4f0fbce

**Comment by krishnacx** [comment]
I am using net-snmp-5.9
@hardaker 
I am using ./configure -C  --without-perl-modules  --disable-embedded-perl  --disable-perl-cc-checks  --with-enterprise-sysoid="1.3.6.1.4.1.5951.6"  --disable-applications  --disable-manuals  --disable-scripts --with-default-snmp-version="3"  --with-sys-contact="citrix"  --with-sys-location="location"  --with-logfile="."  --with-persistent-directory="/var/mps/netsnmp/" --enable-mini-agent  --enable-reentrant  --with-mib-modules=mps,mpsGet  --with-cflags='-I/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/include -I/var/mps64/main/rs_ads_dev/usr.src/crypto/openssl/include -DOPENSSL_FIPS -DNETSCALER -DNETSNMP_NO_INLINE' --with-out-mib-modules="mibII/sysORTable"  **--without-pcre** --with-ldflags='-L/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/src/.libs -L/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto -lcrypto -Wl,-rpath,/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto -lzmq'

I still see -lpcre being used for generating libnetsnmpagent.so.40.0.0 and libnetsnmpmibs.so.40.0.0

libtool: link: cc -shared  -fPIC -DPIC  helpers/.libs/all_helpers.o helpers/.libs/baby_steps.o helpers/.libs/bulk_to_nex t.o helpers/.libs/cache_handler.o helpers/.libs/debug_handler.o helpers/.libs/instance.o helpers/.libs/mode_end_call.o h elpers/.libs/multiplexer.o helpers/.libs/null.o helpers/.libs/old_api.o helpers/.libs/read_only.o helpers/.libs/row_merg e.o helpers/.libs/scalar.o helpers/.libs/scalar_group.o helpers/.libs/serialize.o helpers/.libs/snmp_get_statistic.o hel pers/.libs/stash_cache.o helpers/.libs/stash_to_next.o helpers/.libs/table.o helpers/.libs/table_array.o helpers/.libs/t able_container.o helpers/.libs/table_data.o helpers/.libs/table_dataset.o helpers/.libs/table_iterator.o helpers/.libs/t able_row.o helpers/.libs/table_tdata.o helpers/.libs/watcher.o .libs/agent_handler.o .libs/agent_index.o .libs/agent_rea d_config.o .libs/agent_registry.o .libs/agent_sysORTable.o .libs/agent_trap.o .libs/kernel.o .libs/netsnmp_close_fds.o .
libs/snmp_agent.o .libs/snmp_vars.o mibgroup/mibII/.libs/vacm_conf.o mibgroup/snmpv3/.libs/usmConf.o   -Wl,-rpath -Wl,/v
ar/mps64/main/rs_ads_dev/usr.src/contrib/net-snmp/net-snmp-5.9/snmplib/.libs -Wl,-rpath -Wl,/var/mps64/main/rs_ads_dev/u sr.src/contrib/zeromq-4.1.0/src/.libs -Wl,-rpath -Wl,/usr/local/lib -L/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-
4.1.0/src/.libs/.libs ../snmplib/.libs/libnetsnmp.so -L/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/src/.libs
 -L/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto -L/usr/local/lib -lm **-lpcre** -lkvm -lcrypto /var/mps64 /main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/src/.libs/libzmq.so -lrt -lpthread -lelf -lpkg  -Wl,-no-undefined -Wl,-rpa
th -Wl,/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto   -Wl,-soname -Wl,libnetsnmpagent.so.40 -o .libs/
libnetsnmpagent.so.40.0.0

/.libs/util_funcs.o mibgroup/util_funcs/.libs/header_generic.o mibgroup/mibII/.libs/vacm_context.o mibgroup/util_funcs/.
libs/header_simple_table.o .libs/mib_modules.o .libs/auto_nlist.o   -Wl,-rpath -Wl,/var/mps64/main/rs_ads_dev/usr.src/co
ntrib/net-snmp/net-snmp-5.9/agent/.libs -Wl,-rpath -Wl,/var/mps64/main/rs_ads_dev/usr.src/contrib/net-snmp/net-snmp-5.9/
snmplib/.libs -Wl,-rpath -Wl,/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/src/.libs -Wl,-rpath -Wl,/usr/local /lib -L/var/mps64/main/rs_ads_dev/usr.src/contrib/net-snmp/net-snmp-5.9/snmplib/.libs -L/var/mps64/main/rs_ads_dev/usr.s
rc/contrib/zeromq-4.1.0/src/.libs/.libs ./.libs/libnetsnmpagent.so -L/var/mps64/main/rs_ads_dev/usr.src/contrib/zeromq-4
.1.0/src/.libs -L/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto -L/usr/local/lib /var/mps64/main/rs_ads _dev/usr.src/contrib/net-snmp/net-snmp-5.9/snmplib/.libs/libnetsnmp.so ../snmplib/.libs/libnetsnmp.so -lcrypto /var/mps6 4/main/rs_ads_dev/usr.src/contrib/zeromq-4.1.0/src/.libs/libzmq.so -lrt -lpthread -lkvm -lm -**lpcre** -lelf -lpkg  -Wl,-no-
undefined -Wl,-rpath -Wl,/usr/obj/var/mps64/main/rs_ads_dev/usr.src/secure/lib/libcrypto   -Wl,-soname -Wl,libnetsnmpmib
s.so.40 -o .libs/libnetsnmpmibs.so.40.0.0

Is there anyway to avoid lpcre being linked the libs. Also, please suggest a way to avoid lpkg as well from linking.
