### ISSUE TITLE
Unable to build net-snmp 5.9 WIN32 via win32/build.bat caused by missing identifier NETSNMP_ATTRIBUTE_UNUSED on agent\mibgroup\agent\extend.c

### ISSUE THREAD

**Issue by bandhit** [net-snmp/net-snmp#171]
I download net-snmp 5.9 from [sourceforge](https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9/net-snmp-5.9.zip/download) recently, and try compiling source file via MSVC 14.2 (VS2019) with win32/build.bat. I got syntax error caused by missing identifier NETSNMP_ATTRIBUTE_UNUSED on [agent\mibgroup\agent\extend.c](https://github.com/net-snmp/net-snmp/blob/master/agent/mibgroup/agent/extend.c).

But when I remove NETSNMP_ATTRIBUTE_UNUSED on the line 649 and 651, I got build successful and able to install it without any problem.

**My question:** Is it correct way to build on WIN32? Or do I need to set any option to enable that NETSNMP_ATTRIBUTE_UNUSED?

Tested system:
OS Name: Windows 10 1903
System Type: x64-based PC
Compiler: MSVC 14.2 (Microsoft Visual Studio Community 2019)
Perl: v5.30.3 built for MSWin32-x64-multi-thread (strawberry perl)

This is my setting:
```
---------------------------------------------------------
            Net-SNMP configuration summary:
---------------------------------------------------------

  Version:                    5.9
  Config type:                release
  SDK:                        disabled
  Link type:                  static
  Prefix / Destdir:           c:/usr
  OpenSSL:                    disabled
  Blumenthal AES:             disabled
  IPv6 transport:             disabled
  winExtDLL agent:            disabled
```

This is the error:
```
...

Generating Code...
        cl.exe /I.. /I..\..\include /I..\..\agent /I..\..\agent\mibgroup /D NETSNMP_REMOVE_U64 /D VC_EXTRALEAN /D WIN32 /D _CONSOLE /D _CRT_NONSTDC_NO_WARNINGS /D _CRT_SECURE_NO_WARNINGS /D _MBCS /D _WIN32_WINNT=0xffff /D _WINSOCK_DEPRECATED_NO_WARNINGS /D WIN32_LEAN_AND_MEAN /EHsc /FD /FR.\release\ /Fd.\release\netsnmpmibs.pdb /Fo.\release\ /I C:\OpenSSL-Win32\include   -s -O2 -DWIN32 -DWIN64 -DCONSERVATIVE -D__USE_MINGW_ANSI_STDIO -DPERL_TEXTMODE_SCRIPTS -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DUSE_PERLIO -fwrapv -fno-strict-aliasing -mms-bitfields  -I"C:\STRAWB~1\perl\lib\CORE"  /c /W3 /Zi /nologo /MD  /D NDEBUG /O2 ..\..\agent\mibgroup\agent\extend.c ..\..\agent\mibgroup\agent\nsCache.c ..\..\agent\mibgroup\agent\nsDebug.c ..\..\agent\mibgroup\agent\nsLogging.c ..\..\agent\mibgroup\agent\nsModuleTable.c ..\..\agent\mibgroup\agent\nsTransactionTable.c
cl : Command line warning D9002 : ignoring unknown option '-s'
cl : Command line warning D9002 : ignoring unknown option '-fwrapv'
cl : Command line warning D9002 : ignoring unknown option '-fno-strict-aliasing'
cl : Command line warning D9002 : ignoring unknown option '-mms-bitfields'
extend.c
..\..\agent\mibgroup\agent\extend.c(655): error C2146: syntax error: missing ';' before identifier 'NETSNMP_ATTRIBUTE_UNUSED'
..\..\agent\mibgroup\agent\extend.c(655): error C2065: 'NETSNMP_ATTRIBUTE_UNUSED': undeclared identifier
..\..\agent\mibgroup\agent\extend.c(657): error C2146: syntax error: missing ';' before identifier 'NETSNMP_ATTRIBUTE_UNUSED'
..\..\agent\mibgroup\agent\extend.c(657): error C2065: 'NETSNMP_ATTRIBUTE_UNUSED': undeclared identifier

...
```
Full build log is here [build.log](https://github.com/net-snmp/net-snmp/files/5124374/build.log).

Note: I have tried net-snmp 5.8 and there is no any problem.

Thanks for any update!

**Comment by bvanassche** [comment]
Removing NETSNMP_ATTRIBUTE_UNUSED is fine. An official fix is available here: https://github.com/net-snmp/net-snmp/commit/7266ff58d0a289ecff74492c39d60ed42da2e437 .

**Comment by bandhit** [comment]
Thanks for your reply, I cloned branch V5-9-patches and I got build successful and able to install it without any problem. Thanks :-)
It seem like you are moving the project to github, so I will follow the new package on github instead of sourceforge.
