### ISSUE TITLE
solaris cleanup commit in master from 2 years ago missing from 5.9 release

### ISSUE THREAD

**Issue by ypankov** [net-snmp/net-snmp#172]
Using net-snmp libraries as part of the project and trying to cleanup compile warnings on illumos (solaris) to enable -Werror, I noticed that it's already done in 4916ce00736296be79619d1debecbb74c7beee33 pushed 2 years ago, but  is missing even from 5.9 released several days ago.

I'm not familiar with net-snmp release process, so wonder if this is intentional?

**Comment by bvanassche** [comment]
Please take a look at commits 7f5b50d5c51572f59d4b8c799cc6a676b0f1340f and c13b4349fad05caaa97e69924c020cb02139a367 (V5-9-patches branch).

**Comment by ypankov** [comment]
Thank you!
