### ISSUE TITLE
snmp_parse_oid is missing a check against null 

### ISSUE THREAD

**Issue by sgmr29** [net-snmp/net-snmp#177]
Just working through more Fortify issues. It looks like malloc could return NULL here, and then we'd snprintf to it.
https://github.com/net-snmp/net-snmp/blob/a955b8136a6431ba347a03fc8264147be16a746b/snmplib/mib.c#L6096-L6102

**Comment by bvanassche** [comment]
Please take a look at commit https://github.com/net-snmp/net-snmp/commit/6093d4aee5cc81b8121458864d7e25fa7f46a7ba.
