### ISSUE TITLE
darwin headers were tidied, but Makefile.in still lists them all

### ISSUE THREAD

**Issue by sthen** [net-snmp/net-snmp#181]
'make install' fails for me, it tries to install the various numbered darwin headers from include/system/darwin/darwin(7-17).h but these were removed and only darwin.h exists.

I'm not sure why I'm seeing a failure and other users don't seem to have reported this, but anyway it looks like the extra entries in INCLUDESUBDIRHEADERS should be removed?

**Comment by bvanassche** [comment]
Does commit 52d4a465dcd92db004c34c1ad6a86fe36726e61b help?

**Comment by sthen** [comment]
Yes, thanks.
