### ISSUE TITLE
User with multiple OIDs

### ISSUE THREAD

**Issue by dj95035** [net-snmp/net-snmp#186]
Hi All,

    Is there a way to configure a user with multiple OIDs?

Thanks,
Jenny

**Comment by dj95035** [comment]
I have tried to repeat the same user multiple times with different OID in snmpd.conf, but only the first one is taken.

Your help is appreciated.
Jenny

**Comment by nielsb** [comment]
It is not quite clear to me what you try to do, but I guess that you should look at the view option to the rouser/rwuser directive you probably are using.
/Niels

**Comment by dj95035** [comment]
Hi Niels,

     I must have checked an old man page where does not have the view option for rouser/rwuser.
I just found a new man page which shows how to use view for user.

Thanks a lot for your help.
Jenny
