### ISSUE TITLE
netsnmp5.9 does not compile for architecture aarch64

### ISSUE THREAD

**Issue by FinzelStefan** [net-snmp/net-snmp#188]
As netsnmp5.9 is using an old config,guess it does not compile for newer architectures like aarch64.
Simple solution is to replace config.guess by last version of config.guess available on
https://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess

**Comment by bvanassche** [comment]
config.guess has been updated on the V5-9-patches and master branches. Please retest.
