### ISSUE TITLE
snmpd exit quietly on macOS

### ISSUE THREAD

**Issue by ibigbug** [net-snmp/net-snmp#195]
Hi,

running

```
sudo /usr/local/opt/net-snmp/sbin/snmpd -f -c /etc/snmp/snmpd.conf -D all
```

on macOS just fails with exit code 1 and nothing output on screen for error message.

How should I debug why it's failing to start?

system: 

```
$ uname -a
Darwin awesome-iMac 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```

software: 

```
$ sudo /usr/local/opt/net-snmp/sbin/snmpd -v

NET-SNMP version:  5.9
Web:               http://www.net-snmp.org/
Email:             net-snmp-coders@lists.sourceforge.net
```

Thanks

**Comment by bvanassche** [comment]
Does the following procedure reveal why snmpd fails to start?
* sudo su
* gdb /usr/local/opt/net-snmp/sbin/snmpd
* break exit
* break abort
* run -f -Lo -c /etc/snmp/snmpd.conf

**Comment by ibigbug** [comment]
running inside gdb didn't exit and it blocks at `[New Thread 0xd03 of process 3229]`

However running directly with `-Lo` gives some outputs:

```
sh-3.2# /usr/local/opt/net-snmp/sbin/snmpd -f -c /etc/snmp/snmpd.conf -D all -Lo
/dev/kmem: No such file or directory
/dev/mem: No such file or directory
Agent initialization failed
```

not sure does this help?

**Comment by bvanassche** [comment]
Yes, this helps. Please try to add the option `-r`to the snmpd command-line options.

**Comment by ibigbug** [comment]
Great it works! 

though adding `-LSwd` by running fails

```
$ /usr/local/opt/net-snmp/sbin/snmpd -Dall -rfc /etc/snmp/snmpd.conf -LSwd -Lo
```

and gives

```
[1]    5053 illegal hardware instruction  /usr/local/opt/net-snmp/sbin/snmpd -Dall -rfc /etc/snmp/snmpd.conf -LSwd -Lo
```

now sure how to debug this.

btw, should I create separate issue for this?
