### ISSUE TITLE
Include the sreclaimable patch

### ISSUE THREAD

**Issue by johnbritto1** [net-snmp/net-snmp#2]
Hello,

The memory mib is not calculating the exact free memory due to missing slab value. There was a patch proposed here: https://sourceforge.net/p/net-snmp/patches/1338/

Not sure why the patch wasn't merged with master.

Any idea?

Thanks,

**Comment by bvanassche** [comment]
If nobody beats me to it I will have a look later this week.

**Comment by johnbritto1** [comment]
Any update on this?

Thanks

**Comment by bvanassche** [comment]
As explained in https://sourceforge.net/p/net-snmp/patches/1338/, the sreclaimable patch has been applied on the v5.8 and master branches.
