### ISSUE TITLE
Infinite loop due to integer overflow

### ISSUE THREAD

**Issue by wengyusu** [net-snmp/net-snmp#210]
#207 

https://github.com/net-snmp/net-snmp/blob/7c3723cf539ed7480522d2498752fb14b2fe16d7/agent/mibgroup/util_funcs/header_simple_table.c#L97

when operating GETNEXT to the OID 1.3.6.1.4.1.2021.9.1.1.4294967295,  the `(int)newname[*length - 1]` becomes `-1` since `newname[*length - 1]=4294967295`(0XFFFFFFFF) that breaks the comparison and causes an infinite loop. As a result, the SNMPD will stuck, and CPU usage reaches 100%.

**Comment by bvanassche** [comment]
Please take a look at commit ebe677ea1be61df6589a28a5b6306fe55f5784b2.
