### ISSUE TITLE
[bug] redefinition of symbols in netsnmp 5.9 with Visual Studio

### ISSUE THREAD

**Issue by Johnnyxy** [net-snmp/net-snmp#213]
Hi there,
I am compiling net-snmp 5.9 with several Visual Studio versions. The compilation works as expected.
But when including net-snmp in other projects with Visual Studio, the compiler complains about a redefinition of the stdint.h/cstdint types like ```uint8_t```, ```int8_t```, ...

I have tracked down the problem to this line: https://github.com/net-snmp/net-snmp/blob/c4d46f9f7b5b32bf1d6b61d09bdabaae4ff3cd7a/win32/net-snmp/net-snmp-config.h#L709-L711

For Visual Studio the macro ```HAVE_STDINT_H``` does not get set. I have patched the ```#if``` line to include the compiler version detection as stdint.h/cstdint has been introduced in MSVC since version 16.00 (shipped with VS2010).

```c
#if defined(__MINGW32__) || (defined(_MSC_VER) && (_MSC_VER >= 1600))
#define HAVE_STDINT_H 1
#endif
```

Patch file:
[msvc_stdint.patch.txt](https://github.com/net-snmp/net-snmp/files/5567615/msvc_stdint.patch.txt)

**Comment by bvanassche** [comment]
Thanks for the patch! Please take a look at commit 281e6fc9454a785d9a4487d35146724dadcfbf62.
