### ISSUE TITLE
snmpd core dump error when using snmpv3 disk option in /etc/snmp/snmpd.conf

### ISSUE THREAD

**Issue by nassim124** [net-snmp/net-snmp#214]
NET-SNMP version:  5.8
System: Linux 4.18.0-147.el8.x86_64

I have the following error when I try to add a lot of "disk" lines in snmpd.conf

Started Process Core Dump (PID 24899/UID 0).
Nov 19 15:05:51 systemd-coredump[24900]: 
Process 22773 (snmpd) of user 0 dumped core.#012#012Stack trace of thread 22773:
#012#0  0x00007fe2694518df raise (libc.so.6)
#012#1  0x00007fe26943bcf5 abort (libc.so.6)
#012#2  0x00007fe269494c17 __libc_message (libc.so.6)
#012#3  0x00007fe26949b53c malloc_printerr (libc.so.6)
#012#4  0x00007fe26949cdb7 _int_free (libc.so.6)
#012#5  0x00007fe26adb3295 usm_generate_out_msg (libnetsnmp.so.35)
#012#6  0x00007fe26adb3b09 usm_secmod_generate_out_msg (libnetsnmp.so.35)
#012#7  0x00007fe26ad56f12 snmpv3_packet_build (libnetsnmp.so.35)
#012#8  0x00007fe26ad58f47 snmp_build (libnetsnmp.so.35)
#012#9  0x00007fe26ad5946b netsnmp_build_packet (libnetsnmp.so.35)
#012#10 0x00007fe26ad59686 _build_initial_pdu_packet (libnetsnmp.so.35)
#012#11 0x00007fe26b5c1539 netsnmp_wrap_up_request (libnetsnmpagent.so.35)
#012#12 0x00007fe26b5c46eb netsnmp_handle_request (libnetsnmpagent.so.35)
#012#13 0x00007fe26b5c4a0a handle_snmp_packet (libnetsnmpagent.so.35)
#012#14 0x00007fe26ad61732 _sess_process_packet (libnetsnmp.so.35)
#012#15 0x00007fe26ad627c6 _sess_read (libnetsnmp.so.35)
#012#16 0x00007fe26ad632fd snmp_sess_read2 (libnetsnmp.so.35)
#012#17 0x00007fe26ad6334b snmp_read2 (libnetsnmp.so.35)
#012#18 0x000055d935631377 receive (snmpd)#012#19 0x000055d93563066e main (snmpd)
#012#20 0x00007fe26943d873 __libc_start_main (libc.so.6)#012#21 0x000055d935630abe _start (snmpd)

I struggled to find out why, but when I use this configuration it works: 

disk /boot 25%
disk /home 25%
disk /backup 25%
disk /var/lib/mysqldata/data 25%
disk /var/lib/mysqldata/log 25%
disk /var/lib/mysqldata/tm 25%

But by adding one line or only one character in one line ex: "p" in the last line "disk /var/lib/mysqldata/tmp 25%", snmpd crashes.

I have seen similar issues about memory crash but no found any of them talking about disk usage.

**Comment by jridky** [comment]
Hi, may I ask you for output of `rpm -q net-snmp` command?

**Comment by nassim124** [comment]
Hi @jridky, 

I have this output : net-snmp-5.8-12.el8_1.x86_64

 thank you

**Comment by jridky** [comment]
Than I would suggest you to update to the latest available, because there were some fixes later on in RHEL-8, so this might be already fixed.

If no update is available for you, I would suggest to contact Red Hat support as well, so we will be able to track and fix this issue once the solution is available.

Anyway, I'll try to reproduce this with the latest net-snmp-5.9, to be sure about presence of the issue in the current upstream version.
