### ISSUE TITLE
python3 bindings fails with Hex-STRING

### ISSUE THREAD

**Issue by dheule** [net-snmp/net-snmp#216]
On my Linux System with NET-SNMP version:  5.9 I found the follwoing problem in the python3 binding:

If you try to recive an Hex-String value, it fails. If this Hex-String is a part of walk or bulk operation, it segfaults the whole python.

Example test script:
```
#!/usr/bin/python3

import netsnmp

session = netsnmp.Session(DestHost='localhost', Community='public', Version=2, Timeout=2000000, Retries=5, UseNumeric=1)

print("Try to recive a Hex-STRING via get:")
try:
    myvar = netsnmp.VarList(netsnmp.Varbind('.1.3.6.1.6.3.10.2.1.1.0'))
    session.get(myvar)

    for var in myvar:
        print(var)

except Exception as e:
    print(e)

print("Try to recive a Hex-STRING as part of walk or bulk:")
myvar = netsnmp.VarList(netsnmp.Varbind('.1.3.6.1.6.3.10'))
session.walk(myvar)

for var in myvar:
    print(var)
```

gets the following output:

```
./test.py
Try to recive a Hex-STRING via get:
<built-in function get> returned a result with an error set
Try to recive a Hex-STRING as part of walk or bulk:
Segmentation fault
```

Please help to fix this, because it renders the whole binding unstable ...

**Comment by bvanassche** [comment]
Thanks for having reported this. I will take a look.

**Comment by bvanassche** [comment]
Please retest with the latest version of the V5-9-patches branch (https://github.com/net-snmp/net-snmp/tree/V5-9-patches).

**Comment by dheule** [comment]
I have tested, for my case it's workig. Thank you.

**Comment by bvanassche** [comment]
Thanks for the feedback!
