### ISSUE TITLE
Dynamic timeouts?

### ISSUE THREAD

**Issue by dagbdagb** [net-snmp/net-snmp#217]
Yesterday, I had a long debugging session with a class of devices which, in the end, resulted in having to increase the default SNMP timeout.

The devices managed to respond to the polling when polled with SNMPv2, but when polling with SNMPv3 I got partial results and finally a timeout. (For one particular enterprise mib.  By comparing the network capture from results from a device which works and one that fails, I found that the last GET was repeated at one second intervals and the device responds three times with data snmpwalk finds dissatisfying. Identical response all three times. By increasing the timeout (-t), all data was properly received and the timeout was elliminated.

When explaining the problem (and the solution) to my wife, she asked: why doesn't that timeout increase dynamically? Start out with 1 second, increase by one second for each retry.  Or double. Whatever.

Seeing my results above, I do wonder why as well. Asking the same question over and over and getting the same unsatisfying answer each time is kinda useless...

While I do not suggest changing the existing behavior of the -t parameter, I would like to know if a dynamic timeout is feasible. Thoughts?

**Comment by mivsvit** [comment]
Exponentially increasing (i.e dynamic)  timeouts has also a recommended best-practice from some router vendors.

See for example

[IOS XR SNMP Best Practices](https://www.cisco.com/c/en/us/td/docs/ios_xr_sw/iosxr_r3-9-1/mib/guide/crs-gsr_appe.html#wp1477030)

**Comment by bvanassche** [comment]
If the timeout increases dynamically, when to stop increasing the timeout? Regarding the link in the above comment, that link points to the following text: _The access to SNMP tables or variables cannot be instantaneous, and given the UDP nature of the protocol, the OSS cannot rely on a fast response time. In addition, SNMP is a non confirmed protocol and therefore, the OSS has to be tuned to retry after a GET operation times out._ That's a description of how _not_ to implement an SNMP agent. What the device vendor should do is to cache the values reported via SNMP such that the SNMP response time becomes predictable.

**Comment by dagbdagb** [comment]
Uh. 
I am polling x different devices from y different vendors in z different locations. Predictable response time?! 

If anything should be cached, it was the time spent successfully polling oid p at device q. That would provide a nice baseline for dynamic polling time, per device. Now, that sounds a bit excessive. But, maybe this could be done at the NMS level instead. Hmmm
