### ISSUE TITLE
MacOS Big Sur build failure in mibII icmp with 5.9

### ISSUE THREAD

**Issue by mitchblank** [net-snmp/net-snmp#226]
Trying to build 5.9 on a MacOS 11 machine (which the net-snmp build scripts identify as `darwin20` per the `x86_64-apple-darwin20.1.0` that config.guess returns) I get:
```
Undefined symbols for architecture x86_64:
  "_sysctl_read_icmp6_msg_stat", referenced from:
      import-atom in libnetsnmpmibs.dylib
  "_sysctl_read_icmp6_stat", referenced from:
      import-atom in libnetsnmpmibs.dylib
  "_sysctl_read_icmp_msg_stat", referenced from:
      import-atom in libnetsnmpmibs.dylib
  "_sysctl_read_icmp_stat", referenced from:
      import-atom in libnetsnmpmibs.dylib
ld: symbol(s) not found for architecture x86_64
```
The basic issue is that those functions are defined in agent/mibgroup/mibII/kernel_sysctl.c but the configure script does not bring that file into the build.

In agent/mibgroup/mibII/icmp.h there is:
```
#elif defined(freebsd4) || defined(openbsd4) || defined(dragonfly2) || \
    defined(darwin10)
config_require(mibII/kernel_sysctl)
```

If I change that "darwin10" to just be "darwin" everything builds fine.  However, I am not 100% sure that is the correct fix.

I noticed in the `master` branch this code looks a little different:
```
config_arch_require(darwin10,  mibII/kernel_sysctl)
config_arch_require(darwin11,  mibII/kernel_sysctl)
config_arch_require(darwin12,  mibII/kernel_sysctl)
config_arch_require(darwin13,  mibII/kernel_sysctl)
```
...so it seems to try to expand use of kernel_sysctl to more darwin versions, but still not the "darwin20" that I am actually building under.  I haven't tested if "master" works or not for me though.

So it seems like:
* the existing code seems to be trying to make the kernel_sysctl use dependent on the exact version of MacOS one is building under
* however neither `master` nor 5.9 seem to think darwin20 is in that set
* yet it does seem to be required to make the project build

For reference, the reason that the symbols *are* used is because...
```
#elif (defined(NETSNMP_CAN_USE_SYSCTL) && defined(ICMPCTL_STATS))
```
... is true.  `ICMPCTL_STATS` is defined in `<netinet/icmp_var.h>` (at least in MacOSX11.0.sdk).  `NETSNMP_CAN_USE_SYSCTL` comes from the configure scripts (configure.d/config_os_misc4 to be precise):
```
configure:31574: checking if sysctl can read kernel information
configure:31617: gcc -o conftest -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -g -O2 -Udarwin20 -Ddarwin20=darwin20 -I/usr/local/opt/openssl@1.1/include  -flat_namespace -framework CoreFoundation -framework CoreServices -framework DiskArbitration -framework IOKit -L/usr/local/opt/openssl@1.1/lib  conftest.c  >&5
configure:31617: $? = 0
configure:31617: ./conftest
configure:31617: $? = 0
configure:31627: result: yes
```

**Comment by ryandesign** [comment]
> If I change that "darwin10" to just be "darwin" everything builds fine. However, I am not 100% sure that is the correct fix.

Ping.

> I noticed in the `master` branch this code looks a little different:

The code in master is *older*, inexplicably. #310.
