### ISSUE TITLE
net-snmp-cert gencert creates an obsolete SHA1 certificate

### ISSUE THREAD

**Issue by minfrin** [net-snmp/net-snmp#231]
The script defaults to SHA1, which no longer works on many distros.

Problem is on this line, as well as references in docs.

https://github.com/net-snmp/net-snmp/blob/08d828a995aed6f562df2e3aeec9de1a5da83b0f/local/net-snmp-cert#L1006

**Comment by minfrin** [comment]
First encountered at Redhat, reported downstream: https://bugzilla.redhat.com/show_bug.cgi?id=1908331

**Comment by bvanassche** [comment]
Do you perhaps plan to submit a patch to fix this?

**Comment by jridky** [comment]
Perhaps #278 can solve this issue. Tested locally, generated cert used sha512 algorithm. @bvanassche
