### ISSUE TITLE
Traps/Notifications aren't sent when configured by snmpNotifyTable

### ISSUE THREAD

**Issue by javert** [net-snmp/net-snmp#247]
Version: 5.9 (and 5.8)
A change (post 5.7.3) to agent/agent_trap.c has now broken the call to the callbacks in netsnmp_send_traps when configured using the snmpNotifyTable (which requires use of these callbacks).
If snmpNotifyTable is used, then the _v2_sessions variable remains 0, and the if statement on line 1042 (or 1038 for v1) will not trigger the callback.
Solution seems to be removing the if statement check on _v2_sessions prior to the callback firing. It now looks like this variable serves no real purpose - a bit of incorrect optimisation - and could maybe be removed altogether.

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.9 and master branches. Please retest.

**Comment by javert** [comment]
Oh yes, thanks.
