### ISSUE TITLE
net-snmp-5.8: broken ErrorMsg at ucd-snmp

### ISSUE THREAD

**Issue by volkov-am** [net-snmp/net-snmp#26]
No error messages at UCD-SNMP-MIB::prErrMessage and UCD-SNMP-MIB::dskErrorMsg

### Steps to reproduce:

Create test-fail-snmpd.conf
<pre>
rocommunity test

disk /mnt/test1 50%
disk /mnt/test2 50%

proc snmpd
proc nonexistent
</pre>

Populate /mnt

<pre>
sudo mkdir /mnt/test{1,2}
sudo mount -t tmpfs tmpfs1 -o size=10m /mnt/test1
sudo mount -t tmpfs tmpfs2 -o size=10m /mnt/test2
sudo dd if=/dev/zero of=/mnt/test2/file bs=1M count=9
</pre>

Run snmpd

<pre>
sudo snmpd -C -c test-fail-snmpd.conf -f -Le udp:localhost:161
</pre>

Query disk and proc error mesages

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::prErrMessage
</pre>

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::dskErrorMsg
</pre>

There is no data from both snmpwalk queries

### Let's make a trick: reorder config lines

Create test-pass-snmpd.conf with reordered proc and disk lines
<pre>
rocommunity test

disk /mnt/test2 50%
disk /mnt/test1 50%

proc nonexistent
proc snmpd
</pre>

Rerun snmpd with new config

<pre>
sudo snmpd -C -c test-pass-snmpd.conf -f -Le udp:localhost:161
</pre>

Query disk and proc error mesages one more time

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::dskErrorMsg

UCD-SNMP-MIB::dskErrorMsg.1 = STRING: /mnt/test2: less than 50% free (= 10%)
</pre>

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::prErrMessage

UCD-SNMP-MIB::prErrMessage.1 = STRING: No nonexistent process running
</pre>

It looks better. But incomplete.

### The same tests with both config files for net-snmp-5.7.3 works as expected:

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::dskErrorMsg

UCD-SNMP-MIB::dskErrorMsg.1 = STRING: /mnt/test2: less than 50% free (= 10%)
UCD-SNMP-MIB::dskErrorMsg.2 = STRING: 
</pre>

<pre>
snmpwalk -c test -v1 localhost UCD-SNMP-MIB::prErrMessage

UCD-SNMP-MIB::prErrMessage.1 = STRING: No nonexistent process running
UCD-SNMP-MIB::prErrMessage.2 = STRING: 
</pre>

### Environment

The tests were produced on gentoo linux amd64 with current HEAD
net-snmp-v5.8-780-g06c09a117 (06c09a117857790e02e46465443d44123c8c909b)

### Details

The problem appears at 9b9c0e287b4dd4619da3e3ca80e1832dc1c81699
> MIBs: Use asprintf() instead of snprintf() to prevent truncation
> This patch addresses most gcc 7 warnings about output buffer truncation.

**Comment by bvanassche** [comment]
Thank you for having reported this. A candidate fix has been checked in. Please retest.

**Comment by volkov-am** [comment]
Tests passed
Thanks for getting this fixed so quickly
