### ISSUE TITLE
Compiling the Perl module on Windows fails with "/sbin: No such file or directory at ./Makefile.PL line 109"

### ISSUE THREAD

**Issue by mihaicodrean** [net-snmp/net-snmp#261]
I get the following error(s) when using nmake.exe from VS2019 to perform "nmake perl":
```
Use of uninitialized value $prefix in concatenation (.) or string at ./Makefile.PL line 109.
ERROR from evaluation of net-snmp-5-9-patches\perl\SNMP/Makefile.PL: /sbin: No such file or directory at ./Makefile.PL line 109
NMAKE : fatal error U1077: '...Perl\bin\perl.EXE' : return code '0x2'
```
Full paths sanitized.

The problematic code line from the GetTestInfo function is:
`my $snmpd_path1 = abs_path("${prefix}/sbin");`

**Comment by bvanassche** [comment]
Which procedure has been followed to build the Perl modules? Has build.bat been used or has another approach been used?

**Comment by mihaicodrean** [comment]
Initially tried with build.bat, but then switched to manual nmake(s) to avoid reconfiguration.

**Comment by bvanassche** [comment]
A candidate fix is available on the v5.9 and master branches. Please retest.

**Comment by mihaicodrean** [comment]
Thanks. Tested, but even though the path prefix is now there, it still complains that there's no "sbin" subfolder:
`ERROR from evaluation of F:\net-snmp\perl\SNMP/Makefile.PL: f:/Program Files (x86)/Net-SNMP/sbin: No such file or directory at ./Makefile.PL line 113`
Could it be that the remaining problem is the fact that "nmake install" does not seem to create the "sbin" subfolder?

**Comment by bvanassche** [comment]
Does commit 385d555606ee31a23d5ed711a7ffba45f4197d50 help?

**Comment by mihaicodrean** [comment]
Yes, that did the trick (since it no longer looks for "sbin"), thanks!
