### ISSUE TITLE
TLS 1.2 is not working in net-snmp 5.7.3

### ISSUE THREAD

**Issue by Nagarajan-GK** [net-snmp/net-snmp#263]
I'm want to disable TLS 1.0 and 1.1 versions communication in net-snmp. TLS 1.2 and higher only to be allowed for communication. My system is using OpenSSL 1.0.2j.
I tried to modify net-snmp the source to support it. But, failed. 

How to do it?
Should I upgrade to latest version?

(I'm trying the same thing in net-snmp 5.9 too and not working)

**Comment by hardaker** [comment]
I believe this is fixed with the previously mentioned patch.  Please re-open if this is incorrect.
