### ISSUE TITLE
Python - Setting empty string for OCTETSTR generates error print statement

### ISSUE THREAD

**Issue by thomric2** [net-snmp/net-snmp#265]
Passing in an empty string when performing a set results in this string getting printed out: "error: set: adding variable/value to PDUSNMP"

The value does properly get set, so this is a very minor bug. 

In poking at the code it looks like this was fixed in PERL as part of #65 in commit dac831d3220e2ff9013955a314aada6c1c88fef5. And then it looks like the commit before and after this change also were made against the PERL code but not the PYTHON code.

**Comment by bvanassche** [comment]
A candidate fix is available on the v5.9 and master branches. Thanks for having reported this.
