### ISSUE TITLE
Replacing Windows SNMP service

### ISSUE THREAD

**Issue by Gibson85** [net-snmp/net-snmp#27]
Hi,

one question. Having a MIB DLL registering with the Windows SNMP service (using "SnmpExtension... functions") I tried to replace the windows snmp service with the net-snmp one.
For that I compiled net-snmp per build.bat with 

USING_WINEXTDLL_MODULE

enabled and added the code below to my own windows service.
But if I do a MIB walk with an MIB browser I see the "get-next-request" with wireshark,
but no reponse.

My code looks like the following.
Any ideas what could go wrong here?

```
Snmp::Snmp() :
	m_pRawSession(nullptr),
	m_pSession(new netsnmp_session())
{
	const char* pCommunity = "public";
	const char* pName = "SnmpAgent";
	char* pPeerName = "127.0.0.1";
	init_agent(pName);
	init_snmp(pName);
	snmp_sess_init(m_pSession);
	m_pSession->peername = _strdup(pPeerName);
	m_pSession->remote_port = 161;
	m_pSession->version = SNMP_VERSION_2c;
	m_pSession->community = (u_char*)pCommunity;
	m_pSession->community_len = strlen((char*)m_pSession->community);
	init_master_agent();
}

bool Snmp::Start()
{
	if (m_pRawSession == nullptr)
	{
		SOCK_STARTUP;
		m_pRawSession = snmp_open(m_pSession);
		if (m_pRawSession == nullptr)
		{
			snmp_sess_perror("Snmp::Start", m_pRawSession);
			SOCK_CLEANUP;
			return false;
		}
	}
	return true;
}
```

**Comment by Gibson85** [comment]
I now manually registered the snmpd.exe as a master service

```snmpd.exe -register```

and started the service. But if I do a

```snmpwalk -v2c -c public localhost```

I am getting a

```Timeout: No Response from localhost```

Why is that?
Maybe my expectation that I could replace the windows service by the net-snmp one easily is to naive?

**Comment by Gibson85** [comment]
Ok, now I registerd the service again

```
snmpd -register -Lf c:/usr/log/snmpd.log
```

writing a log file wich says:
```
D:\...\net-snmp\bin>snmpd.exe -H
duplicate registration: MIB modules mibII/snmp and C:\Windows\System32\snmpmib.dll (oid .1.3.6.1.2.1.11).
handler registration failed.
Created directory: c:/usr/snmp/persist/mib_indexes
Warning: no access control information configured.
  (Config search path: c:/usr/etc/snmp;c:/usr/share/snmp;c:/usr/lib)
  It's unlikely this agent can serve any useful purpose in this state.
  Run "snmpconf -g basic_setup" to help you configure the snmpd.conf file for this agent.
```

And when running the snmpconf tool as suggested:

```
D:\...\net-snmp\bin>snmpconf -g basic_setup

Warning: Perl module Win32::Registry is not installed.  This module is
         required to read the SNMPSHAREPATH and SNMPCONFPATH values from
         the registry.  To use snmpconf without the module you need to
         define SNMPSHAREPATH and SNMPCONFPATH as environment variables
         or use the -c and -I command line options.
Can't locate Win32/Registry.pm in @INC (you may need to install the Win32::Registry module) (@INC contains: C:/Perl64/site/lib C:/Perl64/lib) at c:\usr\bin\snmpconf line 873.
```
So I manually added the pats but without success also.
Even replacing the obsolete "Win32::Registry" calls to "Win32::TieRegistry" did not work.

**Comment by Gibson85** [comment]
It becomes better and better. I tried to install the Win32::Registry module with ppm. But my ActivePerl installation seems not to have a process "ppm" anymore. At least on command line it is not found. Ok so lets try cpan:

```
perl -MCPAN -e shell
cpan> install Win32::Registry

Running make for J/JD/JDB/Win32-Registry-0.12.tar.gz
Use of uninitialized value in pattern match (m//) at C:\Perl64\lib/CPAN/Distribution.pm line 2946.
Der Befehl "dmake" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
  JDB/Win32-Registry-0.12.tar.gz
  dmake -- NOT OK
Failed during this command:
 JDB/Win32-Registry-0.12.tar.gz               : make NO
```
Installing dmake fails also. I am getting crazy...

**Comment by Gibson85** [comment]
Tried to build net-snmpt again with options 7 and 8 (Perl modules / Install perl modules) enabled. But this also fails:

```The perl interpreter has been built with gcc instead of MSVC. Giving up.```

**Comment by Gibson85** [comment]
I am close to it. I did a rebuild with PlatformSDK enabled. Now it loaded my MyMIB.dll as registered in the registry. But still the SNMP Walk fails:

```
Timeout: No Response from localhost
```

But why?

**Comment by Gibson85** [comment]
My fault. It's working now.

**Comment by manister7** [comment]
> My fault. It's working now.

**Comment by manister7** [comment]
> My fault. It's working now.

How did you solve it, i am stuck on the same.. Pls help

**Comment by dagbdagb** [comment]
Obligatory XKCD:  https://xkcd.com/979/

**Comment by bvanassche** [comment]
> > Tried to build net-snmpt again with options 7 and 8 (Perl modules / Install perl modules) enabled. But this also fails:
> > `The perl interpreter has been built with gcc instead of MSVC. Giving up.`
> 
> How did you solve it, i am stuck on the same.. Pls help

A possible solution is to build the Perl source code with MSVC, e.g. by running `vcvars64.bat` followed by downloading and running this batch file: https://github.com/net-snmp/net-snmp/blob/master/ci/perl.bat
