### ISSUE TITLE
cisco aes-256 snmp v3 issue (perl)

### ISSUE THREAD

**Issue by rogerGunis** [net-snmp/net-snmp#270]
Hi,

My question is related to https://github.com/net-snmp/net-snmp/issues/267.
I'm trying to poll via >perl< the router and I have no success. The debug message seems to be as the one above.
snmpwalk on cli is working but the perl part seems to be not working.
Are there any hidden switches as well thus the cisco devices will respond correct. Is there any developer available to talk to, who can help me pointing the problem.

Thank you very much
Kind Regards
Roger

The snippet from the testCode ist as following

$sess = new SNMP::Session(
               RemotePort       => 161,
               DestHost         => "10.0.121.4",
               UseNumeric       => 1,
               UseSprintValue   => 1,
               UseLongNames     => 1,
               Timeout          => 300000,
               Retries          => 2,
               ErrorStr         => $error_var,
               RetryNoSuch      => $retry_nosuch,
            Version     => 3,
            SecName     => "sktest",
            SecLevel    => 3,
            AuthProto   => "MD5",
            AuthPass    => "authpass",
            PrivProto   => "AES256C",
            PrivPass    => "privpass"
);
unfortunately I cannot get the response. The Cisco devices debug message is as following:

*Feb 16 06:31:43.017: SNMP: Packet received via UDP from 10.0.6.65 on GigabitEthernet1no such type in ParseType (106) (0x6A)
ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
SrParseV3SnmpMessage: ParseSequence:
SrParseV3SnmpMessage: Failed.
SrDoSnmp: ASN Parse Error

*Feb 16 06:31:45.018: SNMP: Packet received via UDP from 10.0.6.65 on GigabitEthernet1no such type in ParseType (14) (0xE)
ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
SrParseV3SnmpMessage: ParseSequence:
SrParseV3SnmpMessage: Failed.
SrDoSnmp: ASN Parse Error

*Feb 16 06:31:47.021: SNMP: Packet received via UDP from 10.0.6.65 on GigabitEthernet1no such type in ParseType (20) (0x14)
ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
SrParseV3SnmpMessage: ParseSequence:
SrParseV3SnmpMessage: Failed.
SrDoSnmp: ASN Parse Error

*Feb 16 06:31:49.023: SNMP: Packet received via UDP from 10.0.6.65 on GigabitEthernet1no such type in ParseType (80) (0x50)
ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
SrParseV3SnmpMessage: ParseSequence:
SrParseV3SnmpMessage: Failed.
SrDoSnmp: ASN Parse Error

*Feb 16 06:31:51.023: SNMP: Packet received via UDP from 10.0.6.65 on GigabitEthernet1no such type in ParseType (103) (0x67)
ParseSequence, Unexpected type: FFFFFFFFFFFFFFFF
SrParseV3SnmpMessage: ParseSequence:
SrParseV3SnmpMessage: Failed.
SrDoSnmp: ASN Parse Error

**Comment by fenner** [comment]
Hi Roger,

Sadly the perl module was not updated when adding AES192/AES256, and a shortcut that was taken to accept either AES or AES128 (which was to accept any string starting with "AES") means that while your AES256C isn't a syntax error, neither is AESGOBBELDEYGOOK and they all mean AES128.

This should be a reasonably straightforward fix in SNMP.xs's `snmp_new_v3_session()` (and it should probably be fixed to support the newer SHA hashes also at the same time) - but I don't personally have the cycles to tackle this right now.

**Comment by rogerGunis** [comment]
Hi fenner,

thank you very much for clarification and the work so far on this project.

Kind Regards
Roger

**Comment by fenner** [comment]
Hi Roger, I think we should re-open this because it is a real bug in the code, and if someone comes by looking for something to work on, we know there's at least one person in the world who could use this being fixed ;-)

**Comment by fenner** [comment]
Hi Roger, it looks like @bvanassche has fixed this already in ac06c5844105473e211decdf825af75dc7cd8b7c - do you have the ability to try building the V5-9-patches branch and see if you can use the stronger hash/encryption algorithms?

**Comment by rogerGunis** [comment]
Hi @fenner, @bvanassche,

thank you very much for pointing to this commit.
It works like a charm. I'm very happy with it :-)

Thank you once again for your work!
Regards
Roger
