### ISSUE TITLE
Raspbian Pi OS (Debian 10 Buster), Pi does NOT have PCI bus, SNMPD still reports attempt to query PCI bus

### ISSUE THREAD

**Issue by Nodi-Rubrum** [net-snmp/net-snmp#271]
Raspbian Pi OS (Debian 10 Buster), Pi does NOT have PCI bus, SNMPD still reports attempt to query PCI bus.  Please fix this.  A few web sites state this bug was fixed in 5.7.3.  It is NOT fixed.

: Starting Simple Network Management Protocol (SNMP) Daemon....
: Started Simple Network Management Protocol (SNMP) Daemon..
: pcilib: Cannot open /proc/bus/pci
: pcilib: Cannot find any working access method.
: pcilib: pci_init failed
: Turning on AgentX master support.
: NET-SNMP version 5.7.3

**Comment by bvanassche** [comment]
Net-SNMP version v5.7.3 is no longer maintained. The actively maintained branches are the v5.9 and master branches. Please retest with one of these two branches.

**Comment by Nodi-Rubrum** [comment]
Yup, I have tested 5.9, it addresses the issue.  However, 5.9 is not packaged for Raspberry Pi OS (ARMHF) Buster 10.  So anyone that wants to avoid the errors of Net-SNMP trying to query the PCIe bus... which does not exist on Pi devices, will have to download and compile 5.9 from source.  Thanks for being responsive to issues posted.

**Comment by abutcher-gh** [comment]
I'm not sure how the referenced patch solved this, [it seems to do the opposite](https://github.com/net-snmp/net-snmp/commit/8c301c1e06004aa4095f956bff5f399104e71127#commitcomment-131661740).  I.e. not init PCI on systems with PCI, and still fail to init PCI on systems without it.

**Comment by bvanassche** [comment]
Commit ea6c54f508ca8897961f4faa8d7b04793151db78 should fix the PCI test.
