### ISSUE TITLE
init_snp("snmpclient") is getting crashed

### ISSUE THREAD

**Issue by agollaravi** [net-snmp/net-snmp#272]
Hi,
Would you please help here. I am having issue at init_snmp()  function call crash the application. When I was debugging it is throwing  "Unhandled exception at 0x00000000 in NDServer.exe: 0xC0000005: Access violation." at init_snmp() function call.
We are using net-snmp-5.5.2 library and openssl 1.0.2g. Any suggestions would be appreciated

Thanks,
Ravichand

**Comment by hardaker** [comment]
I wonder if that machine's access restrictions aren't allowing either network access or file access (ie, reading configuration files).

As that doesn't make much sense why that function would crash.

**Comment by agollaravi** [comment]
init_snmp() call was not crashing we we have openssl 0.9.8za with net-snmp-5.5. It was working before. This issue was observed when we upgraded openssl from 0.9.8za to 1.0.2g. With the crash dump we are not able identify any root cause for the issue. Any suggestions for identifying the cause.

**Comment by agollaravi** [comment]
I have resolved the issue.

**Comment by ftrebosc** [comment]
Hi
It would be interesting to know which was the cause of the issue. I'm facing the sam kind of issue using net-snmp 5.7.3 and OpenSSL 1_0_2h. The call init_snmp causes the crash of our application only on certains version of windows

**Comment by agollaravi** [comment]
Hi,

In our case we have upgraded openssl from 0.9.8za to 1.0.2g. But net-snmp libraries did not build with openssl 1.0.2g. That was the reason init_snmp() function call was crashing the application.

**Comment by ftrebosc** [comment]
Hi,

Thank you for your precisions. I think I had the same kind of issues, because I fixed it by rebuilding OpenSSL and Net-SNMP to the last release. So I suspect dependencies issues on OS causing our crash.
