### ISSUE TITLE
Windows -> NMAKE : fatal error U1077

### ISSUE THREAD

**Issue by Gremlingroj** [net-snmp/net-snmp#277]
vsdevcmd.bat -arch=amd64

c:\net-snmp-5.9\win32>build.bat

Net-SNMP build and install options
==================================

1.  OpenSSL support:                disabled
2.  OpenSSL include directory:      C:\OpenSSL-Win32\include
3.  OpenSSL library director:       C:\OpenSSL-Win32\lib\VC
4.  Platform SDK support:           disabled

5.  Install path:                   c:/usr
6.  Install after build:            disabled

7.  Perl modules:                   disabled
8.  Install perl modules:           disabled

9.  Quiet build (logged):           enabled
10. Debug mode:                     disabled

11. IPv6 transports (requires SDK): disabled
12. winExtDLL agent (requires SDK): disabled

13. Link type:                      static

14. Install development files       disabled

F.  Finished - start build
Q.  Quit - abort build

Select option to set / toggle: F

Building...

Creating *.out log files.

Deleting old log files...
Running Configure...
Cleaning...
Building main package...
Build error (see make.out) at build.pl line 202, <> line 1.

**Comment by Gremlingroj** [comment]
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\cl.exe" : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\bin\HostX64\x64\nmake.EXE" : возвращенный код "0x2"
Stop.

**Comment by Gremlingroj** [comment]
[make.out.log](https://github.com/net-snmp/net-snmp/files/6130273/make.out.log)

**Comment by Gremlingroj** [comment]
If using net-snmp-5.8

Building...

Creating *.out log files.

Deleting old log files...
Running Configure...
Cleaning...
Building main package...

Installing main package...
Type nmake install_devel to install the development files to c:/usr

Done!
c:\net-snmp-5.8\win32>

**Comment by bvanassche** [comment]
This has been fixed a while ago. Please try the latest version of the v5.9 or master branch. See also https://github.com/net-snmp/net-snmp/tree/V5-9-patches .

**Comment by Gremlingroj** [comment]
Thx

Building...

Creating *.out log files.

Deleting old log files...
Running Configure...
Cleaning...
Building main package...

Installing main package...
Type nmake install_devel to install the development files to c:/usr

**Done!**
c:\net-snmp-5.9-patches\win32>
