### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [net-snmp/net-snmp#279]
Please release at least 5.9.1 out of commits which are already accumulated in V5.9.-patches branch.

**Comment by hardaker** [comment]
There is a previous bug (that I couldn't find) asking the same question.  I'm shooting for April or so.  Our release process is a long one, to ensure proper testing and community support.

**Comment by kloczek** [comment]
Yas I've been asking for the same after long time not release release anything after 5.8.
Now situation with 5.9 repeats.
5.8.1 after rc1 and rc2 even not been released ..
People starts testing not before but **after** making new release.
Last release was almost 1.5y ago.
I can understand that you want to want longer on next major release bat not releasing updated major release out of commits collected on the branch is really strange. Something like 5.9.x with only bugfixes should be released on regular base. in V5.9.-patches branch is already accumulated almost 120 commits.

**Comment by hardaker** [comment]
5.8.1 was a problem.  Commits were made to the tree (no names named) that violated the policy with respect to API changes so we had to release 5.9 instead.  I'll start 5.9.1 in April, as I previously said, which will be about 7 months after.  Thanks for your opinions, we do appreciate it.  We could change our release strategy to be less tested I suppose too.  We've not adopted the release-early release-often, because we consider the SNMP toolkit to be critical in importance for stability.  It often gets into hardware and products that are hard to update, so we've opted for ensuring stability with a release and testing cycle that takes 1-2 months.

**Comment by kloczek** [comment]
More patches to push in next release than always higher probablity you will have that some "problems" you will have.

You nmention something about testing what needs to be released and in meantime I've tested next version of my rpm package with more patches than last time from 5.9 branch.
Suddenly I found that with those new patches libnetsnmpagent after "make install" is with zero bytes lenghth.
Hrere is list of patches which I've added in new version of my spec file:
```
@@ -154,6 +153,23 @@
 Patch130:      %{VCS}/commit/e3601420.patch#/%{name}-Revert-Read-intermediate-certificates-from-PEM-files.patch
 Patch131:      %{VCS}/commit/4d92f401.patch#/%{name}-Fix-compilation-when-feature-NETSNMP_FEATURE_REMOVE_.patch
 Patch132:      %{VCS}/commit/02bc1baf.patch#/%{name}-snmpd-Exclude-the-dev-kmem-code-if-configured-with-w2.patch
+Patch133:      %{VCS}/commit/d468c8ad.patch#/%{name}-HOST-RESOURCES-MIB-Simplify-the-code-for-recognizing.patch
+Patch134:      %{VCS}/commit/8d8d8439.patch#/%{name}-HOST-RESOURCES-MIB-Add-JFFS2-support.patch
+Patch135:      %{VCS}/commit/0dcebaf3.patch#/%{name}-python-netsnmp-tests-test.py-Also-perform-a-full-MIB.patch
+Patch136:      %{VCS}/commit/a29685e5.patch#/%{name}-configure-Only-display-the-message-Checking-for-deve.patch
+Patch137:      %{VCS}/commit/b71b52f0.patch#/%{name}-Fix-the-Wtype-limits-compiler-warnings.patch
+Patch138:      %{VCS}/commit/b754da08.patch#/%{name}-Enable-the-compiler-flag-Wtype-limits.patch
+Patch139:      %{VCS}/commit/f0358245.patch#/%{name}-snmplib-Add-more-comments-in-netsnmp_random.patch
+Patch140:      %{VCS}/commit/ddd338fa.patch#/%{name}-python-netsnmp-tests-test.py-Add-a-test-for-setting-.patch
+Patch141:      %{VCS}/commit/6ad61e66.patch#/%{name}-Python-Do-not-report-error-set-adding-variable-value.patch
+Patch142:      %{VCS}/commit/428a486d.patch#/%{name}-Python-Use-netsnmp_memdup-instead-of-open-coding-it.patch
+Patch143:      %{VCS}/commit/f64e0111.patch#/%{name}-Perl-Set-the-prefix-variable-on-Windows.patch
+Patch144:      %{VCS}/commit/385d5556.patch#/%{name}-Perl-Only-use-prefix-on-Unix-systems.patch
+Patch145:      %{VCS}/commit/8c301c1e.patch#/%{name}-IF-MIB-Do-not-scan-for-PCI-devices-if-no-PCI-bus-is-.patch
+Patch146:      %{VCS}/commit/dc58ed99.patch#/%{name}-net-snmp-create-v3-user-Print-the-version-number-onc.patch
+Patch147:      %{VCS}/commit/dce7b17e.patch#/%{name}-ci-build.bat-Fix-the-Cygwin-build.patch
+Patch148:      %{VCS}/commit/eb1b11bb.patch#/%{name}-Prevent-parsing-IP-address-twice-199.patch
+Patch149:      %{VCS}/commit/a9cf25db.patch#/%{name}-net-snmp-cert-Use-sha512-as-default-option-for-gener.patch
 BuildRequires: automake
 BuildRequires: bzip2-devel
 BuildRequires: elfutils-devel
```
So that bub must be in some of those patches.
Package without those patches is OK and with is trashed. Clear 0/1 situation.

Releasesing less frequently is kind of mith that iot prevents releasing sometbing bad.
Only prevention is more eye bals loooking on recent changes. Releasing less frequrntly with more changes decreases probablity of catching something wrong.

Other thing which makes more difficult to maintain is that if someone hase some patch will b forced to rediff its own patches.
Look on ANY  linux distribution and try to count how many patches all those distributions are adding on top of dist net-snmp.

Again: pelase consider start making more frequent et least releases of the last stable branch.. That kind of releases shpould be on regular base.

**Comment by kloczek** [comment]
More interesting is that none of the test units otf the `testall` target catched that something is wrong with libnetsnmpagent. Probably there is no oeven on uniot which could test is that binary OK.

**Comment by kloczek** [comment]
Looks like again it gap between releases is growing 😞 
In git repo it is +230 commitch since last prod release ..
