### ISSUE TITLE
FreeBSD 13 + net-snmp = dskTable freezes

### ISSUE THREAD

**Issue by zlobar** [net-snmp/net-snmp#282]
Recently updated a couple of FreeBSD hosts to fresh **13.0-RELEASE**.
All hosts have NET-SNMP reinstalled from pkg after OS upgrade, version **5.9_3,1**.

But values of UCD-SNMP-MIB::**dskUsed** and UCD-SNMP-MIB::**dskAvail** are completely freezed.
Even snmpd daemon restart, or remove+install makes no changes to data given via SNMP.

Only host reboot helps.

**Comment by bvanassche** [comment]
From the FreeBSD statvfs man page: `The statvfs() and fstatvfs() functions fill the structure pointed to by buf with garbage.  This garbage will occasionally bear resemblance to file system statistics, but portable applications must not depend on this.` Does this perhaps mean that statfs() and fstatfs() should be used on FreeBSD?

**Comment by zlobar** [comment]
> A candidate fix has been checked in, namely commit [93ea661](https://github.com/net-snmp/net-snmp/commit/93ea661906fb25657a63cfd757ef7a04c4dd0b33). Please retest.

Seems it works :)

**Comment by bvanassche** [comment]
Thanks for the testing and for the feedback :-)
