### ISSUE TITLE
Snmpd infinite loop in IF-MIB (5.7.3, 5.9)

### ISSUE THREAD

**Issue by Forest-fox** [net-snmp/net-snmp#286]
Have checked on 5.7.3 version from package manager and manually installed from sources 5.9 on Debian 10.
Daemon worked until get snmpwalk request with .1.3.6.1.2.1.2.2 OID (IF-MIB), after what its get Rs state and take much CPU (30-50%), but no response from agent.

Log with key -D  -d shows that:

 trace: netsnmp_access_interface_ioctl_ifindex_get(): if-mib/data_access/interface_ioctl.c, 411:
access:interface:ioctl: ifindex_get
trace: _ioctl_get(): if-mib/data_access/interface_ioctl.c, 52:
verbose:access:interface:ioctl: ioctl 35123 for vlan222
trace: _load_ipv4(): ip-forward-mib/data_access/route_linux.c, 95:
9:access:route:container: line |vlan222	00208E24	F5F3325C	0003	0	0	20	00E0FFFF	0	0	0                                                                           
|
trace: netsnmp_access_interface_ioctl_ifindex_get(): if-mib/data_access/interface_ioctl.c, 411:
access:interface:ioctl: ifindex_get
trace: _ioctl_get(): if-mib/data_access/interface_ioctl.c, 52:
verbose:access:interface:ioctl: ioctl 35123 for vlan222
trace: _load_ipv4(): ip-forward-mib/data_access/route_linux.c, 95:
9:access:route:container: line |vlan222	00408E24	F5F3325C	0003	0	0	20	00C0FFFF	0	0	0                                                                           
|
trace: netsnmp_access_interface_ioctl_ifindex_get(): if-mib/data_access/interface_ioctl.c, 411:
access:interface:ioctl: ifindex_get
trace: _ioctl_get(): if-mib/data_access/interface_ioctl.c, 52:
verbose:access:interface:ioctl: ioctl 35123 for vlan222
trace: _load_ipv4(): ip-forward-mib/data_access/route_linux.c, 95:
9:access:route:container: line |vlan222	00808E24	F5F3325C	0003	0	0	20	0080FFFF	0	0	0       

Or same text with other network interface (vlan232). 
Some kind of loop without exit.
But ubuntu 18 with only physical interfaces have none errors of this one.

**Comment by boggarapupriyanka** [comment]
This is seen on 5.8.1 
I am facing the same issue when more than 150+ VLANs are configured. I am also able to see the above repeated log messages when we start the service snmpd in debug mode. Due to this, snmp requests are timing out at SNMP manager.
Below is the backtrace when more VLANs are configured, 


```
#0 0xf7a2bc24 in ioctl () from target:/lib/libc.so.6
#1 netsnmp_get_link_settings (nlls=0xffdb6374, fd=17, name=0x923a4c0 "Port3.205") at util_funcs.c:1176
#2 0xf7e1be22 in netsnmp_linux_interface_get_if_speed (fd=17, name=0x923a4c0 "Port3.205", defaultspeed=0)at if-mib/data_access/interface_linux.c:968
#3 0xf7e1c797 in netsnmp_arch_interface_container_load (container=0x91dd3d0, load_flags=0) at if-mib/data_access/interface_linux.c:861
#4 0xf7e0ca57 in netsnmp_access_interface_container_load (container=0x91dd3d0, load_flags=0) at if-mib/data_access/interface.c:180
#5 0xf7e12884 in ifTable_container_load (container=0x91a7c80)at if-mib/ifTable/ifTable_data_access.c:625
#6 0xf7e0e604 in _cache_load (cache=0x91908b0, vmagic=0x91a7c80)at if-mib/ifTable/ifTable_interface.c:1875
#7 0xf7f4c607 in _cache_load (cache=0x91908b0) at helpers/cache_handler.c:735
#8 0xf7d5d237 in run_alarms () at snmp_alarm.c:218
#9 0x0804b7c8 in receive () at snmpd.c:1349
#10 0x0804ae37 in main (argc=<optimized out>, argv=<optimized out>)at snmpd.c:1092
```

Your help is much appreaciated.

**Comment by bvanassche** [comment]
Net-SNMP versions v5.7.x and v5.8.x are no longer supported. Please reopen this report if this is reproducible with Net-SNMP v5.9.1.
