### ISSUE TITLE
Net-snmp doesn't have transport layer for FQDN as trap receiver address

### ISSUE THREAD

**Issue by prasadreddyvalmeti2** [net-snmp/net-snmp#287]
Hello,

We have integrated net-snmp into our application that runs on an embedded system and
using net-snmp to send traps to user configured trap receivers.

It works fine with the configured IP address as trap receivers.
Now, we have enhanced our system so that user can configure FQDN as well for trap receivers.

We would like to feed user configured FQDN into net-snmp so that net-snmp can resolve the FQDN into an IP and determine the transport domain (UDP or UDP6) before sending the traps.

  1.  Is this possible in any of the net-snmp release versions?
  2.  If not, what workaround do you recommend?

[ We currently, resolve FQDN into IP addresses and create trap session for each such resolved address. This works alright but has its own limitations. For example, DNS Server should be reachable when trap sessions are being created. Also if user decides to host trap receiver on a different server (same FQDN but different IP), then he will have to reconfigure the trap receiver on our device ]

We use the following APIs to setup net-snmp for SNMP v1/v2c/v3 traps:

  1.  create_trap_session
  2.  snmpTargetAddrTable_create, snmpTargetAddrTable_add, snmpNotifyTable_create, snmpNotifyTable_add, snmpTargetParamTable_create, snmpTargetParamTable_add
  3. Using net-snmp 5.8.x version

As per the MIBs, it shows that it supports tdomain as transportAddressDns. But actually in the transports that comes with the net-snmp doesn't have any implementation for it.
  
Please let us know, if the fqdn/dns transport is supported in net-snmp.
Regards,
Prasad

**Comment by bvanassche** [comment]
I think this is supported by the `trapsess` keyword, documented in https://github.com/hardaker/net-snmp/blob/master/man/snmpd.conf.5.def.
