### ISSUE TITLE
snmp agent process crashes during snmp agent restart and parallel fetching values(snmpbulkwalk) 

### ISSUE THREAD

**Issue by adityaprakash90** [net-snmp/net-snmp#288]
Hi There is a crash seen on SNMP agent when the SNMP agent is restarted and at the same time there is a try to fetch the SNMP values(snmpbulkwalk) from not fully up system( probably not fully up SNMP agent).

The version: 5.7.3 and
Operating system is Linux

**Steps to Reproduce:**
1) have a script which continuously restart the SNMP agent at an interval of 120 seconds
2) and at the same time in a loop fetch the SNMP value(snmpbulkwalk)
3) And the traffic is also running but looks like it may be seen even without traffic just restart the SNMP agent and fetch the values

There is a core file generated which shows that crash is in snmp_call_callbacks() under callback.c

```
0  snmp_call_callbacks (major=major@entry=0, minor=minor@entry=2, caller_arg=caller_arg@entry=0x0) at callback.c:354
354	callback.c: No such file or directory.
(gdb) bt
#0  snmp_call_callbacks (major=major@entry=0, minor=minor@entry=2, caller_arg=caller_arg@entry=0x0) at callback.c:354
#1  0x00007faea190cac7 in snmp_shutdown (type=<optimized out>) at snmp_api.c:908
#2  0x000055a9aeab3505 in pl_cleanup () at snmpd-pl-agent.c:94
#3  main (argc=<optimized out>, argv=<optimized out>) at snmpd-pl-agent.c:69
(gdb) where
#0  snmp_call_callbacks (major=major@entry=0, minor=minor@entry=2, caller_arg=caller_arg@entry=0x0) at callback.c:354
#1  0x00007faea190cac7 in snmp_shutdown (type=<optimized out>) at snmp_api.c:908
#2  0x000055a9aeab3505 in pl_cleanup () at snmpd-pl-agent.c:94
#3  main (argc=<optimized out>, argv=<optimized out>) at snmpd-pl-agent.c:69
(gdb) list
349	in callback.c
(gdb) 
```

Thanks an Regards
Aditya Prakash

**Comment by adityaprakash90** [comment]
Hi is there any eye on this issue?

**Comment by bvanassche** [comment]
Net-SNMP v5.7.3 is no longer supported. Please retest with version v5.9.1 and reopen this issue if this is reproducible with v5.9.1.
