### ISSUE TITLE
libnetsnmptrapd doesn't use standard LDFLAGS

### ISSUE THREAD

**Issue by csmall** [net-snmp/net-snmp#29]
I was trying to track down why the Debian CI was complaining about one net-snmp library not using 
the hardening flags (e.g. [Job 363292](https://salsa.debian.org/debian/net-snmp/-/jobs/363292) )

This library is built under apps, not snmplib like the others.  The snmlib linker lines in Makefile.in use $(LDFLAGS) while apps uses $(LIB_LD_LIBS).  The problem is, LIB_LD_LIBS is not defined anywhere so and specified LDFLAGS are not used.

I cannot see why libnetsnmptrapd would need different linker flags to the other libraries, so the simplest fix is to change the relevant apps/Makefile.in to use LDFLAGS instead of (or maybe in addition to) LIB_LD_LIBS.

The other blhc error is around sedscript. I was just going to add CPPGLAGS to the toplevel Makefile to keep blhc happy. It's probably not going to do anything other than that.

**Comment by bvanassche** [comment]
Did you perhaps plan to submit a patch?

**Comment by csmall** [comment]
[fix_sedscript_libnetsnmptrapd_flags.diff.txt](https://github.com/net-snmp/net-snmp/files/3733900/fix_sedscript_libnetsnmptrapd_flags.diff.txt)

**Comment by bvanassche** [comment]
Thanks for the patch! One of the two changes from your patch has been checked in. Please retest.
