### ISSUE TITLE
So Strong function net-snmp is! but why the stars are so less

### ISSUE THREAD

**Issue by xx-zhang** [net-snmp/net-snmp#3]
Is there some other snmp suported project that do the service for net manager. I have used snmp for a pirod time and i find it great for me. but the project in github is so cold. i want to know what the reason is.

**Comment by bvanassche** [comment]
I do not understand your comment. This year already more than 300 commits have been checked in:

```
$ git log origin/master --since=2019-01-01 | grep -c ^commit
339
```

**Comment by hardaker** [comment]
The vast discussion occurs in the mailing lists (www.net-snmp.org/lists) not in github dialogs at this point.
