### ISSUE TITLE
regression v.5.9.1: Python snmpwalk with UseNumeric=1 sets tag and iid to null

### ISSUE THREAD

**Issue by alex2grad** [net-snmp/net-snmp#303]
The code
_______
import netsnmp

serv = "192.168.1.1."
snmp_pass = "public"

oid = netsnmp.VarList('IF-MIB::ifName','IF-MIB::ifDescr')
snmp_res = netsnmp.snmpwalk(oid, Version=2, DestHost=serv, Community=snmp_pass, UseLongNames=1)
for x in oid:
    print ("snmp_res:: ", x.tag, x.iid, " = ", x.val)
_______

Version 5.9
_______
snmp_res::  .1.3.6.1.2.1.31.1.1.1.1 1  =  Et0
snmp_res::  .1.3.6.1.2.1.2.2.1.2 1  =  Ethernet0
snmp_res::  .1.3.6.1.2.1.31.1.1.1.1 2  =  Fa0
snmp_res::  .1.3.6.1.2.1.2.2.1.2 2  =  FastEthernet0
_______

Version 5.9.1
_______
snmp_res::  None None  =  Et0
snmp_res::  None None  =  Ethernet0
snmp_res::  None None  =  Fa0
snmp_res::  None None  =  FastEthernet0
_______

**Comment by alex2grad** [comment]
This commit https://github.com/net-snmp/net-snmp/commit/c744be5ffed64f992a843e858a3cd2c1fe80f12f
The function build_python_varbind resets getlabel_flag  to NO_FLAGS.
Need to pass getlabel_flag to function build_python_varbind

**Comment by alex2grad** [comment]
Attached the patch which fixes this issue
[net-snmp-5.9.1-getlabel_flag.patch.txt](https://github.com/net-snmp/net-snmp/files/6626918/net-snmp-5.9.1-getlabel_flag.patch.txt)

**Comment by bvanassche** [comment]
The attached patch has been applied on the v5.9 and master branches. Please retest.
