### ISSUE TITLE
Getting compilation error during compilation of net-snmp 5.9.1 version on Solaris platform.

### ISSUE THREAD

**Issue by nilamk746** [net-snmp/net-snmp#307]
Hi,

We were using  net-snmp 5.7.3 version previously.
Currently we are trying to upgrade version of net-snmp library to net-snmp 5.9.1.
Compilation of net-snmp 5.9.1 is successful on windows 32 bit, windows 64 bit and zlinux platforms.
But its failing on solaris sparc 10 platform with below error:

```
/bin/bash ../libtool  --mode=compile /tivoli/tools/solaris2/studio12/SUNWspro/prod/bin/cc -I../include -I. 	-I../snmplib -instances=static -xmemalign=4i -w -KPIC -m64 -g -xO2 -DNDEBUG -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64  -Dsolaris2=solaris2  -c -o asn1.lo asn1.c
libtool: compile:  /tivoli/tools/solaris2/studio12/SUNWspro/prod/bin/cc -I../include -I. -I../snmplib -instances=static -xmemalign=4i -w -KPIC -m64 -g -xO2 -DNDEBUG -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -Dsolaris2=solaris2 -c asn1.c -o asn1.o
cc: Warning: illegal option -nstances=static
cc: Warning: illegal option -fno-strict-aliasing
"asn1.c", line 619: syntax error before or at: {
"asn1.c", line 619: cannot recover from previous errors
cc: acomp failed for asn1.c
gmake[3]: *** [asn1.lo] Error 1
gmake[2]: *** [subdirs] Error 1
gmake[1]: *** [/BR4/ism_7.4.0.2/sachin.patil_p01854/mtpt1/TOP/solaris/thirdparty/net-snmp/net-snmp-5.9.1/snmplib/.libs/libnetsnmp.a] Error 2
```

Its giving syntax error in asn1.c file at line 619. Below are the contents at line 619:
`if (NETSNMP_BIGENDIAN) {`

Near around code of 619 line is as below:
```
memset(&value.b, *bufp & 0x80 ? 0xff : 0, sizeof(value.b));
    if (NETSNMP_BIGENDIAN) {
        for (i = sizeof(long) - asn_length; asn_length--; i++)
            value.b[i] = *bufp++;
    } else {
        for (i = asn_length - 1; asn_length--; i--)
            value.b[i] = *bufp++;
    }
```

By looking at the code there are no syntax error. Why does cc compiler reports syntax error during compilation for Solaris platform? Compilation works fine for other platforms like windows and zlinux?

Please let us know what could be the issue with Solaris sparc platform.

Note: We had faced similar syntax error issue while compilation of net-snmp 5.9 library on RHEL platform at different place.
We had replaced macro with its definition and it worked. Here, we cant replace macro as definition of macro is constant value as below:
`#  define NETSNMP_BIGENDIAN 1`

We tried changing 619 line from asn1.c as below but it didn't work:
```
    if (NETSNMP_BIGENDIAN == 1) 
	{
        for (i = sizeof(long) - asn_length; asn_length--; i++)
            value.b[i] = *bufp++;
    } 
	else	
	{
        for (i = asn_length - 1; asn_length--; i--)
            value.b[i] = *bufp++;
    }
```

Thanks and Regards,
Nilam Khamkar

**Comment by bvanassche** [comment]
I think this means that the following code is incompatible with Solaris' cc compiler:
```
# define NETSNMP_BIGENDIAN                              \
    (__extension__                                      \
     ({                                                 \
         union { unsigned long l; unsigned char c; } u; \
                                                        \
         u.l = 1;                                       \
         u.c == 0;                                      \
     })                                                 \
    )
```

**Comment by bvanassche** [comment]
Commit 8adf72091f177cca8c8a4e55c5b8740627dd50d4 should fix this issue.
