### ISSUE TITLE
Net-snmp patch 0001-config_os_headers-Error-Fix.patch from 5.8

### ISSUE THREAD

**Issue by sriparnasom** [net-snmp/net-snmp#315]
I am upgrading my net-snmp module version from 5.7.3 to 5.9.1.
I see this patch : 0001-config_os_headers-Error-Fix.patch 

is available both in 5.7.3 and 5.8 but not upstream in 5.9.1 . but without this patch basic functionality walk is not working.

do we need to add this to 5.9.1 or we ahve any other patch? as i dont see bb file in github, not able to determine which are the patches i need to take in 5.9.1

**Comment by bvanassche** [comment]
Please download, build and install Net-SNMP 5.9.1. If you encounter any issues, feel free to report these by opening a new bug report.
