### ISSUE TITLE
USM_NOTINTIMEWINDOW errors frequently seen

### ISSUE THREAD

**Issue by joeclarkia** [net-snmp/net-snmp#33]
On our system (using a code drop from early Oct 2019), under certain conditions (namely, frequent SNMP requests happening, but not seemingly like an overwhelming number), we frequently see the error that is generated by this line of code:

https://github.com/net-snmp/net-snmp/blob/master/snmplib/snmpusm.c#L2618

of the format

boot_uint 0 myBoots 2 time_diff <incrementing with system uptime> => not in time window

When these errors begin to occur, SNMP requests seem to get "flaky".  In some cases the SNMP agent stops responding altogether until the requests stop.

Is there something specific that we can look at to track down what might cause this error to occur?

**Comment by hardaker** [comment]
So your error message is missing the time_difference output, which is strange.  But the boots value (2) is higher than the (0) being sent by the client.  so yes, renegotiation of the time needs to happen and this is normal.  Good continuously running clients shouldn't trigger this on a regular basis.  If on the other hand you're calling CLI clients on a frequent basis, it'll re-negotiate the time window.  in the end, this is a debugging message and shouldn't concern you other that it will take an extra round-trip packet-wise to get the data you want, which will slow things down some.

But I'd suggest the flakiness may depend on what it is you're querying.  The agent itself may be searching for much harder information.  Every request arriving that causes it to dive deep into a complex mib tree will be seen as slow, and has nothing to do with the USM timing.

**Comment by hardaker** [comment]
Feel free to update this bug if you think I'm incorrect.

**Comment by joeclarkia** [comment]
Note that I accidentally used brackets in my original post that made the time_diff disappear.  I have corrected it.  In the end, I'm going with the "it's a debugging message" mentality, and we'll just monitor it (I don't have any more details to add).
