### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by anagaraj-fluke** [net-snmp/net-snmp#336]
Hi,

I Pulled latest master branch.

configured with following command "_./configure --without-openssl --with-default-snmp-version=3 --with-sys-contact=dummy@gmail.com --with-sys-location=2nfoor --with-logfile=snmpd_build.log --with-persistent-directory=/var/net-snmp --without-perl-modules --without-python-modules --disable-embedded-perl --disable-shared --enable-static --enable-ipv6 --with-pic --enable-agent --enable-applications --disable-manuals --disable-scripts --disable-snmptrapd-subagent --with-out-mib-modules=list_"

Following error is observed

libtool: compile:  gcc -I../include -I. -I../agent -I../agent/mibgroup -I../snmplib -D_GNU_SOURCE -D_ALL_SOURCE -D_THREAD_SAFE -D__EXTENSIONS__ -g -O2 -DNETSNMP_ENABLE_IPV6 -fno-strict-aliasing -DNETSNMP_REMOVE_U64 -g -O2 -Ulinux -Dlinux=linux -Wall -Wextra -Wstrict-prototypes -Wwrite-strings -Wcast-qual -Wlogical-op -Wundef -Wno-format-truncation -Wno-missing-field-initializers -Wno-sign-compare -Wno-unused-parameter -c mibgroup/if-mib/data_access/interface_linux.c  -fPIC -DPIC -o mibgroup/if-mib/data_access/interface_linux.o
mibgroup/if-mib/data_access/interface_linux.c:27:2: error: #error libnl-3 is required
 #error libnl-3 is required
  ^
mibgroup/if-mib/data_access/interface_linux.c:29:27: fatal error: netlink/cache.h: No such file or directory
compilation terminated.
Makefile:100: recipe for target 'mibgroup/if-mib/data_access/interface_linux.lo' failed
make[1]: *** [mibgroup/if-mib/data_access/interface_linux.lo] Error 1
make[1]: Leaving directory '/home/devuser/net-snmp/agent'
Makefile:674: recipe for target 'subdirs' failed
make: *** [subdirs] Error 1

**Comment by bvanassche** [comment]
The message `libnl-3 is required` means that the libnl-3 and/or libnl-route-3 development packages are missing. Please install these packages. On Debian and Ubuntu systems these packages can be installed by running `apt-get install libnl-route-3-dev`.

**Comment by randomdude** [comment]
I see the same issue trying to build even after installing `libnl-3-dev` and `libnl-route-3-dev` (I'm using a debian buster-slim docker image). Specifying the config option `--without-nl` isn't enough to get a working build.

**Comment by bvanassche** [comment]
If this hasn't been tried yet, please remove `--without-nl` from the list of options of the Net-SNMP configure script. That option is incompatible with using libnl-3 and libnl-route-3.

**Comment by randomdude** [comment]
Ah, my mistake - removing `--without-nl` as suggested *does* result in a successful compile.

**Comment by bvanassche** [comment]
Thanks for confirming :-) Does that mean that this issue can be closed?

**Comment by randomdude** [comment]
Yes, I'm good now. I'm having other problems but I'll open another issue if I can't figure them out. Thanks!
