### ISSUE TITLE
netsnmpd: malloc(): smallbin double linked list corrupted

### ISSUE THREAD

**Issue by dj95035** [net-snmp/net-snmp#340]
Hi All,

We are running net-snmp 5.8 and use snmpd as proxy. We got the below crash. At the same time frame, snmpd log showed:
2021-08-23_23:40:20.96206 malloc(): smallbin double linked list corrupted
Crash backtrace:

[New LWP 685]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/libthread_db.so.1".
Core was generated by `/usr/sbin/snmpd -f -c /etc/snmp/snmpd.conf -Dsnmpd/main,mib_init -Lo -I usmConf'.
Program terminated with signal SIGABRT, Aborted.
#0 __GI_raise (sig=) at ../sysdeps/unix/sysv/linux/raise.c:50
50 return ret;
#0 __GI_raise (sig=) at ../sysdeps/unix/sysv/linux/raise.c:50
#1 0x000000ffeabb5f68 in __GI_abort () at abort.c:79
#2 0x000000ffeabf8eb8 in __libc_message (action=, fmt=) at ../sysdeps/posix/libc_fatal.c:181
#3 0x000000ffeac01458 in malloc_printerr (str=) at malloc.c:5350
#4 0x000000ffeac04514 in _int_malloc (av=0xffead1b528 , bytes=1099159117824) at malloc.c:3648
#5 0x000000ffeac076a0 in __libc_calloc (n=, elem_size=) at malloc.c:3436
#6 0x000000ffeb17bb1c in netsnmp_create_delegated_cache () from /usr/lib/libnetsnmpagent.so.35
#7 0x000000ffeaf08f5c in proxy_handler () from /usr/lib/libnetsnmpmibs.so.35
#8 0x000000ffeb17a8ec in netsnmp_call_handlers () from /usr/lib/libnetsnmpagent.so.35
#9 0x000000ffeb18ea3c in handle_var_requests () from /usr/lib/libnetsnmpagent.so.35
#10 0x000000ffeb18fe24 in handle_pdu () from /usr/lib/libnetsnmpagent.so.35
#11 0x000000ffeb190050 in netsnmp_handle_request () from /usr/lib/libnetsnmpagent.so.35
#12 0x000000ffeb190744 in handle_snmp_packet () from /usr/lib/libnetsnmpagent.so.35
warning: GDB can't find the start of the function at 0xffead72a6f.

Thanks a lot for your help.
Jenny Yao

**Comment by bvanassche** [comment]
The v5.8 branch is no longer maintained. Please upgrade to the v5.9 branch. If this issue would not yet be solved on the v5.9 branch, try to reproduce this under Valgrind. Unfortunately there is not enough information in the glibc memory corruption reports to determine the root cause.

**Comment by dj95035** [comment]
Hi Bart,

    Thanks a lot for your help.

Jenny
