### ISSUE TITLE
Notification filtering based on snmpNotifyFilterProfileTable and snmpNotifyFilterTable is not working

### ISSUE THREAD

**Issue by porobd** [net-snmp/net-snmp#342]
This was working in net-snmp 5.7 but has stopped working in net-snmp 5.9. As far as I could understand there are 2 issues:

1. The ncompare method (which is used to compare partial indices in a table) pointer was not set for the container used to store the filter information. I changed snmplib/container.c to assign a default ncompare method pointer  (the same way a default compare method pointer is assigned) when finding a container (i.e. in method netsnmp_container_find).

2. The notification filter information is stored in one container but during filtering, a different container is being used to look for matching filters. I changed agent/mibgroup/snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_storage.h and agent/mibgroup/snmp-notification-mib/snmpNotifyFilterTable/snmpNotifyFilterTable_data_access.c to expose the data_storage method that creates the container (used when actual filtering) so that this method can be used when creating the container used to store the notification filters.

Changes are included in the attached file.
[notification_filtering.txt](https://github.com/net-snmp/net-snmp/files/7123454/notification_filtering.txt)

**Comment by bvanassche** [comment]
Please take a look at commits 64a88cc2fdd3e6f4cb7a66d4c2846da97112494e and 1672d705202e0f758133707b3a291319bebfdc66.

**Comment by porobd** [comment]
The commits look good to me. This might be a basic question and pardon me since I am new to the process here. But, how does this change become part of the 5.9.1 code base at https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.1/ ?

**Comment by bvanassche** [comment]
That's a great question. Version 5.9.1 has been released and won't be modified. A conversation is ongoing about the next release. I think that the next release will be assigned version number 5.9.2 and that it will come from the v5.9 branch. It may take a few months however before version 5.9.2 is released.

**Comment by porobd** [comment]
Thank you for the clarification; that helps.
