### ISSUE TITLE
Missing "ERR_GET_FUNC"

### ISSUE THREAD

**Issue by gvanem** [net-snmp/net-snmp#343]
In the function `netsnmp_openssl_err_log()` there is this:
```c
        snmp_log(LOG_ERR, "library=%d, function=%d, reason=%d\n",
                 ERR_GET_LIB(err), ERR_GET_FUNC(err), ERR_GET_REASON(err));
```

According to https://www.openssl.org/news/changelog.html, the `ERR_GET_FUNC()` macro (?) was removed some time ago.
Could this be patched like this:
```diff
--- a/snmplib/snmp_openssl.c 2021-09-08 09:10:44
+++ b/snmplib/snmp_openssl.c 2021-09-08 11:33:34
@@ -939,6 +939,10 @@


 #ifndef NETSNMP_FEATURE_REMOVE_OPENSSL_ERR_LOG
+#ifndef ERR_GET_FUNC
+#define ERR_GET_FUNC(e)  (int)(((e) >> 12L) & 0xFFFL) /* removed in OpenSSL 3.0 */
+#endif
+
 void
 netsnmp_openssl_err_log(const char *prefix)
```

I see no reference to `NETSNMP_FEATURE_REMOVE_OPENSSL_ERR_LOG`. So this function is always compiled AFAICS.

**Comment by bvanassche** [comment]
Please take a look at commits 19e75743173cb8d49d49fd685b8e0249e83cc820 (v5.9 branch) and 8518bafe941eb6f9a1abe4d2d0a3ac18347074b4 (master branch).
