### ISSUE TITLE
Build fail with latest master branch

### ISSUE THREAD

**Issue by anagaraj-fluke** [net-snmp/net-snmp#351]
Hi, 
I did pull the latest master branch and configured with following command.

./configure --with-openssl=/usr/local/ssl --with-default-snmp-version=3 --with-sys-contact=dummy@gmail.com --with-sys-location=2nfoor --with-logfile=snmpd_build.log --with-persistent-directory=/var/net-snmp --without-perl-modules --without-python-modules --disable-embedded-perl --disable-shared --enable-static --enable-ipv6 --with-pic --enable-agent --enable-applications --disable-manuals --disable-scripts --disable-snmptrapd-subagent --with-out-mib-modules=lis

I get the following error

make[1]: Entering directory '/home/devuser/net-snmp/testing'
(cd fuzzing && ./build.sh)
clang: error: unsupported argument 'fuzzer-no-link' to option 'fsanitize='
Makefile:145: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/devuser/net-snmp/testing'
Makefile:674: recipe for target 'subdirs' failed
make: *** [subdirs] Error 1

Please let me know, if i missed anything during configuration.

**Comment by anagaraj-fluke** [comment]
I am getting the following error with the latest master branch.
Can testing be disabled with configuration ?

make[4]: *** No rule to make target 'installlibs'.  Stop.
make[4]: Leaving directory <build_dir_name>/net-snmp/testing'
Makefile:872: recipe for target 'installsubdirlibs' failed
make[3]: *** [installsubdirlibs] Error 1
make[3]: Leaving directory '<build_dir_name>/net-snmp'
CMakeFiles/net-snmp.dir/build.make:73: recipe for target 'net-snmp-prefix/src/net-snmp-stamp/net-snmp-install' failed
make[2]: *** [net-snmp-prefix/src/net-snmp-stamp/net-snmp-install] Error 2
make[2]: Leaving directory <build_dir_name>
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/net-snmp.dir/all' failed
make[1]: *** [CMakeFiles/net-snmp.dir/all] Error 2
make[1]: Leaving directory <build_dir_name>
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bvanassche** [comment]
Please reopen if this needs further attention.
