### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by VFMick** [net-snmp/net-snmp#368]
When trying to build in Centos 7 i run the make command and then it fails partway through
/usr/bin/perl $carp Makefile.PL -NET-SNMP-IN-SOURCE=true		\
    -NET-SNMP-CONFIG="sh $dir/net-snmp-config" 
Can't locate ExtUtils/MakeMaker.pm in @INC (@INC contains: /home/mick/Downloads/net-snmp-5.9.1/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at Makefile.PL line 3.
BEGIN failed--compilation aborted at Makefile.PL line 3.
make: *** [perl/Makefile] Error 2

Does anyone know what might be causing the issue?

**Comment by bvanassche** [comment]
Does this help?
```
yum install -y perl-ExtUtils-MakeMaker
```

**Comment by VFMick** [comment]
Yes it does thank you. The install completes OK and i now need to work through configuration.
