### ISSUE TITLE
SNMP-5.9.1: SNMP build is failing on solaris systems

### ISSUE THREAD

**Issue by satish2123** [net-snmp/net-snmp#376]
Hello,

I have tried downloading the source code from the https://sourceforge.net/projects/net-snmp/
and tried compile on solaris systems. getting below compilation errors:

"../../snmplib/large_fd_set.c", line 179: cannot have void object: tmo
"../../snmplib/large_fd_set.c", line 182: warning: left operand of "." must be struct/union object
"../../snmplib/large_fd_set.c", line 182: cannot access member of non-struct/union object
"../../snmplib/large_fd_set.c", line 183: warning: left operand of "." must be struct/union object
"../../snmplib/large_fd_set.c", line 183: cannot access member of non-struct/union object
"../../snmplib/large_fd_set.c", line 200: warning: argument #5 is incompatible with prototype:
        prototype: restrict pointer to struct timeval {long tv_sec, long tv_usec} : "/usr/include/sys/select.h", line 135
        argument : pointer to int
cc: acomp failed for ../../snmplib/large_fd_set.c

After doing some analysis, I observed that configure is creating net-snmp-config.h file and the below actual source .h file content is changed like below:

#define NETSNMP_SELECT_TIMEVAL struct timeval --> source win/net-snmp/net-snmp-config.h
to
#define NETSNMP_SELECT_TIMEVAL void --> generated by configure

I believe the problem here is with generated net-snmp-config.h file which is inturn the problem with configure utility.

please someone help how to mitigate this issue on solaris.

Note: I built this on Linux systems and it worked fine. the net-snmp-config.h file generated properly

Thanks,
Satish.

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.9 branch (https://github.com/net-snmp/net-snmp/tree/V5-9-patches). Does that help?

**Comment by satish2123** [comment]
Hello,

Thanks for the response, I have incorporated the above two changes mentioned in the configure files and tried compilation against the solaris systems but still the same error.
the generated net-snmp-config.h file still contains void instead of "struct timeval".

"../../snmplib/large_fd_set.c", line 179: cannot have void object: tmo
"../../snmplib/large_fd_set.c", line 182: warning: left operand of "." must be struct/union object
"../../snmplib/large_fd_set.c", line 182: cannot access member of non-struct/union object
"../../snmplib/large_fd_set.c", line 183: warning: left operand of "." must be struct/union object
"../../snmplib/large_fd_set.c", line 183: cannot access member of non-struct/union object
"../../snmplib/large_fd_set.c", line 200: warning: argument #5 is incompatible with prototype:
prototype: restrict pointer to struct timeval {long tv_sec, long tv_usec} : "/usr/include/sys/select.h", line 135
argument : pointer to int
cc: acomp failed for ../../snmplib/large_fd_set.c

Thanks,
Satish.

**Comment by satish2123** [comment]
Hello,
Just checking if any update on this issue. Thanks in advance.

Satish.

**Comment by bvanassche** [comment]
I'm not sure any Net-SNMP developer has access to a Solaris system. So a patch would be appreciated.

**Comment by abdulmuqsith** [comment]
Similar error on AIX

"large_fd_set.c", line 179.28: 1506-160 (S) Object tmo cannot be declared as type void.
make[1]: *** [large_fd_set.lo] Error 1

**Comment by bvanassche** [comment]
Which version of AIX? Which compiler? Net-SNMP builds fine on AIX 7 with xlc as far as I can see:
~~~
$ uname -a
AIX power-aix 1 7 00F84C0C4C00
$ grep SELECT_TIMEVAL include/net-snmp/net-snmp-config.h
#define NETSNMP_SELECT_TIMEVAL struct timeval
~~~

**Comment by abdulmuqsith** [comment]
```
$ oslevel
5.3.0.0
```


```
$ cc -qversion
IBM XL C/C++ for AIX, V11.1 (5724-X13)
Version: 11.01.0000.0000
```

```
$ grep NETSNMP_SELECT_TIMEVAL include/net-snmp/net-snmp-config.h
#define NETSNMP_SELECT_TIMEVAL void

```

**Comment by abdulmuqsith** [comment]
Same issue on HPUX

```
$ uname -a
HP-UX xxxxx B.11.23 U ia64 1284665958 unlimited-user license

```
```
$ cc --version
cc: HP C/aC++ B3910B A.06.25 [Nov 30 2009]

```
```
$ grep NETSNMP_SELECT_TIMEVAL include/net-snmp/net-snmp-config.h
#define NETSNMP_SELECT_TIMEVAL void

```

**Comment by bvanassche** [comment]
Please share `config.log`.

**Comment by abdulmuqsith** [comment]
[configure.log](https://github.com/net-snmp/net-snmp/files/7631022/configure.log)

**Comment by bvanassche** [comment]
Thank you for having shared the `config.log` file. In that file I found the following: `cc: 1501-210 (S) command option Werror contains an incorrect subargument`. So the select() test needs to be modified such that it does not use -Werror.

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.9 and master branches. Please retest.

**Comment by satish2123** [comment]
Will this candidate fix works for solaris also?

**Comment by bvanassche** [comment]
Yes. I expect it to also fix the build for (older) Solaris systems.
