### ISSUE TITLE
winExtDLL not loading

### ISSUE THREAD

**Issue by janclod** [net-snmp/net-snmp#383]
Last time writing down my problem lead me to a solution, so I will describe my new problem here and hope it will also get me closer to a solution :)

Goal: run NetSNMP agent v3 on Win10

Requirement 1: v3 with both authentication and encryption (e.g., SHA/AES)

Requirement 2: need to load extension of Windows agent written years ago by someone else

**V5-9-patches scenario**
I am able to fulfil requirements 1 by running my own build of the `V5-9-patches` branch. Using the `V5-9-patches` build I am not able to load the winExtDLL, this is the debug information:
```
registered debug token winExtDLL, 1
init_winExtDLL started.
winExtDLL: read_extension_dlls_from_registry called
init_winExtDLL: found 0 extension DLLs in the registry.
init_winExtDLL: registered 0 OID ranges.
init_winExtDLL finished.
```

Build information
Architecture: x86
OpenSSL: v3 32bit

**v5.5.0 binary scenario**
I am able to fulfil requirement 2 by running the binaries downloadable from sourceforge (v5.5.0 64-bit), but not requirements 1. As far as I understand it is not possible to install NetSNMP with encryption support from binary, please correct if I am wrong. So the first scenario is where I am looking for a solution.

Bug trace
```
init_winExtDLL started.
winExtDLL: read_extension_dlls_from_registry called
registry key SOFTWARE\mysoftware\CurrentVersion: DLL C:\Windows\System32\mysnmp.dll.
registry key Software\mysoftware\CurrentVersion: DLL C:\Windows\System32\mysnmp.dll.
init_winExtDLL: found 2 extension DLLs in the registry.
loading DLL C:\Windows\System32\mysnmp.dll.
loading DLL C:\Windows\System32\mysnmp.dll.
registering handler for DLL C:\Windows\System32\mysnmp.dll and OID prefix .1.3.6.1.4.1.XXXXX
registering handler for DLL C:\Windows\System32\mysnmp.dll and OID prefix .1.3.6.1.4.1.XXXXX
registering handler for DLL C:\Windows\System32\mysnmp.dll and OID prefix .1.3.6.1.4.1.XXXXXX
OID range .1.3.6.1.4.1.96788: replacing handler C:\Windows\System32\mysnmp.dll by C:\Windows\System32\mysnmp.dll.
init_winExtDLL: registered 4 OID ranges.
init_winExtDLL finished.
```

This is how my registry looks like:
```
Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SNMP\Parameters\ExtensionAgents
Default REG_SZ                (value not set)
0           REG_SZ                Software\mysoftware\CurrentVersion
1           REG_SZ                SOFTWARE\mysoftware\CurrentVersion
```

Can you provide some guidance for scenario V5-9-patches? Should I try building from a different branch? Is this a bug (unlikely)?

**Comment by bvanassche** [comment]
winExtDLL can only load Windows SNMP DLLs after these have been installed. Is SNMP still supported by Windows 10? The following appears if I try to install SNMP in a Windows 10 VM:
~~~
$ Enable-WindowsOptionalFeature -online -FeatureName SNMP
Enable-WindowsOptionalFeature : Feature name SNMP is unknown.
At line:1 char:1
+ Enable-WindowsOptionalFeature -online -FeatureName SNMP
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand
~~~

**Comment by janclod** [comment]
Thank you Bart for your contribution :)

Windows 10 still offers the SNMP service, it is simply extra hidden. I did install the SNMP Win service following [this strategy](https://www.thewindowsclub.com/enable-and-configure-snmp-service-in-windows) and the customized winExtDLL is registered.

I also dare to claim that the winExtDLL SNMP works based:

- on the output posted above, see v5.5.0 binary scenario
- on the fact that I am able to query the custom SNMP loaded from winExtDLLs

Based on some extra debugging, I found out that NetSNMP fails to open the Win registry (where the winExtDLL path is stored): `SOFTWARE\mysoftware\CurrentVersion`

**Comment by janclod** [comment]
In my specific case, the `mysnmp.dll` was a 64-bit version. In the `V5-9-patches` scenario I was trying to load the 64-bit library (DLL) into a 32-bit process. This is not allowed.
https://docs.microsoft.com/en-us/windows/win32/winprog64/process-interoperability

SOLUTION: build NetSNMP agent using `x64` environment

Specifications
NetSNMP: branch V5-9-patches
OpenSSL: Win64OpenSSL-3_0_0.exe
Build env: x64
winExtDLL: mysnmp.dll (64-bit version)
