### ISSUE TITLE
NET-SNMP fails to compile for host=arm-linux-gnueabihf

### ISSUE THREAD

**Issue by glenfine** [net-snmp/net-snmp#391]
When I use:

**./configure \
--host=arm-linux-gnueabihf \
--target=arm-linux-gnueabihf \
--build=i686 \
--disable-manuals \
--disable-ipv6 \
--with-cc=arm-linux-gnueabihf-gcc \
--with-ar=arm-linux-gnueabihf-ar \
--without-rpm \
--disable-applications \
--disable-embedded-perl \
--disable-deprecated \
--disable-shared \--
--with-pcre \
--enable-static LDFLAGS="-L/home/crayfish/openvuplus_3.0/build/vusolo4k/tmp/sysroots/vusolo4k/usr/lib/libpcre"  \
--with-sysroot=/home/crayfish/openvuplus_3.0/build/vusolo4k/tmp/sysroots/vusolo4k/**

It ends up with an error in linking to pcre_exec. 

**Downloads/net-snmp-5.9.1/agent/mibgroup/if-mib/data_access/interface.c:860: undefined reference to `pcre_exec'
collect2: error: ld returned 1 exit status
Makefile:999: recipe for target 'snmpd' failed
make[1]: *** [snmpd] Error 1
make[1]: Leaving directory '/home/cobham/Downloads/net-snmp-5.9.1/agent'
Makefile:674: recipe for target 'subdirs' failed
make: *** [subdirs] Error 1**

Anyone have an idea of how to get around this showstopper?  

G

**Comment by bvanassche** [comment]
Is /home/crayfish/openvuplus_3.0/build/vusolo4k/tmp/sysroots/vusolo4k/usr/lib/libpcre a directory? If not, please leave out `/libpcre`.

**Comment by glenfine** [comment]
HI Bart, 
Nope. Did a **make clean** then the ./configure without the **enable-static** line. Did

**./configure
--host=arm-linux-gnueabihf
--target=arm-linux-gnueabihf
--build=i686
--disable-manuals
--disable-ipv6
--with-cc=arm-linux-gnueabihf-gcc
--with-ar=arm-linux-gnueabihf-ar
--without-rpm
--disable-applications
--disable-embedded-perl
--disable-deprecated
--disable-shared**

Generated the same error. If this configure is wrong I need to find the right ./configure incantation. 
**/home/user/Downloads/net-snmp-5.9.1/agent/mibgroup/if-mib/data_access/interface.c:860: undefined reference to `pcre_exec'
collect2: error: ld returned 1 exit status
Makefile:999: recipe for target 'snmpd' failed
make[1]: *** [snmpd] Error 1
make[1]: Leaving directory '/home/user/Downloads/net-snmp-5.9.1/agent'
Makefile:674: recipe for target 'subdirs' failed
make: *** [subdirs] Error 1**


Cheers, 
G

**Comment by glenfine** [comment]
This seemed to work.

**./configure \
--host=arm-linux-gnueabihf \
--target=arm-linux-gnueabihf \
--build=i686 \
--disable-manuals \
--disable-ipv6 \
--with-cc=arm-linux-gnueabihf-gcc \
--with-ar=arm-linux-gnueabihf-ar \
--without-rpm \
--disable-applications \
--disable-embedded-perl \
--disable-deprecated \
--disable-shared \
--without-pcre**

Needed the without-pcre added to the configure. 

Cheers, 

G

**Comment by bvanassche** [comment]
I think that --target and --build can be left out. This is how I cross-compile Net-SNMP:
```
./configure
--enable-ipv6
--with-defaults
--enable-new-features
--with-default-snmp-version=2
--with-systemd
--with-transports='IPX STD UDPshared'
--with-security-modules='usm tsm'
--with-mib-modules='agent/extend examples/data_set examples/delayed_instance examples/example examples/notification examples/scalar_int examples/ucdDemoPublic examples/watched smux deliver/deliverByNotify disman/event disman/expression disman/mteEventNotificationTable disman/mteEventTable disman/mteObjectsTable disman/mteTriggerBooleanTable disman/mteTriggerDeltaTable disman/mteTriggerExistenceTable disman/mteTriggerTable disman/mteTriggerThresholdTable disman/nslookup-mib disman/ping-mib disman/schedule disman/traceroute-mib etherlike-mib examples/netSnmpHostsTable hardware/cpu hardware/fsys hardware/memory host ip-forward-mib ip-mib/inetNetToMediaTable ip-mib/ipDefaultRouterTable ip-mib/ipv4InterfaceTable ip-mib/ipv6InterfaceTable ip-mib/ipv6ScopeZoneIndexTable mibII/mta_sendmail misc/ipfwacc sctp-mib snmp-notification-mib tcp-mib testhandler tunnel ucd-snmp/diskio ucd-snmp/extensible udp-mib rmon-mib'
--host=arm-linux-gnueabihf
--without-openssl
--without-perl-modules
--disable-embedded-perl
--without-python-modules
--without-pcre
```
