### ISSUE TITLE
AES support without openssl

### ISSUE THREAD

**Issue by daab007** [net-snmp/net-snmp#393]
Hello,

I have running application using the _authPriv_ security level. It works great, but seems that _AES_ is not supported without the _openssl_ lib. Looks like, that the _NETSNMP_USE_INTERNAL_CRYPTO_ introduces _DES_ for the encyption only.

Question: do I need to have _openssl_ library to have support for _AES_?

**Comment by janclod** [comment]
As far as I understand, yes :)

I have been busy building NetSNMP for Win over the last months and I needed OpenSSL for building NetSNMP with AES support.

Are you building on Win or others?

**Comment by hardaker** [comment]
Yes, we don't have an extracted AES module in the source code at this point (and likely won't in the future).  It was a fair amount of work to get the extracted DES/MD5 code out and tested, and we'd need to do something similar for AES to pull it off.

**Comment by daab007** [comment]
I saw, that AES has been removed with these commits: [1](https://github.com/net-snmp/net-snmp/commit/c10b756d84978b9c3b5aa907fe8723b9869dc386) and [2](https://github.com/net-snmp/net-snmp/commit/b964eebe0064b80946be0ca05c9dd2beb52f47e9), but there are some places related to "internal support" for the AES left in the code.

Maybe it would be a good idea to remove AES from the [readme file](https://github.com/net-snmp/net-snmp/blob/master/README.snmpv3).

Thanks for clarification, all is clear.
