### ISSUE TITLE
snmpv1 trap ipv6,  error "unknown host: 2000::1996"

### ISSUE THREAD

**Issue by phongting** [net-snmp/net-snmp#395]
version: net-snmp 5.9.1 
When I snmptraped with ipv6 in the agent-addr parameter, snmptrap reported the error:  "unknown host: 2000::1996".
`/usr/local/net-snmp/bin/snmptrap -v1 -c test [2000::1995]:162 '' 2000::1996 6 0 1000 snmpInSetRequests.0 c 0`

If I replace ipv4 with '2000::1996', it would send seccess:
`/usr/local/net-snmp/bin/snmptrap -v1 -c test [2000::1995]:162 '' 192.168.1.1 6 0 1000 snmpInSetRequests.0 c 0`

Viewing the code, I find snmptrap parsing the arg of agent-addr with function 'netsnmp_gethostbyname_v4()':
apps\snmptrap.c:273
``` code
agent = argv[arg];
if (agent != NULL && strlen(agent) != 0) {
    int ret = netsnmp_gethostbyname_v4(agent, pdu_in_addr_t);
    if (ret < 0) {
        fprintf(stderr, "unknown host: %s\n", agent);
        goto out;
    }
} else {
    *pdu_in_addr_t = get_myaddr();
}
```

**Comment by bvanassche** [comment]
SNMPv1 traps only support IPv4 agent addresses according to https://datatracker.ietf.org/doc/html/rfc1157.
