### ISSUE TITLE
Traps v2. Source address

### ISSUE THREAD

**Issue by daab007** [net-snmp/net-snmp#396]
Hello,

I am using the stack in our embedded system for receiving traps from agents. When I am using traps v1, I have expected agent's address in the field _agent_addr_ . 

How about traps v2? I am receiving 0.0.0.0 there. How can I obtain the address of the source?

**Comment by nielsb** [comment]
With a bit of luck it is found as the varbind snmpTrapAddress (.1.3.6.1.6.3.18.1.3.0), otherwise you will have to check the transport parameters for the source address.
/Niels
