### ISSUE TITLE
Configuration override of nsCacheTimeout does not affect actual timeout

### ISSUE THREAD

**Issue by kaiw** [net-snmp/net-snmp#406]
When configured with an `override` directive, `NET-SNMP-AGENT-MIB::nsCacheTimeout` appears to take on the configured value (i.e., an `snmpget` shows the configured value), but the actual cache timeout does not change.

To reproduce, add e.g., `override 1.3.6.1.4.1.8072.1.5.3.1.2.1.3.6.1.2.1.2.2 integer 5` to `snmpd.conf` and restart. Running `snmpget -c <community> 127.0.0.1 NET-SNMP-AGENT-MIB::nsCacheTimeout.1.3.6.1.2.1.2.2` will show the configured timeout. However, running `watch -n 1 snmpwalk -c <community> 127.0.0.1 IF-MIB::ifHCInOctets` will show that the value updates every 3 seconds, which is the default frequency.

If `NET-SNMP-AGENT-MIB::nsCacheTimeout` is configured using `snmpset` after startup, then the same `snmpwalk` command shows that the cached values update at the expected frequency.

**Comment by kaiw** [comment]
Sorry, should have mentioned that this is version 5.7.2.

**Comment by fenner** [comment]
This is exactly the behavior that the `override` configuration file option provides: pretend via SNMP that the object that you specify has the value that you specify, but ignore that fact internally.

There is no configuration option for the behavior that you're looking for.  Rows in the nsCacheTable are only created as caches are created, and caches are created with the `nsCacheDefaultTimeout.0` value.

**Comment by kaiw** [comment]
Fair enough. I clearly misunderstood `override`. Thanks.
