### ISSUE TITLE
Too permissive authorization for authPriv with snmpv3

### ISSUE THREAD

**Issue by manticorps** [net-snmp/net-snmp#413]
## Context
I am testing with net-snmp and I am surprised by the acceptance of some messages. A user with a configured private key, accepts a request without the use of the key, if the message request is set to authNoPriv.

I think the request should be fully compliant with the user, if the user has authentication and a private key, the system should never accept an unencrypted message.

## Reproduce 

Create a docker with the following dockerfile :
```
FROM ubuntu:20.04

# Other tools
RUN apt-get update -y && apt-get install -y tcpdump vim net-tools man-db

# SNMP dependencies.
RUN apt-get install -y snmpd snmp libsnmp-dev snmptrapd
RUN net-snmp-create-v3-user -ro -A STrP@SSWRD -a SHA -X STr0ngP@SSWRD -x AES snmpadmin
```

**build docker**
`docker build . -t test-snm`

**Run docker**
`docker container run -it test-snmp`

### Send request with authPriv (from docker command line)
`snmpwalk -v3 -a SHA -A STrP@SSWRD -x AES -X STr0ngP@SSWRD -l authPriv -u snmpadmin localhost | head`

```
iso.3.6.1.2.1.1.1.0 = STRING: "Linux e6e17675adcd 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
iso.3.6.1.2.1.1.3.0 = Timeticks: (4088) 0:00:40.88
iso.3.6.1.2.1.1.4.0 = STRING: "Me <me@example.org>"
iso.3.6.1.2.1.1.5.0 = STRING: "e6e17675adcd"
iso.3.6.1.2.1.1.6.0 = STRING: "Sitting on the Dock of the Bay"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.11.3.1.1
```
-> status is OK as expected

### Send request with authPriv but invalid key

`snmpwalk -v3 -a SHA -A STrP@SSWRD -x AES -X STr0ngP@SSWRD1AAAAAAAAAAAAAAA -l authPriv -u snmpadmin localhost | head`

-> status is KO as expected

### Send request with authNoPriv
snmpwalk -v3 -a SHA -A STrP@SSWRD -x AES -X STr0ngP@SSWRD -l authNoPriv -u snmpadmin localhost | head

```
iso.3.6.1.2.1.1.1.0 = STRING: "Linux e6e17675adcd 5.16.5-arch1-1 #1 SMP PREEMPT Tue, 01 Feb 2022 21:42:50 +0000 x86_64"
iso.3.6.1.2.1.1.2.0 = OID: iso.3.6.1.4.1.8072.3.2.10
iso.3.6.1.2.1.1.3.0 = Timeticks: (11290) 0:01:52.90
iso.3.6.1.2.1.1.4.0 = STRING: "Me <me@example.org>"
iso.3.6.1.2.1.1.5.0 = STRING: "e6e17675adcd"
iso.3.6.1.2.1.1.6.0 = STRING: "Sitting on the Dock of the Bay"
iso.3.6.1.2.1.1.7.0 = INTEGER: 72
iso.3.6.1.2.1.1.8.0 = Timeticks: (0) 0:00:00.00
iso.3.6.1.2.1.1.9.1.2.1 = OID: iso.3.6.1.6.3.10.3.1.1
iso.3.6.1.2.1.1.9.1.2.2 = OID: iso.3.6.1.6.3.11.3.1.1
```
-> status is OK

## Reference 

From what I have read and understand, if the security level is authPriv the expected behavior is : AUTHORIZATION_ERROR

## Version

**NET-SNMP version 5.8**

Best regards

**Comment by fenner** [comment]
`net-snmp-create-v3-user` uses `rouser` or `rwuser` with no additional qualifications, which results in the behavior that you observe.  If you add `priv` to the end of the `rouser`/`rwuser` configuration, then you get your desired behavior.

**Comment by manticorps** [comment]
Gee, I feel a little silly...

Probably because I'm stuck with a lot of misunderstanding about SNMPv3 protocol, and I'm working hard to understand USM / VACM.

Thanks sorry for this false issue.
