### ISSUE TITLE
parallel compilation failures

### ISSUE THREAD

**Issue by citrus-it** [net-snmp/net-snmp#415]
I know that various parallel build failures have been fixed in the past, but I still see some occasionally if I run with enough parallelism. It always looks like this:

```
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so.40" && ln -s "libnetsnmpagent.so.40.0.0" "libnetsnmpagent.so.40")
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so.40" && ln -s "libnetsnmpagent.so.40.0.0" "libnetsnmpagent.so.40")
ln: cannot create libnetsnmpagent.so.40: File exists
gmake[1]: *** [Makefile:964: libnetsnmpagent.la] Error 2
gmake[1]: *** Waiting for unfinished jobs....
libtool: link: (cd ".libs" && rm -f "libnetsnmpagent.so" && ln -s "libnetsnmpagent.so.40.0.0" "libnetsnmpagent.so")
libtool: link: ( cd ".libs" && rm -f "libnetsnmpagent.la" && ln -s "../libnetsnmpagent.la" "libnetsnmpagent.la" )
: libnetsnmpagent.la -lnetsnmp -lnetsnmphelpers
gmake[1]: Leaving directory '/home/af/net-snmp/agent'
gmake: *** [Makefile:675: subdirs] Error 1
```

which, to me, looks like two different processes are trying to create the symlink for `libnetsnmpagent.so.40.0.0` at the same time. I've stared at the makefile and cannot work out why this is happening. Any help appreciated as I'd like to reduce the build time for net-snmp, and building with -j1 takes quite a while.

Thanks!

**Comment by bvanassche** [comment]
Which Net-SNMP version are you using? I haven't seen any build failures recently with the v5.9 or master branches.
