### ISSUE TITLE
Crash when parsing config (createUser)

### ISSUE THREAD

**Issue by mindcrunch4u** [net-snmp/net-snmp#416]
Version: `v5.9.1`
Configure options: `-without-perl-modules --disable-embedded-perl --with-cflags=-g  --disable-mib-loading`

Reproduce: add this line to your _**snmpd.conf**_
`createUser test blah`
This is a bad configuration, and it should result in error instead of crashing

Call stack:
`read_config() -> run_config_handler() -> usm_parse_create_usmUser() -> usm_create_usmUser_from_string()`
at: `usm_create_usmUser_from_string()`
in: api/net-snmp/snmplib/snmpusm.c
line: `4489`
code: `if ((strncmp(cp, "default", 7) == 0) && (NULL != def_auth_prot)) {`
root cause: **_cp_** is 0x0, which causes strncmp to crash

Suggestion: change the line to
`if (( cp && strncmp(cp, "default", 7) == 0) && (NULL != def_auth_prot)) {`

BTW: I couldn't build the latest(master) branch, therefore I filed an issue (instead of fixing it myself)
error:
`mibgroup/if-mib/data_access/interface_linux.c:27:2: error: #error libnl-3 is required. Please install the libnl-3 and libnl-route-3 development packages and remove --without-nl from the configure options if necessary.`
I've installed `libnl-*-3-dev` on `Ubuntu 20.04`, reconfigured, make clean, and make again. No luck.
Perhaps I'm missing something, I'd appreciate it if anyone can point me to the latest development guide.

Thanks.

**Comment by moshekaplan** [comment]
Replicated with current master branch:
```
$ sudo ./agent/snmpd -fd -C  -c /etc/snmp/snmpd.conf
snmpusm.c:4677:10: runtime error: null pointer passed as argument 1, which is declared to never be null
AddressSanitizer:DEADLYSIGNAL
=================================================================
==503704==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7f301b2c7ac8 bp 0x7ffe9a893e70 sp 0x7ffe9a8935e0 T0)
==503704==The signal is caused by a READ memory access.
==503704==Hint: address points to the zero page.
    #0 0x7f301b2c7ac8 in __interceptor_strncmp ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:559
    #1 0x7f301987a17c in usm_create_usmUser_from_string /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4677
    #2 0x7f301987f527 in usm_parse_create_usmUser /home/user/Desktop/net-snmp/snmplib/snmpusm.c:4977
    #3 0x7f30197a8630 in run_config_handler /home/user/Desktop/net-snmp/snmplib/read_config.c:565
    #4 0x7f30197aba92 in read_config /home/user/Desktop/net-snmp/snmplib/read_config.c:990
    #5 0x7f30197a7ca5 in read_config_with_type_when /home/user/Desktop/net-snmp/snmplib/read_config.c:499
    #6 0x7f30197ac2ad in read_configs_optional /home/user/Desktop/net-snmp/snmplib/read_config.c:1048
    #7 0x7f30197ac564 in read_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1079
    #8 0x7f301971a6ae in init_snmp /home/user/Desktop/net-snmp/snmplib/snmp_api.c:930
    #9 0x562c359adec1 in main /home/user/Desktop/net-snmp/agent/snmpd.c:909
    #10 0x7f3018c23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #11 0x7f3018c23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #12 0x562c359aaee4 in _start (/home/user/Desktop/net-snmp/agent/.libs/snmpd+0x8ee4) (BuildId: ca8b245b5833c44ad0c7e0ffb1182f1ce6138855)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:559 in __interceptor_strncmp
==503704==ABORTING
```
