### ISSUE TITLE
Memory leak PreRelease 5.9.2

### ISSUE THREAD

**Issue by Chanilabulle** [net-snmp/net-snmp#418]
release: v5.9.2
Configure options:
message(STATUS "Calling Configure command for net snmp")
execute_process(COMMAND ./configure --prefix=${PREFIX_PATH} 
                                    --host=${TOOLCHAIN_TUPPLE} 
                                    --target=${TOOLCHAIN_TUPPLE} 
                                    --with-cc=${TOOLCHAIN_PATH}/${TOOLCHAIN_TUPPLE}-gcc 
                                    --with-ar=${TOOLCHAIN_PATH}/${TOOLCHAIN_TUPPLE}-ar 
                                    --with-sysroot=${TOOLCHAIN_PATH} 
                                    --enable-agent 
                                    --enable-applications 
                                    --disable-manuals 
                                    --disable-scripts 
                                    --enable-mibs 
                                    --enable-mib-loading 
                                    --disable-ipv6 
                                    --disable-embedded-perl 
                                    --enable-des 
                                    --enable-privacy 
                                    --with-default-snmp-version=3
                                    "--with-out-transports=Unix AAL5PVC IPX UDPIPv6 TCPIPv6" 
                                    --disable-snmptrapd-subagent 
                                    --with-mib-modules=snmpv3mibs    
                                    --with-mibdirs=${PROJECT_SOURCE_DIR}/Supervision/Common/Snmp/mibcompiler/mibs   
                                    --with-mibs=all
                                    --with-logfile=/var/log/snmpd.log 
                                    --with-persistent-directory=/var/net-snmp
                                    --without-perl-modules 
                                    --without-efence 
                                    --without-rsaref 
                                    --with-openssl=internal 
                                    --enable-shared 
                                    --enable-static 
                                    --disable-read-only
                                    --disable-embedded-perl 
                                    --without-rpm 
                                    --without-pkcs 
                                    --without-libwrap 
                                    --without-bzip2 
                                    --without-zlib 
                                    --with-libs=-lpthread
                                    --with-endianness=little
                                    "--with-cflags=-w -O0 -g" WORKING_DIRECTORY ${SUP_NET_SNMP})

I already tried release 5.73, 5.9.1 and this last pre 5.9.2 and the result is the same : memory leak when I use an SNMP V3 user account.

The script (with valid @IP and oid) to reproduce : 
#!/bin/sh
i=0
for (( ; ; ))
do
echo "New scan ..."
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
 	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid
	snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password'  -x DES -X 'D_Password' @IP oid	
	sleep 0.1
done

Memory leak : 10M / hour

Thanks.

**Comment by bvanassche** [comment]
Please define "memory leak". Did you perhaps monitor RSS with `ps`? An increasing RSS number is not the same as a memory leak.

**Comment by Chanilabulle** [comment]
Thanks for your reply.
To investigate we use data from /proc/<pid>/status and /proc/meminfo

**Comment by bvanassche** [comment]
The data in /proc/${pid}/status and /proc/meminfo cannot be used to detect memory leaks reliably. Please use a tool like Valgrind or LeakSanitizer to detect memory leaks.

**Comment by Chanilabulle** [comment]
With Valgrind we can see several memory leaks in SNMP with the following script 👍 
The script (with valid @ip and oid) to reproduce :
#!/bin/sh
i=0
for (( ; ; ))
do
echo "New scan ..."
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
snmpget -v 3 -l authPriv -u User1 -a MD5 -A 'A_Password' -x DES -X 'D_Password' @ip oid
sleep 0.1
done

**Traces of valgring :**


==20872== 11,616 bytes in 363 blocks are definitely lost in loss record 1,405 of 1,450
==20872==    at 0x484C494: calloc (vg_replace_malloc.c:1328)
==20872==    by 0x2DCB0F: snmpv3_parse (snmp_api.c:3920) **"pdu->contextEngineID = (u_char *) calloc(1, SNMP_MAX_ENG_SIZE);"**
==20872==    by 0x2DE243: _snmp_parse (snmp_api.c:4387)
==20872==    by 0x2DE96B: snmp_parse (snmp_api.c:4572)
==20872==    by 0x2E22C3: _sess_process_packet_parse_pdu (snmp_api.c:5674)
==20872==    by 0x2E2BBB: _sess_process_packet (snmp_api.c:5907)
==20872==    by 0x2E3857: _sess_read (snmp_api.c:6179)
==20872==    by 0x2E4687: snmp_sess_read2 (snmp_api.c:6452)
==20872==    by 0x2E2DC3: snmp_read2 (snmp_api.c:5967)
==20872==    by 0x2102EF: receive (snmpd.c:1379)
==20872==    by 0x20FC3F: snmpd_main (snmpd.c:1161)
==20872==    by 0x1F8B33: snm_main (SNM_task.c:126)
==20872==    by 0x4921F43: ??? (in /usr/lib/libpsos.so.0.0.0)
==20872==
==20872== 23,168 bytes in 362 blocks are definitely lost in loss record 1,417 of 1,450
==20872==    at 0x484C494: calloc (vg_replace_malloc.c:1328)
==20872==    by 0x2DCB37: snmpv3_parse (snmp_api.c:3929) **pdu->securityEngineID = (u_char *) calloc(1, SNMP_MAX_ENG_SIZE * 2);**
==20872==    by 0x2DE243: _snmp_parse (snmp_api.c:4387)
==20872==    by 0x2DE96B: snmp_parse (snmp_api.c:4572)
==20872==    by 0x2E22C3: _sess_process_packet_parse_pdu (snmp_api.c:5674)
==20872==    by 0x2E2BBB: _sess_process_packet (snmp_api.c:5907)
==20872==    by 0x2E3857: _sess_read (snmp_api.c:6179)
==20872==    by 0x2E4687: snmp_sess_read2 (snmp_api.c:6452)
==20872==    by 0x2E2DC3: snmp_read2 (snmp_api.c:5967)
==20872==    by 0x2102EF: receive (snmpd.c:1379)
==20872==    by 0x20FC3F: snmpd_main (snmpd.c:1161)
==20872==    by 0x1F8B33: snm_main (SNM_task.c:126)
==20872==    by 0x4921F43: ??? (in /usr/lib/libpsos.so.0.0.0)
==20872==
==20872== 92,928 bytes in 363 blocks are definitely lost in loss record 1,435 of 1,450
==20872==    at 0x484C494: calloc (vg_replace_malloc.c:1328)
==20872==    by 0x2DCB5F: snmpv3_parse (snmp_api.c:3931) **"pdu->securityName = (char *) calloc(1, SNMP_MAX_SEC_NAME_SIZE);"**
==20872==    by 0x2DE243: _snmp_parse (snmp_api.c:4387)
==20872==    by 0x2DE96B: snmp_parse (snmp_api.c:4572)
==20872==    by 0x2E22C3: _sess_process_packet_parse_pdu (snmp_api.c:5674)
==20872==    by 0x2E2BBB: _sess_process_packet (snmp_api.c:5907)
==20872==    by 0x2E3857: _sess_read (snmp_api.c:6179)
==20872==    by 0x2E4687: snmp_sess_read2 (snmp_api.c:6452)
==20872==    by 0x2E2DC3: snmp_read2 (snmp_api.c:5967)
==20872==    by 0x2102EF: receive (snmpd.c:1379)
==20872==    by 0x20FC3F: snmpd_main (snmpd.c:1161)
==20872==    by 0x1F8B33: snm_main (SNM_task.c:126)
==20872==    by 0x4921F43: ??? (in /usr/lib/libpsos.so.0.0.0)

Thanks
