### ISSUE TITLE
Extend, No Data Returned as Service (Windows), and Perl Commands Timeout

### ISSUE THREAD

**Issue by arrmo** [net-snmp/net-snmp#421]
OK, pulling my hair out - and I can't spare that ... LOL! I'm building net-snmp v5.9.2.rc1 (though I also tried 5.9.1, same result), using the Native Tools Command Prompt for VS 2022, on Windows 11. Build and install all goes fine, and if I run snmpd with "Enabling the Windows SNMP extension agents" as a command, it works mostly fine. Command is,
```
snmpd -I-udp,udpTable,tcp,tcpTable,icmp,ip,interfaces,snmp_mib,system_mib,sysORTable
```
But if I register this command, run as a service ... extend functions (like `extend perl where perl`) don't provide and output string ... for example, the output is,
```
NET-SNMP-EXTEND-MIB::nsExtendOutLine."perl".1 = STRING:
```
But from the command line run, I get,
```
NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."perl" = STRING: C:\Users\micro\AppData\Local\activestate\cache\bin\perl.bat
```

So that's oddity 1 😆. The second odd thing, if I try to use extend with perl, for example (and command line, from above),
```
extend vers perl --version
```
It get a timeout error (from snmpwalk). Remove this extend, all good again.

Am I just crazy? 😜 

Thanks!

**Comment by bvanassche** [comment]
Building Net-SNMP with Visual Studio and combining it with a Perl interpreter built with gcc is no longer supported (recent versions of ActiveState Perl have been built with gcc). Please use the same compiler for both software packages. An example of how to download and build the Perl source code with Visual Studio is available in the `ci/perl.bat` batch file in the Net-SNMP source tree.

**Comment by arrmo** [comment]
Appreciate the pointer! Trying that batch file, but it's failing 😞. Perhaps I can run an older version of ActiveState Perl?

Open to suggestions, appreciate it!

**Comment by arrmo** [comment]
OK, digging a bit more - getting this error. Searching around, it seems common, but no real solution found? FYI, this is on Visual Studio Community 2022.
```
..\perlio.c(3627): error C2039: '_cnt': is not a member of '_iobuf'
```

Thanks!

**Comment by bvanassche** [comment]
Hmm ... which version of the Perl source code did you download? We use version 5.31.10 in the Net-SNMP continuous integration infrastructure.

**Comment by arrmo** [comment]
Hi, yes - the same here, 5.31.10. I ran across [this](https://stackoverflow.com/questions/31150635/build-error-in-visual-studio-in-perlio-h-and-iobuf) issue - did some searching to find it 😆.

Are you not seeing the same thing? I applied the noted "fix" (though I'm not sure of the implications of it 😞) - it does let the build proceed though, so that part is good. And you don't have to do this? FYI ,what I did was to copy over that noted file, and then undefine USE_STDIO_BASE and USE_STDIO_PTR.
```
perlio.c has multiple cases of trying to use FILE::_base and FILE::_ptr. These can be disabled by undefining USE_STDIO_BASE and USE_STDIO_PTR in config.h. (In a clean build config.h is generated by copying config_H.vc)
```

Perhaps it's related to the version of MSVC? I'm running "whatever" comes with VS 2022 Community (I admit, not sure I see where the exact version is, but I assumed / set MSVC142).

Thoughts?

Thanks!

**Comment by arrmo** [comment]
OK, I decided to try the latest version, 5.36 ... I change (uncomment) the CCTYPE row in the Makefile - and it fully builds, no issues at all! So seems 5.31 is too old?

Thanks!

**Comment by bvanassche** [comment]
Apparently Perl 5.31.10 cannot be built with Visual Studio 2015. It's great that Perl 5.36 builds fine.

As one can see in commit a8ea1e4aadc542aebda46a09258aec76f71b19e9, Net-SNMP now uses version 5.37.0 in its continuous integration tests.

**Comment by arrmo** [comment]
Excellent, thanks! I see it just changed, that works - appreciate it.

FYI, two side questions for you (hoping at least one may help 😜),
1. you mentioned that "Building Net-SNMP with Visual Studio and combining it with a Perl interpreter built with gcc is no longer supported (recent versions of ActiveState Perl have been built with gcc).". No issue at all, but where is this noted? It may be good to clearly capture this somewhere (which it may be, and I just missed it).
2. this one is very odd, but ... if I use extend in net-snmp, even a simple perl command like `perl --version` => it works (and I receive a correct response) when using the (Windows) service, but if I run snmpd from the command line (in a window where perl does work, confirmed!) ... net-snmp just times out, due to the extend function. Huh?!?! This one is a bit of a blocker, as it messes with test and debug.

Thanks again.

**Comment by bvanassche** [comment]
My answers to your questions are as follows:

1. Commit e769fa1ddef4598e801fe3377d1a526976d07b2a should make the build process stop if Perl has been built with gcc instead of Visual Studio. I'm not sure why that check did not get triggered.
2. This is unexpected and needs further attention.

**Comment by arrmo** [comment]
Thanks! Not sure I can say much on 1, but on 2 - any suggestions of how to debug? I can try to run manually, enable debugging ... post that for you to check?

**Comment by arrmo** [comment]
FYI, I did try adding an extend command than runs `whoami` ... the result is different in the two cases, but the problem case (command line) shows the user as my account, and if I run the Perl command it executes just fine. Hmmm.

Thanks!
