### ISSUE TITLE
Require OpenSource MIB OID details of net-snmp

### ISSUE THREAD

**Issue by PriyankaBoggarapu** [net-snmp/net-snmp#422]
Hi,

Do we have complete documentation how all the OIDs are reading the data from? 

Example:
lets say take IF-MIB, it is fetching the ifName from /proc/net/dev.

IF-MIB::ifName.1 = STRING: lo
IF-MIB::ifName.2 = STRING: ipsec0
IF-MIB::ifName.3 = STRING: sit0
IF-MIB::ifName.4 = STRING: ip6tnl0
IF-MIB::ifName.5 = STRING: Port1
IF-MIB::ifName.6 = STRING: Port2
IF-MIB::ifName.7 = STRING: Port3
IF-MIB::ifName.8 = STRING: Port4
IF-MIB::ifName.9 = STRING: ifb0
IF-MIB::ifName.11 = STRING: gre0
IF-MIB::ifName.12 = STRING: gretap0
IF-MIB::ifName.13 = STRING: erspan0
IF-MIB::ifName.14 = STRING: host0
IF-MIB::ifName.15 = STRING: host1
IF-MIB::ifName.16 = STRING: GuestAP
IF-MIB::ifName.19 = STRING: spq

Like this, do we have any indetailed documentation how all the below MIB tables are filling up the data from?

SNMPv2-MIB
IF-MIB
SNMPv2-SMI
IP-MIB
TCP-MIB
UDP-MIB
HOST-RESOURCES-MIB
DISMAN-EVENT-MIB
SNMP-FRAMEWORK-MIB
SNMP-MPD-MIB
SNMP-USER-BASED-SM-MIB
SNMP-VIEW-BASED-ACM-MIB

**Comment by bvanassche** [comment]
Closing this issue since this is a request for information while the purpose of the issue tracker is to track bugs.
