### ISSUE TITLE
net-snmp-create-v3-user write the clear text passwd(this may leak sensitive information) to the configuration file(snmpd.conf), can this be improved?

### ISSUE THREAD

**Issue by XWwalker** [net-snmp/net-snmp#423]

**Comment by hardaker** [comment]
The password is stored only temporarily in the file until the agent is run, after which it's overwritten with a localized hash that is much more restrictive.  Unfortunately, the password (or the derived master key which is equally as sensitive) must be known before localization.

The only solution would be to  have net-snmp-config create a localized key at the time it's run -- this should be possible but would require a new tool capable of generating that line within the net-snmp-config shell script.

**Comment by XWwalker** [comment]
First, please forgive me for not responding in a timely manner.
Thank you very much, I think it's a balanced approach. If in the future for me to have the ability to write such scripts, I think I can make some help.
I will close this issue until a better option is available.

**Comment by XWwalker** [comment]
Okay, I may not have permission to close this Issue.
Please help me to close this Issue if it is convenient.
