### ISSUE TITLE
make test failed because of autoconf version.

### ISSUE THREAD

**Issue by xiacunshun** [net-snmp/net-snmp#431]
When i try to make a test, I run into this:
`Checking the Net-SNMP configure script validity ......................... 
not ok 1 - found 0 copies of '^# Generated by GNU Autoconf 2.69 for Net-SNMP' in output (/builddir/build/BUILD/net-snmp-5.9.1/testing/fulltests/support/../../../configure); expected 1`
The autoconf I use is up to 2.71 while the dist/autoconf-version is always 2.69....
So, why the verison number is completely hardcoded? Will it be better if the version can be read dynamicly from the building env?

**Comment by bvanassche** [comment]
Does this mean that you are regenerating the configure script before building Net-SNMP? Has it been considered to use the configure script included in the Net-SNMP source tree?

**Comment by xiacunshun** [comment]
> Does this mean that you are regenerating the configure script before building Net-SNMP? Has it been considered to use the configure script included in the Net-SNMP source tree?

Yes.I found that I used `autoreconf` to regenerate the configure before building which will update the version number in dist/autoconf-verison.That's exactly the reason why this test failed.
I tried the configure script included in the source tree and the test process moves on successfully. thx.:)
