### ISSUE TITLE
zeroDotZero BER-Encoding of NULL name

### ISSUE THREAD

**Issue by pobinger** [net-snmp/net-snmp#435]
Trying to build an SNMP packet calling ``snmp_build(...)``, I put only one variable into ``variables`` of the SNMP PDU with ``name = NULL,`` and ``name_length = 0`` (variable binding for ``zeroDotZero``).

But instead of BER encoding this as ``0x06 01 00`` (as expected), netsnmp encoded it as ``0x06 02 00 00`` (which would be "zeroDotZero.0").

I suspect a problem is inside ``asn_realloc_rbuild_objid()``, because when checking for ``objidlength == 0``,  2 zero-initialized bytes are allocated in the packet.

```
        *(*pkt + *pkt_len - (++*offset)) = 0;
        *(*pkt + *pkt_len - (++*offset)) = 0;
 ```
 
IMHO, the second line above is too much, since the very first 2 parts of an id shall be encoded in the 2 nibbles of the first single byte in BER.

Workaround for me was to put a variable with ``name = "0"`` and ``name_length = 1`` in the PDU.

**Comment by bvanassche** [comment]
Thanks for having reported this. Please take a look at commit 4c1b37bbb193c3c8dcda2240ef86b8435b66283a.
