### ISSUE TITLE
SNMPv3 do not respond REPORT message if user engine ID is different than local engine ID.

### ISSUE THREAD

**Issue by inu1997** [net-snmp/net-snmp#441]
My PC:
```
snmpget -v 3 -n context -u user -l AuthPriv -a MD5 -A password1 -x DES -X password2 -e 0x8000033703XXXXXXXXXXXX XX.XX.XX.XX SOME_OID
```
and get timeout. There is no response from agent at all.

And then I tried the user which is created with local engine ID.
```
snmpget ... -e LOCAL_ENGINE_ID ...
```
My query task gets a **REPORT** message says **"not in time window."**
and then successfully queried the object in the second try.

I looked into the code.
@snmp_api.c:4130 snmpv3_make_report(...)
```
...
    SNMP_FREE(pdu->securityEngineID);
    pdu->securityEngineID =
        snmpv3_generate_engineID(&pdu->securityEngineIDLen);
    SNMP_FREE(pdu->contextEngineID);
    pdu->contextEngineID =
        snmpv3_generate_engineID(&pdu->contextEngineIDLen);
...
```
which replaced the engine ID with the local engine ID.
and then
@snmpusm.c: usm_get_user_from_list
```
...
    struct usmUser *ptr;
...
              memcmp(ptr->engineID, engineID, engineIDLen) == 0)))
            return ptr;
          DEBUGMSGTL(("usm", "no match on engineID ("));
          if (engineID) {
              DEBUGMSGHEX(("usm", engineID, engineIDLen));
          } else {
              DEBUGMSGTL(("usm", "Empty EngineID"));
          }
          DEBUGMSG(("usm", ")\n"));
...
```
It says "no match on engineID" and then there is no REPORT message for my query task.

My snmpd.conf:
```
...
engineIDType 3
EngineID 8000033703XXXXXXXXXXXX <- LOCAL_ENGINE_ID
...
...
createUser -e OTHER_ENGINE_ID user1 MD5 password1 DES password2
createUser -e LOCAL_ENGINE_ID user2 MD5 password1 DES password2
...
```

**Comment by inu1997** [comment]
I modified
snmpv3_make_report()
from
```
...
    SNMP_FREE(pdu->securityEngineID);
    pdu->securityEngineID =
        snmpv3_generate_engineID(&pdu->securityEngineIDLen);
    SNMP_FREE(pdu->contextEngineID);
    pdu->contextEngineID =
        snmpv3_generate_engineID(&pdu->contextEngineIDLen);
...
```
to
```
...
    if (!pdu->securityEngineID)
        snmpv3_generate_engineID(&pdu->securityEngineIDLen);
    if (!pdu->contextEngineID)
        snmpv3_generate_engineID(&pdu->contextEngineIDLen);
...
```
And now there is snmp REPORT message for my out_of_time_window query :)

**Comment by bvanassche** [comment]
Hmm ... shouldn't the value returned by snmpv3_generate_engineID() be stored somewhere? I think the change shown above causes a memory leak.

**Comment by inu1997** [comment]
> Hmm ... shouldn't the value returned by snmpv3_generate_engineID() be stored somewhere? I think the change shown above causes a memory leak.

Oops... I forgot! Sorry about that.
I've editted the above reply.

**Comment by bvanassche** [comment]
If I try that patch most unit tests fail (`ci/test.sh`).

**Comment by inu1997** [comment]
That's weird. My SNMP version is 5.4.
Maybe something changed?
Does not pdu passed to snmpv3_make_report come with an EngineID already?
Or does the latest version respond REPORT message no matter what the engineID is?

**Comment by bvanassche** [comment]
Net-SNMP v5.4 is no longer supported. Only bug reports and patches for the V5-9-patches and master branches are considered.

**Comment by inu1997** [comment]
> Net-SNMP v5.4 is no longer supported. Only bug reports and patches for the V5-9-patches and master branches are considered.

Well... I guess my SNMP is just too out-dated.
