### ISSUE TITLE
PR_SLOWHZ retired in FreeBSD-CURRENT

### ISSUE THREAD

**Issue by vishwin** [net-snmp/net-snmp#445]
The constant was removed/retired in freebsd/freebsd-src@1922eb3e9c23, so the build now fails:
```
mibgroup/mibII/tcp.c:343:33: error: use of undeclared identifier 'PR_SLOWHZ'
        ret_value = TCPTV_MIN / PR_SLOWHZ * 1000;
                                ^
mibgroup/mibII/tcp.c:351:38: error: use of undeclared identifier 'PR_SLOWHZ'
        ret_value = TCPTV_REXMTMAX / PR_SLOWHZ * 1000;
                                     ^
2 errors generated.
*** Error code 1
```

**Comment by arrowd** [comment]
The patch in a6153d721cf34d2a4f40c04fdea5136bc991fa80 doesn't solve the issue.

**Comment by bvanassche** [comment]
How to reproduce this issue? The Net-SNMP master branch builds fine in my FreeBSD 14-CURRENT VM.

**Comment by arrowd** [comment]
Yes, but the build was fixed by some other commit. I want to find out which one and pull it into our port, which builds 5.9.1 release.

Or maybe you'll make a new release containing this fix?

**Comment by bvanassche** [comment]
Has it been considered to use the 5.9.3 release as the basis for your port?

**Comment by arrowd** [comment]
Just tried it, the 5.9.3 release doesn't build with the same error:

```
mibgroup/mibII/tcp.c:343:33: error: use of undeclared identifier 'PR_SLOWHZ'
        ret_value = TCPTV_MIN / PR_SLOWHZ * 1000;
                                ^
mibgroup/mibII/tcp.c:351:38: error: use of undeclared identifier 'PR_SLOWHZ'
        ret_value = TCPTV_REXMTMAX / PR_SLOWHZ * 1000;
                                     ^
2 errors generated.
```

**Comment by vishwin** [comment]
This patch has not made it into any release, but it can be applied to at least 5.9.1 to 5.9.3.

Building on 14-CURRENT now fails with a different error (looks like another symbol retirement).

**Comment by bvanassche** [comment]
Please retest with the V5-9-patches branch.
