### ISSUE TITLE
snmptrapd on Alpine Linux has different outputOption

### ISSUE THREAD

**Issue by banjaxedben** [net-snmp/net-snmp#45]
When I test on Ubuntu, snmptrapd displays the varbind datatype.
Example:
`IF-MIB::ifPhysAddress.1 = STRING: 0:a:14:0:0:0`
i.e. The default outputOption is "S", which agrees with the docs (http://net-snmp.sourceforge.net/docs/man/snmpcmd.html)

But when I test on Alpine, with the same snmptrapd.conf file, there is no datatype information.
It seems to behave as though outputOption is "Q", no matter what I specify in the snmptrapd.conf file.

NET-SNMP version 5.8

**Comment by hardaker** [comment]
Is it possible that the alpine installation doesn't have access to the MIBs directory that defines ifPhysAddress datatypes?  If so, then it would fail to interpret the results properly.

**Comment by banjaxedben** [comment]
Thanks for the reply Wes.
On further investigation, I wasn't comparing like with like. There is no issue with the Alpine implementation.

But there is a different problem: it is _impossible_ to include the datatype information in the output to an external program, via the traphandle directive.
i.e. The output to stderr/stdout/etc. is different from the output to a traphandler.

For clarity I will close this issue and raise a new one.
I would appreciate it if you could take a look at it!
