### ISSUE TITLE
Pass_persist SET command formatted with an extra \n

### ISSUE THREAD

**Issue by MartySvec** [net-snmp/net-snmp#461]
Hello, 

since commit 9b9c0e287b4dd4619da3e3ca80e1832dc1c81699, SNMP pass_persist SET command is formatted with double `\n` at the end. This change breaks the pass_persist pipe protocol by an unexpected empty line after every SET. Please see https://github.com/net-snmp/net-snmp/commit/9b9c0e287b4dd4619da3e3ca80e1832dc1c81699#diff-4352101f88c0202efc92ec36fb13b58bf99a399be2ab27c5aa6af1689f87a9f8L366 . Indeed, one `\n` is added in `netsnmp_internal_pass_set_format()` and another one `\n` is added by `asprintf(&persistpassthru->command, "set\n%s\n%s\n", buf, buf2)`. The original code added second `\n` at a fixed position at the end of the buffer, so in most cases this extra `\n` had no effect. IMO it should be sufficient to change asprintf formatting string to `"set\n%s\n%s"`.

Regards,
Martin

**Comment by bvanassche** [comment]
Thank you for the detailed report. Does the patch mentioned above fix this issue?

**Comment by MartySvec** [comment]
Yes, the path fixes it, thank you.
