### ISSUE TITLE
Segfault: when a PEM file is read containing only a key, we segfault while printing debug

### ISSUE THREAD

**Issue by minfrin** [net-snmp/net-snmp#463]
If a file ending in the suffix .pem is placed underneath /etc/snmp/tls, and this file contains no certificates, just a key, we crash on this line:

https://github.com/net-snmp/net-snmp/blob/master/snmplib/cert_util.c#L1413

The debug assumes a certificate has previously been parsed, and tries to print the filename. Variable cert is NULL, so crash.

**Comment by bvanassche** [comment]
Is commit 7233ec6a4b15d3281e7a700c84aeee81f2897d0f sufficient to fix this issue?
