### ISSUE TITLE
snmpwalk not returning correct value on SLES15 when memory is large

### ISSUE THREAD

**Issue by tuaaldf** [net-snmp/net-snmp#472]
Having a  problem with our Logic Monitoring tool.  The memory usage is negative. 
According to Logic Monitor, the OID's are returning incorrect values.
Please see below for their explanation.

In addition, we have validated that the output of the snmpwalk does NOT return the correct value, but only when memory values are very large (in this case 5TB).

There seemed to be a bug fix for RHEL regarding the same issue.  Wanted to know if there's a similar fix for SUSE linux?

Please advise if you need additonal information.

From the Logic Monitor Support team:
=========================

I have taken a closer look and the Devices are returning incorrect values for the OID's being called by the datasource. It appears to be reversed values, but I can't say for sure, Your admins would need to verify that, The issue is with the SNMP on the devices. Your Linux admins should be able to identify and resolve the issue. I have included links and information below to the OID.s and what they should be reporting.

If you can't resolve the issue for some reason, you can clone the datasource and alter the script to reverse the OID's if they are, in fact, reversed. and apply it only to the affected resources. This is not ideal, but I offer it as a workaround if needed.

Please let me know if you have any question. 

Thank you

Testing results and information.

Using sappr01 and compared to sappr01a that is reporting correctly.

.1.3.6.1.4.1.2021.4.5.0 should return the values of all the ram installed in the device. But returns the used memory.

.1.3.6.1.4.1.2021.4.6.0 Should return the values of the free memory (available) But returns total memory

Your devices are returning the values that reverse of the expected values. 

Here is the raw polling of each OID from the collector 

$ !snmpget 10.134.193.12 1.3.6.1.4.1.2021.4.5.0

Getting OID 1.3.6.1.4.1.2021.4.5.0 from 10.134.193.12:161 for version v2c with community=**** timeout=5s

   1.3.6.1.4.1.2021.4.5.0 => 1466299072

$ !snmpget 10.134.193.12 1.3.6.1.4.1.2021.4.6.0

Getting OID 1.3.6.1.4.1.2021.4.6.0 from 10.134.193.12:161 for version v2c with community=**** timeout=5s

   1.3.6.1.4.1.2021.4.6.0 => 2599566144

now we do apply math to this as follows to give you the percentage and I verified the math is correct and with revered values, would be what, I think, is expected. 

ActiveMemoryPercent = ((TotalReal - AvailReal - Cached)/TotalReal*100)

       UsedMemory = (TotalReal - AvailReal - Cached)

I also ran the same test on sappr01a to show that we are using the same OID's but getting correct values.

!snmpget 10.134.193.30 1.3.6.1.4.1.2021.4.5.0

agent has fetched the task, waiting for response

Getting OID 1.3.6.1.4.1.2021.4.5.0 from 10.134.193.30:161 for version v2c with community=**** timeout=5s

   1.3.6.1.4.1.2021.4.5.0 => 133807744

$ !snmpget 10.134.193.30 1.3.6.1.4.1.2021.4.6.0

agent has fetched the task, waiting for response

Getting OID 1.3.6.1.4.1.2021.4.6.0 from 10.134.193.30:161 for version v2c with community=**** timeout=5s

   1.3.6.1.4.1.2021.4.6.0 => 8613632

=================================

One of my colleagues found this article, which did find a bug in the RHEL version.  He thinks this could be the same case in SUSE.

https://access.redhat.com/solutions/4784781

In the RHEL article, under root cause, there is a link (upstream).  It shows you where in the code the error lies.  

Do you know where this file would be in SUSE?  We were curious to take a look at the source code.
===============================

FROME THE SERVER:

sappr01:/etc/snmp # snmpbulkwalk -v2c -c M3Gsnmp4U 127.0.0.1 .1.3.6.1.4.1.2021.4

UCD-SNMP-MIB::memIndex.0 = INTEGER: 0

UCD-SNMP-MIB::memErrorName.0 = STRING: swap

UCD-SNMP-MIB::memTotalSwap.0 = INTEGER: 2097088 kB

UCD-SNMP-MIB::memAvailSwap.0 = INTEGER: 2096000 kB

UCD-SNMP-MIB::memTotalReal.0 = INTEGER: 1466297216 kB   <------ This is NOT correct

UCD-SNMP-MIB::memAvailReal.0 = INTEGER: 3410183616 kB

UCD-SNMP-MIB::memTotalFree.0 = INTEGER: 3412279616 kB

UCD-SNMP-MIB::memMinimumSwap.0 = INTEGER: 16000 kB

UCD-SNMP-MIB::memShared.0 = INTEGER: 15569728 kB

UCD-SNMP-MIB::memBuffer.0 = INTEGER: 7296 kB

UCD-SNMP-MIB::memCached.0 = INTEGER: 74524736 kB

UCD-SNMP-MIB::memTotalSwapX.0 = Counter64: 2097088 kB

UCD-SNMP-MIB::memAvailSwapX.0 = Counter64: 2096000 kB

UCD-SNMP-MIB::memTotalRealX.0 = Counter64: 5761264512 kB   <----------- this is correct

UCD-SNMP-MIB::memAvailRealX.0 = Counter64: 3410183616 kB

UCD-SNMP-MIB::memTotalFreeX.0 = Counter64: 3412279616 kB

UCD-SNMP-MIB::memMinimumSwapX.0 = Counter64: 16000 kB

UCD-SNMP-MIB::memSharedX.0 = Counter64: 15569728 kB

UCD-SNMP-MIB::memBufferX.0 = Counter64: 7296 kB

UCD-SNMP-MIB::memCachedX.0 = Counter64: 74524736 kB

UCD-SNMP-MIB::memSwapError.0 = INTEGER: noError(0)

UCD-SNMP-MIB::memSwapErrorMsg.0 = STRING:

sappr01:/etc/snmp # cat /proc/meminfo

MemTotal:      5761264512 kB

MemFree:       3412726208 kB

MemAvailable:  3456605824 kB

Buffers:           7296 kB

Cached:        74544320 kB

SwapCached:           0 kB

Active:        2275304512 kB

Inactive:      63193152 kB

Active(anon):  2267329024 kB

Inactive(anon): 12237568 kB

Active(file):   7975488 kB

Inactive(file): 50955584 kB

Unevictable:     312320 kB

Mlocked:         312320 kB

SwapTotal:      2097088 kB

SwapFree:       2096000 kB

Dirty:             2880 kB

Writeback:            0 kB

AnonPages:     2264267008 kB

Mapped:        16463872 kB

Shmem:         15577792 kB

KReclaimable:   4598848 kB

Slab:           7298176 kB

SReclaimable:   4598848 kB

SUnreclaim:     2699328 kB

KernelStack:      66144 kB

PageTables:      876480 kB

NFS_Unstable:         0 kB

Bounce:               0 kB

WritebackTmp:         0 kB

CommitLimit:   2882729344 kB

Committed_AS:  2439099776 kB

VmallocTotal:  549755813888 kB

VmallocUsed:     845248 kB

VmallocChunk:         0 kB

Percpu:          430080 kB

HardwareCorrupted:    0 kB

AnonHugePages:        0 kB

ShmemHugePages:       0 kB

ShmemPmdMapped:       0 kB

CmaTotal:      20971520 kB

CmaFree:       20971520 kB

HugePages_Total:      0

HugePages_Free:       0

HugePages_Rsvd:       0

HugePages_Surp:       0

Hugepagesize:     16384 kB

Hugetlb:              0 kB

**Comment by fenner** [comment]
The values that Logic Monitor are polling are 32-bit integers, meaning that they can not possibly represent the value once it gets too high.  This is why the memTotalRealX was introduced: to allow reporting memory amount greater than what can be represented in 32 bit values.  It's similar to needing to use `ifHighSpeed` for interfaces faster than 2Gbps.

Logic Monitor should change to poll the 64-bit values.

**Comment by tuaaldf** [comment]
Thank you Bill, appreciate your time and support.  I will advise Logic Monitor.
