### ISSUE TITLE
AES256 length constant missing (net-snmp 5.8)

### ISSUE THREAD

**Issue by razabc** [net-snmp/net-snmp#48]
Hello,

`oid usmAES256PrivProtocol[9]` is defined in _transform_oids.h_ (using `--enable-blumenthal-aes` flag).
However, a constant for its OID length (9) is missing.

Just like there's `#define USM_PRIV_PROTO_AES_LEN 10` for `oid usmAESPrivProtocol[10],` I'd expect to see something like `#define USM_PRIV_PROTO_AES256_LEN 9` for `oid usmAES256PrivProtocol[9]` .

What am I missing?

Thanks.

**Comment by hardaker** [comment]
The other ones are there for backwards compatibility (see the note above them, eg).  Generally its recommended you should use the `OID_LENGTH` macro instead: `OID_LENGTH(usmAES256PrivProtocol)`.  Is there a particular reason you need the `#define` version and the recommended above macro won't work for you?

**Comment by razabc** [comment]
There's no particular reason I need the `#define` version. I could use the macro.

Thanks for clarifying.

**Comment by hardaker** [comment]
FYI, the OID_LENGTH macro is handled at compile time, so it it is literally calculating the same answer at compile time and incurs no run-time overhead.
