### ISSUE TITLE
snmptrap sends wrong engineBoots/engineTime values

### ISSUE THREAD

**Issue by vardan** [net-snmp/net-snmp#499]
Hello,

I am experiencing following issue with `snmptrap`:
even after successful timeliness alignment between agent and the manager, `snmptrap` is sending traps with wrong engineBoots and engineTime. Both have 0 values, regardless previous negotiation between agent and manager. Any attempt to explicitly provide these in snmptrap command using -Z option do not work. Clearly `snmpd` is able to align engineTime/Boots, but `snmptrap` is ignoring it. Can you guide me where the issue could be?

**Comment by vardan** [comment]
Manager starts discovery:
![image](https://user-images.githubusercontent.com/1768673/207816704-69801044-90c2-40fd-85cc-47fa820daa50.png)

Agent replies with its engineID and engineBoots/Time values:
![image](https://user-images.githubusercontent.com/1768673/207816830-4fcb455b-d67e-4b15-8b22-2344371cad90.png)

Manager learns agents engineID:
![image](https://user-images.githubusercontent.com/1768673/207817268-aeebc846-1223-49fa-9a0c-7b3e425eb0bf.png)

snmptrap is sent with both engineTime/Boots set to 0:
![image](https://user-images.githubusercontent.com/1768673/207817546-86245d14-650c-4ffe-8b4b-0ecbc4fa73fa.png)

Manager sends a report usmStatsNotInTimeWindows. And later attempts a discovery again

**Comment by vardan** [comment]
Fixed by using a later version of libsnmp40

**Comment by iyyapa** [comment]
Can you please help us to share the RCA and fix details
