### ISSUE TITLE
Deleting initial users not possible.

### ISSUE THREAD

**Issue by rms95** [net-snmp/net-snmp#504]
I am creating a custom agent, in which I have an InitialUser which is used to setup SNMP:
```
createUser InitialUser MD5 InitialUser
rwuser InitialUser authNoPriv .1
```
This user is intended to setup other users, and then be deleted.
In my custom agent I supply a conf file, containing the above, via:
```c
netsnmp_ds_set_string(NETSNMP_DS_LIBRARY_ID, NETSNMP_DS_LIB_OPTIONALCONFIG, "/path/to/above/snmp.conf");
```

Now, when I delete the user runtime (`snmpusm -v 3 -l authNoPriv -u InitialUser -a MD5 -A InitialUser [localhost]:161 delete InitialUser`), the user is gone, as expected. Also, when running the command again it reports "snmpset: Unknown user name", also as expected. When I now stop the snmp agent, the user indeed is NOT in the persistent file of the agent.

However, after a restart of the agent, the deleted user is back again, and also re-added to the persistent file of the agent.

### Steps to reproduce
The same happens with snmpd, and is easily reproducible:
1. Add the configuration above to `/etc/snmp/snmpd.conf` and start snmpd (`sudo service snmpd start`)
2. Check out ther persistence file `/var/lib/snmp/snmpd.conf`; The InitialUser will be in there.
3. Delete the user using `snmpusm -v 3 -l authNoPriv -u InitialUser -a MD5 -A InitialUser [localhost]:161 delete InitialUser`
4. Stop the agent using `sudo service snmpd stop`
5. Check out `/var/lib/snmp/snmpd.conf`; The InitialUser will be removed there.
6. Now start the agent again; `sudo service snmpd start`
7. The user is back.

Is this intended behavior? What would be a proper way of handling this situation?

**Comment by hardaker** [comment]
The user is back because it is re-reading your config file in `/path/to/above/snmp.conf`, per your API call.  The right place to put initial user creation lines is actually to [after shutting the agent down] put them in the persistent file `/var/lib/snmp/snmpd.conf`, and they'll be properly maintained and removable.
