### ISSUE TITLE
net-snmp.org is down (2023-01-04)

### ISSUE THREAD

**Issue by GwynethLlewelyn** [net-snmp/net-snmp#505]
Apparently, the name resolver for `www.net-snmp.org` is down (at the time of writing this, of course). Attempting to resolve names via either Google's or Cloudflare's public DNS servers fail:

```bash
$ dig @8.8.8.8 www.net-snmp.org a

; <<>> DiG 9.10.6 <<>> @8.8.8.8 www.net-snmp.org a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 59215
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;www.net-snmp.org.              IN      A

;; Query time: 561 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Wed Jan 04 14:03:09 WET 2023
;; MSG SIZE  rcvd: 45

$ dig @1.1.1.1 www.net-snmp.org a

; <<>> DiG 9.10.6 <<>> @1.1.1.1 www.net-snmp.org a
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 22161
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
; OPT=15: 00 09 6e 6f 20 53 45 50 20 6d 61 74 63 68 69 6e 67 20 74 68 65 20 44 53 20 66 6f 75 6e 64 2066 6f 72 20 6e 65 74 2d 73 6e 6d 70 2e 6f 72 67 2e ("..no SEP matching the DS found for net-snmp.org.")
; OPT=15: 00 16 61 74 20 64 65 6c 65 67 61 74 69 6f 6e 20 6e 65 74 2d 73 6e 6d 70 2e 6f 72 67 2e ("..at delegation net-snmp.org.")
; OPT=15: 00 17 36 38 2e 37 38 2e 37 32 2e 31 37 3a 35 33 20 72 63 6f 64 65 3d 53 45 52 56 46 41 49 4c20 66 6f 72 20 77 77 77 2e 6e 65 74 2d 73 6e 6d 70 2e 6f 72 67 20 41 ("..68.78.72.17:53 rcode=SERVFAILfor www.net-snmp.org A")
;; QUESTION SECTION:
;www.net-snmp.org.              IN      A

;; Query time: 1529 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Wed Jan 04 14:03:56 WET 2023
;; MSG SIZE  rcvd: 188
```

Note: actual nameservers are:

    Name Server: nsw.net-snmp.org
    Name Server: ns1.rollernet.us
    Name Server: ns2.rollernet.us

None of the above reply, either (`nsw.net-snmp.org` naturally cannot even be located), and queries for any other DNS record (SOA, NS, etc.) also fail, of course.

The domain seems to have been registered with DreamHost (excellent choice, btw!), which is [up and running](https://www.dreamhoststatus.com/), and currently co-located with Rollernet, which is also [fully operational](https://www.rollernetstatus.com/).

The domain name itself is duly paid for until the end of 2023:

```bash
$ whois net-snmp.org
Domain Name: net-snmp.org
Registry Domain ID: 286f59fb10ed486684231c2515ffd9bd-LROR
Registrar WHOIS Server: http://whois.dreamhost.com
Registrar URL: http://www.dreamhost.com/
Updated Date: 2022-11-05T08:05:48Z
Creation Date: 2000-12-01T16:46:57Z
Registry Expiry Date: 2023-12-01T16:46:57Z
Registrar: DreamHost LLC
[...]
```

My apologies for raising the issue here, but, alas, I don't have any other contact (it's probably on the page itself...).

Feel free to close this issue as soon as the nameservers start to respond again!

---

**Feature suggestion:** join Cloudflare (disclaimer: I'm not affiliated with them, just a happy user). Their basic services are free, and at the very least, you get rock-solid DNS performance (and a nice backoffice for registering everything), a certain degree of protection against intruder attacks (which runs on their servers, not yours, so you don't get any performance penalties that way), an HTTPS front-end (Cloudflare can contact your website via HTTP, but the 'external world' will just see their front-ends and their valid certificates, and you can force all links to be automatically upgraded to HTTPS, transparently, without any coding), and, of course, a globally distributed CDN/reverse proxy cache that requires zero configuration on the website itself (no plugins needed, no JavaScript snippets, no downloads, no code changes, nothing, zilch, nada). As a bonus, you can even have Cloudflare present a Wayback Machine page for your website if it is down — so, at the very least, even if your _server_ is down, your visitors will see _something_.

It's just a thought. It's free, as said, and the only thing that is required is to let their nameservers host your DNS records — all else is done automatically. If you get tired of paying DreamHost for the domain name, you can optionally use Cloudflare as your registrar, too (that's not their core business, so they resell domain names dirt cheap). But all that is easily reversable at will, if you decide, in the future, to go back to your original setup. It's worth a try :) I did that, a decade ago or so, and never regretted the choice for a single instant — and I've got all my websites there except one :)

**Comment by hardaker** [comment]
Grr....  Turns out that after a power failure of the primary server it didn't come back up to a good state (and I need to set up an external monitor for the name, as the internal one was ok bound to a different address).  It should be functional now.

Thanks for the suggestion of CloudFlare, but I'll politely decline.  I'm a fan of much of their work and am close associates with many of their excellent engineers, but I'm not likely to switch to using them for any reason.  But when considering things like this, we should separate out web hosting/fronting from DNS.  Note that the web site is currently sourceforge directly, though we've talked about switching it to github.io -- but the problem there is the wiki.  I've been, coincidentally, thinking about revamping the website and switching to github.io with at least a redirect or something to the SF mediawiki installation.  We've talked about switching away from mediawiki, but it turns out to be a big pain to convert content [especially when a lot of templates have been used like we have].

**Comment by hardaker** [comment]
[oh -- dreamhost for the main net-snmp.org page is really just an HTML redirect to SF's www version]

**Comment by GwynethLlewelyn** [comment]
Thanks for the quick fix! It's certainly back up again.

As for the future, well, I'm sure you will find a solution for everything, according to your wishes (and best practices).

I love MediaWiki too, and I totally understand the reason for not wishing to convert it to something else! Neither Sourceforge's, nor GitHub's Wiki come close to the kind of flexibility that MediaWiki has, and the kind of things you can do with templates, well... it's hard to replace those in any other environment. Especially now that MediaWiki has direct Lua support as an extension...

**Comment by hardaker** [comment]
I actually love mediawiki too in general, but it's harder than average to use, doesn't have native git support for offline editing, etc.  There is no perfect.

I'm also tempted to host the wiki somewhere else under a different name (wiki.net-snmp.org with redirects to get there).  Half the problem is that sourceforge is, um, less than ideal to work with for hosting web content.

**Comment by GwynethLlewelyn** [comment]
Well, the GitHub wiki works reasonably well, too... you can certainly publish to it via Git... but, of course, it means no templates/scripting whatsoever, and replacing WikiSyntax with GitHub-Flavoured Markdown :) Personally, I hate the WikiSyntax with a passion — as much as I love the platform itself — and I'm rather fond of Markdown myself, but I have found that the GitHub Wiki is far from perfect. It's 'adequate' at most, quite minimalistic, and hard to navigate (from the perspective of a visitor, of course). Alas!... it works well enough as a quick & dirty solution. And you can, to a degree, convert from a Sourceforge-based Wiki to a GitHub-based one. You might need to do some search & replace on the paths (if you have cross-references within the wiki pages) before publishing it on GitHub, but it's not really hard to do.

From MediaWiki to GitHub is another story!... but fortunately [someone has at least provided a migration script](https://github.com/outofcontrol/mediawiki-to-gfm) — I've never tested it myself, but it should work, I guess!

**Comment by GwynethLlewelyn** [comment]
> I've never tested it myself, but it should work, I guess!

... correction: I've just tested it, and it sort of works! It relies on [`pandoc`](https://pandoc.org/) to do the burden of the conversion (which works to a degree), as well as on the patience of a human to add _all_ categories to be exported to XML from a MediaWiki installation (a built-in functionality). But it certainly works...
