### ISSUE TITLE
snmpd return service startup time not system

### ISSUE THREAD

**Issue by Tsvetk** [net-snmp/net-snmp#509]
> systemctl restart snmpd.service

> uptime
 23:20:49  up  12:25,  1 user,  load average: 0.04, 0.07, 0.08

> snmpget -c public -v 2c localhost sysUpTimeInstance
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (5067) 0:00:50.67

NET-SNMP version: 5.9.3

**Comment by bvanassche** [comment]
I think this behavior is compliant with the definition of `sysUpTime` in https://www.rfc-editor.org/rfc/rfc3418.

**Comment by fenner** [comment]
Bart is correct; this is expected behavior. You may be interested in
HOST-RESOURCES-MIB::hrSystemUptime.

  Bill
