### ISSUE TITLE
Windows 64bit support?

### ISSUE THREAD

**Issue by xzzh999** [net-snmp/net-snmp#52]
Hi~  
Greate work!
Is the 5.8 version support win64?  if not is there a plan to do so?

**Comment by bvanassche** [comment]
The github issue tracker is a bug tracker. Please submit questions to one of the Net-SNMP mailing lists [http://www.net-snmp.org/support/mailinglists.html](http://www.net-snmp.org/support/mailinglists.html). Anyway, to answer your question: 64-bit support for Windows has been added many years ago.
