### ISSUE TITLE
Question about netsnmp_set_mib_directory

### ISSUE THREAD

**Issue by Flow86** [net-snmp/net-snmp#530]
Hi,

I wanted to add a MIB directory per code in my own application, but was unable to do so, since `netsnmp_set_mib_directory` is not dll-exported on windows build.

My question is:
- Is there a specific reason why `netsnmp_set_mib_directory` is not exported, but `netsnmp_get_mib_directory` is?
- Should it be exported?
- There is a `add_mibdir` which is exported, but I didnt get that to work to find my mibs. Neither before/after calling `init_snmp`

**Comment by hardaker** [comment]
IMHO, it makes sense to have it exported in my mind.

**Comment by Flow86** [comment]
I've opened a PR for this "microfix": https://github.com/net-snmp/net-snmp/pull/534
