### ISSUE TITLE
snmpbulkwalk.1 mentions snmpbulkget instead of snmpbulkwalk

### ISSUE THREAD

**Issue by csmall** [net-snmp/net-snmp#537]
Very minor manpage issue where the wrong utility is mentioned.

In **snmpbulkwalk.1**:
>  Note that **snmpbulkget** REQUIRES an argument specifying the agent to query and at most one OID argument, as described above.

[bulkwalk_patch.txt](https://github.com/net-snmp/net-snmp/files/10857643/bulkwalk_patch.txt)

Reference: [Debian #1032139](https://bugs.debian.org/1032139)

**Comment by bvanassche** [comment]
The patch author information is missing from the bulkwalk_patch.txt file. Can you please convert that patch into a pull request?

**Comment by hardaker** [comment]
fixed in 1efe6dfbd
