### ISSUE TITLE
Any pnams to release new version?

### ISSUE THREAD

**Issue by kloczek** [net-snmp/net-snmp#550]
https://github.com/net-snmp/net-snmp/compare/v5.9.3...V5-9-patches shows 45 commits since last reease.
it would be really good to flush tose changes and release new 5.9.4.

BTW is it any plan to make  the new major release soon as well and/what is the plan what needs to be done in that version? 🤔
(I'm asking because I ccannot find any comments anywhere about that)

**Comment by hardaker** [comment]
I was actually hoping to push the first pre-release for 5.9.4 last week as we've been talking about it, but the IETF was far busier for me than normal (and I seem to have a tradition of pushing them near or during IETFs, where SNMP was defined).  I'll push the first one out this week.

We don't have firm date plans for a major branch release, but agreed that it should likely follow soon after a stable branch release.

**Comment by kloczek** [comment]
Is it anything still on pstanding list before release 5.9.4? 🤔

**Comment by hardaker** [comment]
there is still submitting new patches so yes.  I was going to release 5.9.4.pre2 this week.

[note that after that will be an RC phase]

**Comment by hardaker** [comment]
It's out: https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.4/

**Comment by kloczek** [comment]
Thank you 👍 😄 
Just updated my package and looks like it builds correctly.

**Comment by Whinegum** [comment]
Thanks for the announcement!

One question regarding the release notes:
It is mentioned that there is a known issue regarding TLS/DTLs in this new release. It is possible to get more information regarding this topic? E.g. what is the impact and can I easily figure out if "my" combination of netsnmp and openssl is also affected?
