### ISSUE TITLE
Kernel change from -EINVAL to -ENETUNREACH

### ISSUE THREAD

**Issue by jridky** [net-snmp/net-snmp#564]
Hi,

when sending an SNMP request to a broadcast address like 10.0.0.255 (in a /24 network), snmpd returns nothing and outputs following:   snmpd[xxxx]: send response: Failure in sendto

From further investigation it seems kernel changed its behavior ([Kernel patch](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=595e0651d029)) so sendmsg() now returns ENETUNREACH instead of EINVAL for broadcast addresses.

Would you agree, that simple switch from EINVAL to ENETUNREACH in affected file below would resolve the issue?

https://github.com/net-snmp/net-snmp/blob/4b4527a4a53a66c8e62ec5e9ae156c9a9f8e8606/snmplib/transports/snmpUDPBaseDomain.c#L318

What are your thoughts on this?

**Comment by bvanassche** [comment]
How about checking two error codes instead of only one in snmpUDPBaseDomain.c such that we do not break users with an older kernel version?

**Comment by fenner** [comment]
Doing the special behavior will also affect a case where the network is actually unreachable, right?  E.g., you don't have a default route in your routing table?  Is that OK?  (Presumably the second send will also fail in that case, which is probably fine.)
