### ISSUE TITLE
UCD-SNMP-MIB::dskTable - Ubuntu server 22.04.2

### ISSUE THREAD

**Issue by ManchiMe** [net-snmp/net-snmp#584]
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy

Package: snmpd
Version: 5.9.1+dfsg-1ubuntu2

the branch does not exist
.1.3.6.1.4.1.2021.9

snmpwalk -v 2c -c public 127.0.0.1  .1.3.6.1.4.1.2021.9
UCD-SNMP-MIB::dskTable = No Such Object available on this agent at this OID

**Comment by nielsb** [comment]
Have you configured it, using _includeAllDisks_ or individual _disk_ directives in snmpd,conf?
See _man snmpd.conf_ for details.
