### ISSUE TITLE
Enabling/Disabling cache timer

### ISSUE THREAD

**Issue by Achpile** [net-snmp/net-snmp#588]
Good day!

Im working with cache handling and trying to find a way to change the cache timeout. Like so:

```
int cache_load(netsnmp_cache *cache, void *magic) {
	netsnmp_cache_timer_stop(cache);
	cache->timeout = <value>;
	netsnmp_cache_timer_start(cache);
}
```

But it does not register new alarm in `netsnmp_cache_timer_start`, because `cache->timer_id` holds old value of unregistered timer after calling `netsnmp_cache_timer_stop`.

Is it a bug or do I have to manually set `cache->timer_id` to `0` ?

https://github.com/net-snmp/net-snmp/blob/50da1362e52092a253371b173dbacbbfff7d917c/agent/helpers/cache_handler.c#L323

```
    if(0 != cache->timer_id) {
        snmp_log(LOG_WARNING, "cache has existing timer id.\n");
        return cache->timer_id;
    }
```

Thanks.

**Comment by nielsb** [comment]
To me it looks like a bug, and netsnmp_cache_timer_stop should clear the timer_id after calling snmp_alarm_unregister.
