### ISSUE TITLE
linux vrf support in 5.9

### ISSUE THREAD

**Issue by VicLiuV** [net-snmp/net-snmp#593]
hi：
I'm using SNMPD version 5.9 and I had an issue with VRF and then saw this patch 《#1376 Linux VRF》.So, I was wondering if there was a patch like this <linux-vrf-5.8.0.patch> in snmpd 5.9. 
Thanks.

**Comment by nielsb** [comment]
This was applied for 5.8.1, and as such is also available in the 5.9 releases.
