### ISSUE TITLE
GPG signing key location

### ISSUE THREAD

**Issue by abergmann** [net-snmp/net-snmp#595]
I was testing `net-snmp-5.9.4.rc1` and noticed that it was signed with a new signing key, that replaced the previous one that expired last year (2022-10-28).

The new key has the ID: `EDDSA key 6E6718AEF1EB5C65C32D1B2A356BC0B552D53CAB`

Unfortunately I cannot find the public location of this new key, as it is not present on sourceforge.net inside the [current-key/](https://sourceforge.net/projects/net-snmp/files/net-snmp-admin%20PGP%20key/current-key/) directory. I was also not able to located it somewhere else.

**Comment by hardaker** [comment]
The signing key is published to the MIT server and (now) in the current-key directory on the SF file server too.
