### ISSUE TITLE
Misleading error message for SQLite RPM db based systems

### ISSUE THREAD

**Issue by jridky** [net-snmp/net-snmp#596]
Hi,

starting from RPM 4.16 the SQLite support is available for RPM DB. After https://fedoraproject.org/wiki/Changes/Sqlite_Rpmdb, rpm changed from Berkeley DB to SQLite. SNMP is using these hard coded paths [1] to determine where RPM info is, so it is trying to search for /var/lib/rpm/Packages and if the system is running on SQLite DB for RPM it fails with the following error

```Can't find directory of RPM packages```

This should be handled as both options are possible in theory (depends on the system).

Question: Does it even make sense to keep this init check once no info is pulled from /var/lib/rpm/Packages directly, but everything is obtained via RPM API?

What do you think?

Regards 
Josef

[1] https://github.com/net-snmp/net-snmp/blob/master/agent/mibgroup/host/data_access/swinst_rpm.c#L82

**Comment by nielsb** [comment]
This is used as a "cheap" way to check for updates to tha packages, and therefore invalidate the cache.
Is there an official way to check for package updates?
/Niels

**Comment by jridky** [comment]
If I am not mistaken, in that specific file there is no cache invalidation at all and even with the db file path created there (nor anywhere else) is operated. Is it possible that this is some kind of code residue from other platforms? The cache is invalidated every 30 seconds anyway (https://github.com/net-snmp/net-snmp/blob/master/agent/mibgroup/host/hrSWInstalledTable.c#L118)

Either way I've tested current code on Fedora 38 and due of auto invalidation I receive correct data every time I ask for them. But I'll check with RPM authors about check for package updates anyway.

**Comment by jridky** [comment]
So the simplest way to solve this could be by adding check for ```/var/lib/rpm/rpmdb.sqlite``` file if exists.

That would eliminate the log message and keep the current functionality basically intact.

**Comment by jridky** [comment]
@nielsb @bvanassche may I ask for review?
