### ISSUE TITLE
linux: IF-MIB Counters (HwIfInOctets, HwIfOutOctets, etc.) became 32-bit counters

### ISSUE THREAD

**Issue by stannous** [net-snmp/net-snmp#6]
Recently, patch 64f4ead817c4c0 (libsnmp: Only include <inttypes.h> when necessary)
effectively remove inttypes.h for and added it back for most files except for

if-mib/data_access/interface_linux.c

This had the effect of turning what were 64 bit counters (SCNuMAX is no longer defined)
into 32 bit counters.

**Comment by stannous** [comment]
There is a simple fix and I opened https://github.com/net-snmp/net-snmp/pull/7
for this.

**Comment by bvanassche** [comment]
Please either submit a pull request or report an issue instead of doing both. Anyway, since the submitted patch has been applied I'm closing this issue.
