### ISSUE TITLE
I get 5.9.1 version when i compile and install the 5.9.4.rc1 version.. Help

### ISSUE THREAD

**Issue by thebrainiak** [net-snmp/net-snmp#604]
Hi,

When i compile and install snmp 5.9.4.rc1 it installs the 5.9.1 version..
I download the zip, i make a ./configure, next "make" , and finally "make install", everything seems ok, but the version i get when i install it is 5.9.1. (Previusly i uninstalled and purged the version that i had before)

result of /.configure

![image](https://github.com/net-snmp/net-snmp/assets/101867702/a752bd14-20b8-4467-b030-153f83f21def)

result of make  (no errors)
![image](https://github.com/net-snmp/net-snmp/assets/101867702/46961df8-632d-46d3-b5cb-fe8bf2ebe885)

result of make install (no errors)
![image](https://github.com/net-snmp/net-snmp/assets/101867702/1a19f7f2-a41b-483a-84aa-0bb0b88c553c)

And finally the version i get..
![image](https://github.com/net-snmp/net-snmp/assets/101867702/c0210ca9-9846-47b7-a0c0-05ace23097a7)

Need help please, thank you!

**Comment by nielsb** [comment]
You must have some old version lying around still. Are you sure /usr/local/sbin/ is first in your search path?
what is the output from "which snmpd"?
What is the output from "ldd `which snmpd`"?

**Comment by thebrainiak** [comment]
> You must have some old version lying around still. Are you sure /usr/local/sbin/ is first in your search path? what is the output from "which snmpd"? What is the output from "ldd `which snmpd`"?


which snmpd:

![image](https://github.com/net-snmp/net-snmp/assets/101867702/64d44f69-797d-4d46-9625-83d970f30f06)

ldd /usr/local/sbin/snmpd

![image](https://github.com/net-snmp/net-snmp/assets/101867702/8239523f-deba-45ce-be05-134ac5b4286f)

**Comment by nielsb** [comment]
So, your /usr/local/sbin/snmpd finds it libraries in /lib/x86_64-linux-gnu which smells like an old installation. It should find them in /usr/local/lib.....
/Niels

**Comment by hardaker** [comment]
Essentially the above is saying "clean the libraries out of the system before installing the new one" to make sure that you don't have conflicting versions installed in multiple paths.
