### ISSUE TITLE
Memory leak in HOST-RESOURCES-MIB::hrSWRunTable

### ISSUE THREAD

**Issue by eriklax** [net-snmp/net-snmp#61]
There is a memory leak happening for HOST-RESOURCES-MIB::hrSWRunTable. It causes a significant amount of memory leaking each day. It has been discussed before and suggested patches provided in the past. I believe the solution is still relevant.

https://sourceforge.net/p/net-snmp/bugs/2717/
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=219072

Would this patch be something that could get accepted https://bugs.freebsd.org/bugzilla/attachment.cgi?id=182307&action=diff

**Comment by bvanassche** [comment]
A candidate fix has been applied on the v5.8 and master branches. Please retest. See also commit 5846564f5be46e0e362be894d4cb57be383c5b3d.

**Comment by eriklax** [comment]
Thanks, it worked
