### ISSUE TITLE
Wrong version in 5.9.4

### ISSUE THREAD

**Issue by ryandesign** [net-snmp/net-snmp#646]
5.9.4 reports its version as 5.9.4.pre2:

```
% net-snmp-config --version
5.9.4.pre2
```

**Comment by DanParker75089** [comment]
Even worse, I just installed 5.9.4 and...

> net-snmp-config --version
> 5.8

**Comment by ryandesign** [comment]
> 5.9.4 reports its version as 5.9.4.pre2:

It was fixed in 8c18c7442b68cae57812b4e340bee257d664c841.

> Even worse, I just installed 5.9.4 and...

It sounds like you have not successfully installed 5.9.4. It sounds like you still have 5.8 installed.
