### ISSUE TITLE
net-snmp won't report lmSensors data

### ISSUE THREAD

**Issue by theosib** [net-snmp/net-snmp#67]
Building net-snmp from source with the configure option "--with-mib-modules=ucd-snmp/lmsensorsMib" results in a netsnmp that does depend on libsensors:

$ ldd /usr/local/sbin/snmpd
        linux-vdso.so.1 (0x00007fff4edcd000)
        libnetsnmpagent.so.35 => /usr/local/lib/libnetsnmpagent.so.35 (0x00007f31fbd99000)
        libnetsnmpmibs.so.35 => /usr/local/lib/libnetsnmpmibs.so.35 (0x00007f31fb90d000)
        libnetsnmp.so.35 => /usr/local/lib/libnetsnmp.so.35 (0x00007f31fb586000)
        libsensors.so.4 => /lib64/libsensors.so.4 (0x00007f31fb377000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f31fb173000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f31fadf1000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f31faa2e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f31fc001000)

And I have lmsensors configured to report some data:

$ sensors
pch_cannonlake-virtual-0
Adapter: Virtual device
temp1:        +34.0°C  

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +33.0°C  (high = +80.0°C, crit = +100.0°C)
Core 0:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 1:        +33.0°C  (high = +80.0°C, crit = +100.0°C)
Core 2:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 3:        +30.0°C  (high = +80.0°C, crit = +100.0°C)
Core 4:        +31.0°C  (high = +80.0°C, crit = +100.0°C)
Core 5:        +30.0°C  (high = +80.0°C, crit = +100.0°C)

However, the snmpwalk doesn't include any of this data:

$ snmpwalk -v 2c -c public localhost
SNMPv2-MIB::sysDescr.0 = STRING: Linux localhost.localdomain 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Fri Jan 3 23:55:26 UTC 2020 x86_64
SNMPv2-MIB::sysObjectID.0 = OID: NET-SNMP-MIB::netSnmpAgentOIDs.10
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (80599) 0:13:25.99
SNMPv2-MIB::sysContact.0 = STRING: Root <root@localhost> (configure /etc/snmp/snmp.local.conf)
SNMPv2-MIB::sysName.0 = STRING: localhost.localdomain
SNMPv2-MIB::sysLocation.0 = STRING: Unknown (edit /etc/snmp/snmpd.conf)
SNMPv2-MIB::sysORLastChange.0 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORID.1 = OID: SNMP-FRAMEWORK-MIB::snmpFrameworkMIBCompliance
SNMPv2-MIB::sysORID.2 = OID: SNMP-MPD-MIB::snmpMPDCompliance
SNMPv2-MIB::sysORID.3 = OID: SNMP-USER-BASED-SM-MIB::usmMIBCompliance
SNMPv2-MIB::sysORID.4 = OID: SNMPv2-MIB::snmpMIB
SNMPv2-MIB::sysORID.5 = OID: SNMP-VIEW-BASED-ACM-MIB::vacmBasicGroup
SNMPv2-MIB::sysORID.6 = OID: TCP-MIB::tcpMIB
SNMPv2-MIB::sysORID.7 = OID: IP-MIB::ip
SNMPv2-MIB::sysORID.8 = OID: UDP-MIB::udpMIB
SNMPv2-MIB::sysORID.9 = OID: SNMP-NOTIFICATION-MIB::snmpNotifyFullCompliance
SNMPv2-MIB::sysORID.10 = OID: NOTIFICATION-LOG-MIB::notificationLogMIB
SNMPv2-MIB::sysORDescr.1 = STRING: The SNMP Management Architecture MIB.
SNMPv2-MIB::sysORDescr.2 = STRING: The MIB for Message Processing and Dispatching.
SNMPv2-MIB::sysORDescr.3 = STRING: The management information definitions for the SNMP User-based Security Model.
SNMPv2-MIB::sysORDescr.4 = STRING: The MIB module for SNMPv2 entities
SNMPv2-MIB::sysORDescr.5 = STRING: View-based Access Control Model for SNMP.
SNMPv2-MIB::sysORDescr.6 = STRING: The MIB module for managing TCP implementations
SNMPv2-MIB::sysORDescr.7 = STRING: The MIB module for managing IP and ICMP implementations
SNMPv2-MIB::sysORDescr.8 = STRING: The MIB module for managing UDP implementations
SNMPv2-MIB::sysORDescr.9 = STRING: The MIB modules for managing SNMP Notification, plus filtering.
SNMPv2-MIB::sysORDescr.10 = STRING: The MIB module for logging SNMP Notifications.
SNMPv2-MIB::sysORUpTime.1 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.2 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.3 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.4 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.5 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.6 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.7 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.8 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.9 = Timeticks: (0) 0:00:00.00
SNMPv2-MIB::sysORUpTime.10 = Timeticks: (0) 0:00:00.00
HOST-RESOURCES-MIB::hrSystemUptime.0 = Timeticks: (88967972) 10 days, 7:07:59.72
HOST-RESOURCES-MIB::hrSystemUptime.0 = No more variables left in this MIB View (It is past the end of the MIB tree)

**Comment by fenner** [comment]
Try `snmpwalk -v 2c -c public localhost .1` or `snmpwalk -v 2c -c public localhost LM-SENSORS-MIB::lmSensors`

The default `snmpwalk` invocation with no oid starts the walk at `mib-2`.
