### ISSUE TITLE
SNMP file logging has a bug.

### ISSUE THREAD

**Issue by veldanda3415** [net-snmp/net-snmp#681]
the snmp code for log handling for file has a bug,

* filename:snmp_logging.c
* function:snmp_log_string
* if (logh->enabled && (priority >= logh->pri_max))

            logh->handler( logh, priority, str );
* the priority is what we send in the snmp_log and
* The pri_max is what exactly allowed to print in file.
* For example if we set priority as LOG_DEBUG(which 7) and the
* log->pri_max is set as LOG_WARNING its 4, for all the LOG_WARNING to LOG_DEBUG will get printed.
* However we execpt, it should get print LOG_EMER to LOG_WARNING.
* The (priority >= logh->pri_max) should be (priority <= logh->pri_max) as the Log severity decreases with
* Higher number.

Because of this some times we are seeing files are getting flooding with logs. We need to make it proper.

**Comment by bvanassche** [comment]
Does commit db0f7f83b820b6be91b25417d1e21fa32895f937 help? It has been applied on the V5-9-patches and master branches.

**Comment by veldanda3415** [comment]
Yes and thanks
