### ISSUE TITLE
Suggestion: Add -Wextra -Wno-unused-parameter

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#687]
Please consider adding compiler flags: `-Wextra -Wno-unused-parameter` to the default built. This will allow the compiler to detect mismatched size comparisons as were fixed with https://github.com/net-snmp/net-snmp/pull/684 and https://github.com/net-snmp/net-snmp/pull/685

**Comment by bvanassche** [comment]
I do not agree with enabling `-Wsign-compare`. Other projects, e.g. the Linux kernel, leave this warning disabled. From the Linux kernel changelog: "This -Wsign-compare compiler warning can be very noisy and most of the suggested conversions are unnecessary." See also https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a97ea93ed5b64704a2171c505355c12ab427b1b1.

**Comment by moshekaplan** [comment]
The two PRs I submitted this morning fixed the only two issues detected when I built on Ubuntu. As such, the codebase is already in a good state as far as -Wsign-compare is concerned.

**Comment by bvanassche** [comment]
Please take a look at the output of `git grep 'for.*(int)'`. The '(int)' casts have been inserted in for-statements to suppress `-Wsign-compare` warnings. My opinion is that these casts hurt readability of the code and also reduce type-checking by the compiler. I think the output of that grep command shows that addressing `-Wsign-compare` warnings causes damage to the code base.

**Comment by moshekaplan** [comment]
Agreed, casting as a band-aid solution that only squelches the warning and does not fix the underlying cause is a problem. The better solution is to use properly-sized types. Of course, in larger programs, that can require significant rework and even lead to breaking API changes.
