### ISSUE TITLE
Wrong version reported by utils in 5.9.4

### ISSUE THREAD

**Issue by DanParker75089** [net-snmp/net-snmp#712]
Update: Never mind.  I discovered that the installation procedure places the binaries in /usr/local/bin instead of /usr/bin, so running the utilities without specifying the path picks up older the older 5.8 versions that were installed in /usr/bin.

I just downloaded, built and installed the latest 5.9.4, but all of the command-line tools I've tried so far with the --version argument report version 5.8.
```
$ net-snmp-config --version
5.8
```
This then causes installation of the Perl libraries to fail:
```
$ perl -I. Makefile.PL
Use of uninitialized value in lc at ./Makefile.PL line 73.
Writing MYMETA.yml and MYMETA.json
Use of uninitialized value in lc at ./Makefile.PL line 83.
Writing MYMETA.yml and MYMETA.json
ERROR:
Net-SNMP installed version: 5.8 => 5.08
Perl Module Version:        5.0904
```

**Comment by bvanassche** [comment]
Thank you for the update. I assume that this issue can be closed?

**Comment by DanParker75089** [comment]
> Thank you for the update. I assume that this issue can be closed?

Yes it can, thank you.
