### ISSUE TITLE
heap-buffer-overflow in snmplib/snmpv3.c:587

### ISSUE THREAD

**Issue by moshekaplan** [net-snmp/net-snmp#732]
```
$ ./agent/snmpd -fd -C -r -c "fuzz_input.conf.txt" 127.0.0.1:12345
=================================================================
==239331==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200002b710 at pc 0x7f2aba5d2143 bp 0x7ffc96108ed0 sp 0x7ffc96108ec0
WRITE of size 4 at 0x60200002b710 thread T0
    #0 0x7f2aba5d2142 in setup_engineID /home/user/Desktop/net-snmp/snmplib/snmpv3.c:587
    #1 0x7f2aba5d462d in init_snmpv3_post_premib_config /home/user/Desktop/net-snmp/snmplib/snmpv3.c:1114
    #2 0x7f2aba5e486c in snmp_call_callbacks /home/user/Desktop/net-snmp/snmplib/callback.c:360
    #3 0x7f2aba5ac78a in read_premib_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1114
    #4 0x7f2aba51a6a4 in init_snmp /home/user/Desktop/net-snmp/snmplib/snmp_api.c:925
    #5 0x5583ed7faec1 in main /home/user/Desktop/net-snmp/agent/snmpd.c:909
    #6 0x7f2ab9a23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #7 0x7f2ab9a23b48 in __libc_start_main_impl ../csu/libc-start.c:360
    #8 0x5583ed7f7ee4 in _start (/home/user/Desktop/net-snmp/agent/.libs/snmpd+0x8ee4) (BuildId: 5a392703b0edb942f603e011c18761693f91fd48)

0x60200002b711 is located 0 bytes after 1-byte region [0x60200002b710,0x60200002b711)
allocated by thread T0 here:
    #0 0x7f2abc0de9a7 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:77
    #1 0x7f2aba5d2043 in setup_engineID /home/user/Desktop/net-snmp/snmplib/snmpv3.c:579
    #2 0x7f2aba5d462d in init_snmpv3_post_premib_config /home/user/Desktop/net-snmp/snmplib/snmpv3.c:1114
    #3 0x7f2aba5e486c in snmp_call_callbacks /home/user/Desktop/net-snmp/snmplib/callback.c:360
    #4 0x7f2aba5ac78a in read_premib_configs /home/user/Desktop/net-snmp/snmplib/read_config.c:1114
    #5 0x7f2aba51a6a4 in init_snmp /home/user/Desktop/net-snmp/snmplib/snmp_api.c:925
    #6 0x5583ed7faec1 in main /home/user/Desktop/net-snmp/agent/snmpd.c:909
    #7 0x7f2ab9a23a8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: heap-buffer-overflow /home/user/Desktop/net-snmp/snmplib/snmpv3.c:587 in setup_engineID
Shadow bytes around the buggy address:
  0x60200002b480: fa fa 05 fa fa fa 07 fa fa fa 05 fa fa fa 07 fa
  0x60200002b500: fa fa 05 fa fa fa 07 fa fa fa 05 fa fa fa 07 fa
  0x60200002b580: fa fa 05 fa fa fa 07 fa fa fa 00 03 fa fa 07 fa
  0x60200002b600: fa fa 05 fa fa fa 05 fa fa fa 00 02 fa fa 06 fa
  0x60200002b680: fa fa 07 fa fa fa 04 fa fa fa 00 fa fa fa 04 fa
=>0x60200002b700: fa fa[01]fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200002b780: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200002b800: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200002b880: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200002b900: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x60200002b980: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==239331==ABORTING
```

**Comment by moshekaplan** [comment]
[fuzz_input.zip](https://github.com/net-snmp/net-snmp/files/12922879/fuzz_input.zip)

**Comment by moshekaplan** [comment]
Found with:
```
./configure CC=afl-clang CFLAGS='-g -fsanitize=address,undefined,leak -Wall -Wextra -Wno-unused-parameter ' --with-mib-modules=examples/example && make

AFL_NO_FORKSRV=1 AFL_NO_AFFINITY=1 libtool --mode=execute  afl-fuzz -d -i fuzz_in -o fuzz_out -t 10000 ./agent/snmpd -fd -M /home/user/Desktop/net-snmp/mibs/ -C -r -c @@
```

**Comment by 40ngx** [comment]
@bvanassche I recently found a similar problem. After debugging with gdb, I found that it was related to len=0. Please help me analyze it.Thanks.
![1](https://github.com/user-attachments/assets/4d185f30-1239-4b85-8504-f35fbbe3bbaa)

**Comment by bvanassche** [comment]
Does commit fbdf2ed2e0bb06050d314e008a34d9ecdb84be17 help?

**Comment by 40ngx** [comment]
> Does commit [fbdf2ed](https://github.com/net-snmp/net-snmp/commit/fbdf2ed2e0bb06050d314e008a34d9ecdb84be17) help?

I believe the problem has been solved. Thank you very much for your help.

**Comment by 40ngx** [comment]
> Does commit [fbdf2ed](https://github.com/net-snmp/net-snmp/commit/fbdf2ed2e0bb06050d314e008a34d9ecdb84be17) help?

Sorry, I tried to apply the patch in version 5.9.3. I found that it did not work. The problem still occurs.

**Comment by 40ngx** [comment]
> Does commit [fbdf2ed](https://github.com/net-snmp/net-snmp/commit/fbdf2ed2e0bb06050d314e008a34d9ecdb84be17) help?


I sincerely apologize for bothering you again. Does this problem constitute a security vulnerability? If it is indeed a security vulnerability, would it be appropriate for me to submit it for a CVE ? Thanks.

**Comment by moshekaplan** [comment]
@40ngx : I don't think so. This "vulnerability" is predicated on an attacker being able to supply a crafted config file. An attacker with wrote access to the config would be able to just add a line to load a malicious module, without any need to deal with the complexities of memory corruption.

**Comment by 40ngx** [comment]
@bvanassche Hello, about this issue, I've had some recent discussions with other security researchers, and we think that although it is unwise to use this issue to carry out memory corruption attacks, it still leads to logical vulnerabilities in the code. It should have a certain degree of risk. What do you think? Do you agree with moshekaplan's point of view? Thanks.

**Comment by hardaker** [comment]
So to understand the seriousness of a problem, we need to examine a few things:

1. What is the worst end result this bug triggers: to me this is a denial-of-service -- ie, the agent just crashes.
2. What privileges does it take to trigger the bug?

In the case of #2, it's not an over-the-network problem (so this is good).  Since the trigger comes from reading a specially crafted configuration file, an attacker hoping to trigger this to crash the agent would thus need to be able to write to a configuration file that the agent would later read.  What is the situation where this might occur -- specifically, where one user could craft a file where another user actually runs the agent [because crafting a configuration file as yourself to crash your own agent makes no sense].

In the end, this definitely goes against any reasonable deployment model to me where a snmpd.conf file is actually owned by a different user than the agent is running as.  I fail to see the case where this is common (and certainly ill-advised by those with operational experience).

**Comment by moshekaplan** [comment]
To slightly expand and formalize upon what @hardaker wrote:

A security vulnerability generally requires an escalation of capability from what was available prior. This is usually measured as being able to cause a negative impact on a system's confidentiality, integrity, or availability.

@hardaker wrote
> this definitely goes against any reasonable deployment model to me where a snmpd.conf file is actually owned by a different user than the agent is running as

If the configuration file is already owned by the same user as is running the agent, then there is no escalation of capability, because the user running the snmpd agent or utility could also directly run a command directly on the system. And because there is no escalation of capability, there is no vulnerability,

However, even if the configuration file was owned by a different user as the agent, I still would not treat this as a vulnerability within Net-SNMP. Instead, based on what @hardaker wrote, this would be a vulnerability in the system's configuration, because an attacker with write access to the config would be able to add a line to load a malicious module and obtain escalated privileges that way. Therefore, Net-SNMP's security model is predicated on controlling write access to the Net-SNMP configuration file.

**Comment by 40ngx** [comment]
@hardaker @moshekaplan Thank you both so much again for your detailed responses. Best wishes to you all.

**Comment by 40ngx** [comment]
> @40ngx I have no experience at all with the CVE process. Despite this, @moshekaplan's reply makes a lot of sense to me.

Thank you very much for your reply. My question has been solved.

**Comment by hardaker** [comment]
@moshekaplan said it far better than I did :-)
