### ISSUE TITLE
Website http://www.net-snmp.org/ is outdated

### ISSUE THREAD

**Issue by BenoitPoulet** [net-snmp/net-snmp#744]
Hello,

The homepage http://www.net-snmp.org/ is outdated, last version is wrong and source link goes to Sourceforge.

Regards.

**Comment by bvanassche** [comment]
@hardaker I tried to update the net-snmp-htdocs repository but it seems like I don't have permission to update that repository:
```
~/software/net-snmp-htdocs> git pull --rebase
Current branch master is up to date.
~/software/net-snmp-htdocs> git push origin master
ERROR: Permission to net-snmp/net-snmp-htdocs.git denied to bvanassche.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by hardaker** [comment]
@BenoitPoulet fixed

@bvanassche -- yeah, we really need to do a massive web page overhaul and clean up.  Publishing is less than ideal, and we should move to github/io pages but that's a major push and the wiki gets in the way.
