### ISSUE TITLE
cert:map:secname is picking SHA1 CA-Fingerprint instead of SHA256

### ISSUE THREAD

**Issue by basanir** [net-snmp/net-snmp#75]
cert:map:secname is picking SHA1 CA-Fingerprint instead of SHA256. 

Picking SHA256 Fingerprint for certificate but not for CA-fingerprint

As a result validation is failing to connect to client.
==
tlstcp: accept succeeded on sock 8
tlstcp: received 113 decoded bytes from tls
tlstcp: recvfrom fd 9 got 113 bytes (from TLSTCP: dlqa2061.lss.emc.com:2061)
tls:secLevel: SecLevel 3
openssl:fingerprint: WARNING: alg 2 does not match cert alg 4
cert:map:secname: looking for matches for 2 fingerprints
cert:map:secname: no match for 6ba427c81bcf93e177343f0cbc29011f76a90a60 **<--SHA1 CA fingerprint. Should pick SHA256 here -->**
cert:map:secname: no match for bc7245d121130684215042f1dff2dcc7cf89401c6b8a045b92167d02444f6f1f  **_--> Picking SHA256 for certificate fingerprint -->_**
cert:map:secname: found 0 matches for fingerprints
tlstcp: Shutting down SSL connection
tlsbase: Freeing TLS Base data for a session

==

**Comment by basanir** [comment]
in snmplib/snmp_openssl.c file value was hardcoded to SHA1 instead of -1

--
/*
         * loop over chain, adding fingerprint / cert for each
         */
        DEBUGMSGT(("ssl:cert:chain", "examining cert chain\n"));
        for(i = 0; i < sk_num((const void *)ochain); ++i) {
            ocert_tmp = (X509*)sk_value((const void *)ochain,i);
            fingerprint = netsnmp_openssl_cert_get_fingerprint(ocert_tmp,
                                                               **NS_HASH_SHA1**);
--

**Comment by basanir** [comment]
In snmplib/snmp_openssl.c file value was hardcoded to SHA1 instead of -1

--
/*
* loop over chain, adding fingerprint / cert for each
*/
DEBUGMSGT(("ssl:cert:chain", "examining cert chain\n"));
for(i = 0; i < sk_num((const void )ochain); ++i) {
ocert_tmp = (X509)sk_value((const void *)ochain,i);
fingerprint = netsnmp_openssl_cert_get_fingerprint(ocert_tmp,
**NS_HASH_SHA1**); --> This should be -1 instead

**Comment by basanir** [comment]
@bvanassche  Can you please take a look at this bug, when you have a chance.

Thanks!

**Comment by bvanassche** [comment]
A candidate fix has been checked in on the v5.8 and master branches. Please retest.

**Comment by basanir** [comment]
Build target(listener) with the fix code. Seeing below error when I send TLS1_2 connection from client

==
NET-SNMP version 5.8.1.pre2
tlstcp: netsnmp_tlstcp_accept called
TLSTCP: Failed SSL_accept
---- OpenSSL Related Errors: ----
 TLS error: SSL_accept: rc=-1, sslerror = 1 (SSL_ERROR_SSL)
 TLS Error: wrong version number
---- End of OpenSSL Errors ----
==

below is the config used to build
==
./configure  --with-perl-modules --enable-embedded-perl --with-openssl=/usr/local/lib --enable-shared  --enable-ipv6 --with-security-modules="usm tsm" --with-transports="UDPIPv6 TCPIPv6 DTLSUDP TLSTCP"
==

openssl verion
==
openssl version
OpenSSL 1.1.0l  10 Sep 2019
==

**Comment by basanir** [comment]
Build target(listener) with the fix code. Seeing below error when I send TLS1_2 connection from client

==
NET-SNMP version 5.8.1.pre2
tlstcp: netsnmp_tlstcp_accept called
TLSTCP: Failed SSL_accept
---- OpenSSL Related Errors: ----
TLS error: SSL_accept: rc=-1, sslerror = 1 (SSL_ERROR_SSL)
TLS Error: wrong version number
---- End of OpenSSL Errors ----

**Below is the config used to build**
./configure --with-perl-modules --enable-embedded-perl --with-openssl=/usr/local/lib --enable-shared --enable-ipv6 --with-security-modules="usm tsm" --with-transports="UDPIPv6 TCPIPv6 DTLSUDP TLSTCP"

**openssl version**
OpenSSL 1.1.0l 10 Sep 2019

**Comment by basanir** [comment]
@bvanassche  is there any workaround to pick TLS1_2 ?

**Comment by bvanassche** [comment]
I'm not familiar with TLS. Maybe someone else can help?

**Comment by basanir** [comment]
Above Fix is working fine
