### ISSUE TITLE
lmSensors MIB uses Gauge32 for a float

### ISSUE THREAD

**Issue by csmall** [net-snmp/net-snmp#752]
There are several discussions around where people have small servers in places where it gets cold and their temperature graphs stop working or they report very very high numbers, such as:

- https://github.com/librenms/librenms/issues/15609
- https://www.reddit.com/r/LibreNMS/comments/18ah8wo/submitted_a_bug_report_any_help_from_reddit/

The value is gathered in `netsnmp_sensor_arch_load()` at https://github.com/net-snmp/net-snmp/blob/759421b42563832fcd28559d438649b0f97f0389/agent/mibgroup/hardware/sensors/lmsensors_v3.c#L79-L81

with the return value being a double which allows negative temperatures.

The value is then changed to a Gauge32 at lmSensorsTable_handler:
https://github.com/net-snmp/net-snmp/blob/759421b42563832fcd28559d438649b0f97f0389/agent/mibgroup/ucd-snmp/lmsensorsMib.c#L224-L227

The issue is a Gauge32 cannot show a negative number, this is what the MIB has defined for this OID so the implementation is correct as far as MIB is concerned.

My suggestion is:

- Update the lmSensors MIB to have an additional field, not sure if the old temperature should be deprecated.
- Update the handler for this new field and convert it to an Integer32

My expectation is its a handful lines of code to do this. If the approach is ok I can even create a PR for it. I'm not sure what the mechanics are of updating the MIB though.

The mib change would be something like:
```
lmTempSensorsValue OBJECT-TYPE
    SYNTAX      Gauge32
    MAX-ACCESS  read-only
    STATUS      deprecated
    DESCRIPTION
        "The temperature of this sensor in mC.

          This object has been deprecated in favor of
          'lmTempSensorsTemperature(4), which can display
          temperatures below 0 degrees Celcius."
    ::= { lmTempSensorsEntry 3 }

lmTempSensorsTemperature OBJECT-TYPE
    SYNTAX      Integer32
    UNITS "mCel"
    MAX-ACCESS  read-only
    STATUS      current
    DESCRIPTION
        "The temperature of this sensor in mCel."
    ::= { lmTempSensorsEntry 4 }
```

I changed the unit from mC to mCel to follow RFC8428 and currently, its reporting the temperature in milliCoulombs. That's a minor thing in any case.

**Comment by Raspbianuser** [comment]
@csmall thanks alot for this!

**Comment by csmall** [comment]
lmSensors OID is `.1.3.6.1.4.1.2021.13.16.2.1.3.2`. Some other systems use strange/incorrect OIDs and a script, so that's using the [Extending Agent Funcitonality](https://net-snmp.sourceforge.io/docs/man/snmpd.conf.html#lbAZ). For those setups, its whatever the script does.

**Comment by Raspbianuser** [comment]
Any progress?

**Comment by Raspbianuser** [comment]
December 2024 is round the corner, temps below 0 deg C here in Norway - Issue still persists, any news?

**Comment by Raspbianuser** [comment]
@csmall that would be great! 
[Graphs of the bug](https://imgur.com/a/7GPzLlQ)

**Comment by csmall** [comment]
5.9.5.2 got released last week and has this fix, see https://github.com/net-snmp/net-snmp/blob/v5.9.5.2/agent/mibgroup/ucd-snmp/lmsensorsMib.c#L77  5.9.5.2 is also in Debian Sid.
