### ISSUE TITLE
net-snmp release 5.9.4 reports wrong version 5.9.4.pre2

### ISSUE THREAD

**Issue by FinzelStefan** [net-snmp/net-snmp#754]
On github.com both downloaded files of latest net-snmp 5.9.4 release report wrong version 5.9.4.pre2

ls -l net-snmp-5.9.4*z*
-rw-rw-r-- 1 xxx xxx 6681606 Dez 10 17:00 net-snmp-5.9.4.tar.gz
-rw-rw-r-- 1 xxx xxx 7959460 Dez 10 17:00 net-snmp-5.9.4.zip

./configure --with-defaults -prefix=/opt/xxx ${SSL_CFG} --enable-blumenthal-aes --disable-agent --disable-scripts --disable-snmptrapd-subagent --disable-debugging --disable-embedded-perl --disable-perl-cc-checks --disable-manuals --disable-static --enable-silent-libtool --with-cflags='-O3 -fomit-frame-pointer'
...
            Net-SNMP configuration summary:

  SNMP Versions Supported:    1 2c 3
  Building for:               linux
  Net-SNMP Version:           5.9.4.pre2

**Comment by ramu8181** [comment]
Hi stefan if u have installed the 5.9.4 version need some help on this.

**Comment by FinzelStefan** [comment]
I am sorry, I have no clue and no snmp server to test AES256 so far.

**Comment by nielsb** [comment]
@ramu8181 what is the problem that you have?

**Comment by FinzelStefan** [comment]
It's quite simple: some of my scripts detect this pre version instead of a minor version and report an annoying warning.
A release should not have a 'pre'.

**Comment by ramu8181** [comment]
I followed the instructions on the net-snmp 5.9 version installation . but I am not seeing -x option newly configured version
Can you please help me how to solve this issue
 
 
---------------------------------------------------------
            Net-SNMP configuration summary:
---------------------------------------------------------
 
  SNMP Versions Supported:    1 2c 3
  Building for:               linux
  Net-SNMP Version:           5.9.4.pre2
  Network transport support:  Callback Unix Alias TCP UDP TCPIPv6 UDPIPv6 IPv4Base SocketBase TCPBase UDPIPv4Base UDPBase IPBase IPv6Base
  SNMPv3 Security Modules:     usm
  Agent MIB code:            default_modules =>  snmpv3mibs mibII ucd_snmp notification notification-log-mib target agent_mibs agentx disman/event disman/schedule utilities host
  MYSQL Trap Logging:         unavailable
  Embedded Perl support:      enabled
  SNMP Perl modules:          building -- embeddable
  SNMP Python modules:        disabled
  Crypto support from:        crypto
  Authentication support:     MD5 SHA1 SHA224 SHA256 SHA384 SHA512
  Encryption support:         DES AES AES128 AES192 AES192C AES256 AES256C
  Local DNSSEC validation:    disabled
 
---------------------------------------------------------
 
 
 
 
 
cisco@inserthostnamehere:~$ snmpget --version
NET-SNMP version: 5.9.4.pre2
cisco@inserthostnamehere:~$ snmpwalk
No hostname specified.
USAGE: snmpwalk [OPTIONS] AGENT [OID]
 
  Version:  5.9.4.pre2
  Web:      http://www.net-snmp.org/
  Email:    [net-snmp-coders@lists.sourceforge.net](mailto:net-snmp-coders@lists.sourceforge.net)
 
OPTIONS:
  -h, --help         display this help message
  -H                 display configuration file directives understood
  -v 1|2c|3          specifies SNMP version to use
  -V, --version             display package version number
SNMP Version 1 or 2c specific
  -c COMMUNITY       set the community string
SNMP Version 3 specific
  -a PROTOCOL        set authentication protocol (MD5|SHA|SHA-224|SHA-256|SHA-384|SHA-512)
  -A PASSPHRASE             set authentication protocol pass phrase
  -e ENGINE-ID       set security engine ID (e.g. 800000020109840301)
  -E ENGINE-ID       set context engine ID (e.g. 800000020109840301)
  -l LEVEL           set security level (noAuthNoPriv|authNoPriv|authPriv)
  -n CONTEXT         set context name (e.g. bridge1)
  -u USER-NAME       set security name (e.g. bert)
  -x PROTOCOL        set privacy protocol (DES|AES)
  -X PASSPHRASE             set privacy protocol pass phrase
  -Z BOOTS,TIME             set destination engine boots/time
General communication options
  -r RETRIES         set the number of retries
  -t TIMEOUT         set the request timeout (in seconds)
Debugging
  -d                 dump input/output packets in hexadecimal
  -D[TOKEN[,...]]    turn on debugging output for the specified TOKENs
                       (ALL gives extremely verbose debugging output)
General options
  -m MIB[:...]       load given list of MIBs (ALL loads everything)
  -M DIR[:...]       look in given list of directories for MIBs
    (default: /home/cisco/.snmp/mibs:/usr/local/share/snmp/mibs)
  -P MIBOPTS         Toggle various defaults controlling MIB parsing:
                       u:  allow the use of underlines in MIB symbols
                       c:  disallow the use of "--" to terminate comments
                       d:  save the DESCRIPTIONs of the MIB objects
                       e:  disable errors when MIB symbols conflict
                       w:  enable warnings when MIB symbols conflict
                       W:  enable detailed warnings when MIB symbols conflict
                       R:  replace MIB symbols from latest module
  -O OUTOPTS         Toggle various defaults controlling output display:
                       0:  print leading 0 for single-digit hex characters
                       a:  print all strings in ascii format
                       b:  do not break OID indexes down
                       e:  print enums numerically
                       E:  escape quotes in string indices
                       f:  print full OIDs on output
                       n:  print OIDs numerically
                       p PRECISION:  display floating point values with specified PRECISION (printf format string)
                       q:  quick print for easier parsing
                       Q:  quick print with equal-signs
                       s:  print only last symbolic element of OID
                       S:  print MIB module-id plus last element
                       t:  print timeticks unparsed as numeric integers
                       T:  print human-readable text along with hex strings
                       u:  print OIDs using UCD-style prefix suppression
                       U:  don't print units
                       v:  print values only (not OID = value)
                       x:  print all strings in hex format
                       X:  extended index format
  -I INOPTS          Toggle various defaults controlling input parsing:
                       b:  do best/regex matching to find a MIB node
                       h:  don't apply DISPLAY-HINTs
                       r:  do not check values for range/type legality
                       R:  do random access to OID labels
                       u:  top-level OIDs must have '.' prefix (UCD-style)
                       s SUFFIX:  Append all textual OIDs with SUFFIX before parsing
                       S PREFIX:  Prepend all textual OIDs with PREFIX before parsing
  -L LOGOPTS         Toggle various defaults controlling logging:
                       e:           log to standard error
                       o:           log to standard output
                       n:           don't log at all
                       f file:      log to the specified file
                       s facility:  log to syslog (via the specified facility)
 
                       (variants)
                       [EON] pri:   log to standard error, output or /dev/null for level 'pri' and above
                       [EON] p1-p2: log to standard error, output or /dev/null for levels 'p1' to 'p2'
                       [FS] pri token:    log to file/syslog for level 'pri' and above
                       [FS] p1-p2 token:  log to file/syslog for levels 'p1' to 'p2'
  -C APPOPTS         Set various application specific behaviours:
                       p:  print the number of variables found
                       i:  include given OID in the search range
                       I:  don't include the given OID, even if no results are returned
                       c:  do not check returned OIDs are increasing
                       t:  Display wall-clock time to complete the walk
                       T:  Display wall-clock time to complete each request
                       E {OID}:  End the walk at the specified OID
cisco@inserthostnamehere:~$ 
 
 
 
when I try with -x option with AES256 it is throwing unsupported commands
 
 
[cisco@inserthostnamehere:~/net-snmp-5.9.4$](mailto:cisco@inserthostnamehere:~/net-snmp-5.9.4$) 
[cisco@inserthostnamehere:~/net-snmp-5.9.4$](mailto:cisco@inserthostnamehere:~/net-snmp-5.9.4$) 
[cisco@inserthostnamehere:~/net-snmp-5.9.4$](mailto:cisco@inserthostnamehere:~/net-snmp-5.9.4$) snmpwalk -v 3 -l noAuthNoPriv -u "mf" -a SHA -A '4d6141475c604d616352425559494860514d51664c464355615b47575148414142' -x AES256 -X '4d6141475c604d616352425559494860514d51664c464355615b47575148414142' 10.52.157.242  1.3.6.1.2.1
Invalid privacy protocol specified after -3x flag: AES256
USAGE: snmpwalk [OPTIONS] AGENT [OID]
 
  Version:  5.9.4.pre2
  Web:      http://www.net-snmp.org/
  Email:    [net-snmp-coders@lists.sourceforge.net](mailto:net-snmp-coders@lists.sourceforge.net)
 
OPTIONS:
  -h, --help         display this help message
  -H                 display configuration file directives understood
  -v 1|2c|3          specifies SNMP version to use
  -V, --version             display package version number
SNMP Version 1 or 2c specific
  -c COMMUNITY       set the community string
 
Thanks
Ramki
 
-- 
Niels Baggesen -- @home -- Århus -- Denmark -- [nba@users.sourceforge.net](mailto:nba@users.sourceforge.net)
   The purpose of computing is insight, not numbers  --  R W Hamming

**Comment by hardaker** [comment]
You're right that the configure script in net-snmp 5.9.4 failed to get updated to the current version (which is odd).  I'll try to make sure this doesn't happen for future releases, but we can't back-fix it at this point to a published release.
