### ISSUE TITLE
net-snmp in ndk environment compiled with error message ：unknown type name 'fd_set'  && unknown type name 'ulong'

### ISSUE THREAD

**Issue by Chrf00** [net-snmp/net-snmp#760]
![image](https://github.com/net-snmp/net-snmp/assets/122246987/e81c39d3-2362-4e93-b040-d0419b4c88ff)

![image](https://github.com/net-snmp/net-snmp/assets/122246987/861ae7ec-3a4e-4605-b7ca-f0400f40ace4)

**Comment by nielsb** [comment]
What OS is this?
Which configure options?

**Comment by Chrf00** [comment]
> What OS is this? Which configure options?

**Comment by Chrf00** [comment]
> What OS is this? Which configure options?

Cross-compile, the compilation system is Linux 4860135a3e05 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linu.
And the target system is Android，build with android ndk r25b.

configure options: 
    CC="${ANDROID_TOOLCHAIN_NAME}" ./configure \
    --disable-applications \
    --disable-deprecated \
    --disable-embedded-perl \
    --disable-manuals \
    --disable-md5 \
    --disable-mib-loading \
    --disable-mibs \
    --disable-minimalist \
    --disable-perl-cc-checks \
    --without-perl-modules \
    --disable-scripts \
    --disable-snmptrapd-subagent \
    --disable-snmpv1 \
    --disable-snmpv2c \
    --disable-testing-code \
    --disable-ucd-snmp-compatibility \
    --enable-as-needed \
    --host=arm-linux-android \
    --prefix="${str:-/data/nms/snmp}" \
    --target=arm-linux-android \
    --with-cflags="-g3 -D__ANDROID_API__=${api_level_num} -DHAVE_NETINET_IN_H -DHAVE_IN_ADDR_T  -DNETSNMP_FEATURE_REMOVE_LOGGING_FILE -DSIGPIPE -fstack-protector-all -fPIC" \
    --with-default-snmp-version="3" \
    --with-endianness=little \
    --with-enterprise-notification-oid="1.3.6.1.4.1.0000.4" \
    --with-enterprise-oid="0000" \
    --with-enterprise-sysoid="1.3.6.1.4.1.0000.3.2.NETSNMP_OSTYPE" \
    --with-logfile=none \
    --with-openssl="${SNMP_OPENSSL_PATH}" \
    --without-elf \
    --with-out-mib-modules="notification notification-log-mib" \
    --with-persistent-directory="${str:-/data/nms/snmp}" \
    --with-sys-contact="xx@no.where" \
    --with-sys-location=/system \
    --with-sysroot="${SYSROOT}" \
    --with-temp-file-pattern="${str:-/data/snmp.tmpXXXXXX}"

**Comment by bvanassche** [comment]
A fix for the fd_set and ulong types is available (commit b4598662a39ff6974119c900ea56a4d020eac366).

The command for cross-compiling Net-SNMP doesn't look good to me. Something like this should work better (untested):
```
export CC=/usr/lib/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang
./configure --host=aarch64-linux-android33 --without-openssl
```

**Comment by bvanassche** [comment]
With this configure command the build succeeds on my workstation:
```
./configure --with-defaults --with-openssl=internal '--with-out-mib-modules=if-mib default_modules' --disable-embedded-perl --without-perl-modules 'CFLAGS=-fPIE -DNETSNMP_USE_ASSERT' --host=aarch64-linux-android33
```

**Comment by Chrf00** [comment]
Thank you very much for your help. @bvanassche
