### ISSUE TITLE
snmpd crashes when IPv6 or domain name specified in trapsess

### ISSUE THREAD

**Issue by chaitugorantla** [net-snmp/net-snmp#77]
Hi,

I'm using net-snmp-5.6.1-arm version in my application to perform snmpget/walk and receive snmp traps. I have configured snmpv3 user to receive traps. See below example snmpd.conf file with snmpv3 user.

snmpd.conf:-

rwuser testsnmpipv6 auth -V Dummy
createUser testsnmpipv6 SHA "welcome"
trapsess -v 3 -u testsnmpipv6 -l authNoPriv -a SHA -A "test123" xxx:xx9:0:1:1b0:ffff:xxxx:1234/64
engineIDType 3
agentaddress udp:161,udp6:161
/etc # 

snmpd keeps crashing with this configuration. If I change the ipv6 address to ipv4 then snmpd stable and able to receive traps. I'm not sure if this is a limitation in trapsess command in 5.6.1 version which is not able to handle ipv6 or domain name. 
Is there a fix/patch available in later versions? or Am I doing anything wrong in the configuration?

Appreciate your feedback.

**Comment by chaitugorantla** [comment]
Note: snmpd crashes only in snmpv3 user configuration. It works fine if I use IPv6 address in snmp v1/v2 config using trapsink command.

**Comment by bvanassche** [comment]
Net-SNMP v5.6.1 is no longer supported. Please upgrade to the code on the V5-8-patches branch.
