### ISSUE TITLE
Authentication protocol comparison uses the passphrase rather than the protocol

### ISSUE THREAD

**Issue by jeaston-nasuni** [net-snmp/net-snmp#771]
https://github.com/net-snmp/net-snmp/blame/d1306339babd45331b199aa6617dc998d7089311/snmplib/snmpusm.c#L4741

The comparison references cp rather than the token in buf extracted by copy_nword() above it.
This was introduced in Net-SNMP-5.8.  In 5.8 and has the effect of using the default authentication protocol if the authentication passphrase starts with "default".

**Comment by bvanassche** [comment]
Do you perhaps plan to submit a patch to fix this? If not, a reference to the commit that introduced this bug would also be welcome.

**Comment by jeaston-nasuni** [comment]
Sorry about that.  I'm new to this.

The commit that introduced the bug appears to be
https://github.com/net-snmp/net-snmp/commit/09ac3f2f68b2cf4bc3ff98d41a7e945c5eabffbb#diff-3a67fe88ef282292fdc6e54c4a40f82d0eb820033d3da539fb1d2ca1d6a53268R4555

(line 4555 in snmplib/snmpusm.c)

**Comment by bvanassche** [comment]
Does this patch look good to you: https://github.com/net-snmp/net-snmp/compare/V5-9-patches...bvanassche:net-snmp:V5-9-patches ?

**Comment by jeaston-nasuni** [comment]
Yes.  It looks good.
One minor improvement might be to use strcmp() instead of strncmp() if the token in buf is appropriately null terminated.
