### ISSUE TITLE
Net-snmp 5.9.4 does not support the Linux kernel 6.7 /proc/net/snmp file

### ISSUE THREAD

**Issue by F-i-f** [net-snmp/net-snmp#786]
System:
- Fedora Linux 39 running kernel 6.7.3.
- net-snmp 5.9.4

Symptoms:
- system journal contains:
  ```
  snmpd[10442]: systemstats_linux: unexpected header length in /proc/net/snmp. 237 != 224
  ```

Proposed fix in PR #785.

**Comment by paolokappa** [comment]
I have the same behavior with Ubuntu and kernel 6.7.2, but the SNMP service seems to be working correctly nonetheless. Have you encountered any significant anomalies?

Feb  5 12:53:37 time snmpd[974]: systemstats_linux: unexpected header length in /proc/net/snmp. 237 != 224

Linux time 6.7.2-060702-generic #202401251943 SMP PREEMPT_DYNAMIC Fri Jan 26 01:47:27 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

Thanks.

Paolo Caparrelli
GOLINE SA

**Comment by prahal** [comment]
@F-i-f did you intended to title the bug "Linux 6.7.x ..." instead of "Linux 5.7.x ..."?
I also have this message spamming my logs.
Running 6.7. Thanks for your work.

**Comment by paolokappa** [comment]
Hi @prahal,
Yes, I think he was referring to the kernel version 6.7.X. 
In fact, in his explanation, he talks about Fedora Linux 39 running kernel 6.7.3.
I have the same problem on Ubuntu 22.04.3 LTS with the same kernel... but I think also with 6.2 because I did a test with that as well.
Do you have any ideas about this?
Thanks

Paolo Caparrelli
GOLINE SA

**Comment by prahal** [comment]
@paolokappa see #785  @F-i-f already sent a PR to fix the issue (it might require work after a review). But you can test it.

**Comment by prahal** [comment]
@F-i-f could you close this issue? Your PR was merged (but had no "Fixes #786" lines)

**Comment by fda77** [comment]
What about a new relese version?
Currently i'm running an old 6.6 kernel to stop log-spam

Btw, please change topic
> Linux 5.7.x breaks net-snmp

its 6.7!

**Comment by bvanassche** [comment]
I have changed the title and will close this bug report. Thanks everyone for the help!

**Comment by F-i-f** [comment]
Thank you for fixing the wrong title, and sorry for forgetting about the "Fixes" tag.

**Comment by fda77** [comment]
I've still logspam with kernel 6.7.
What about a new release of snmp?

**Comment by TheBossME** [comment]
Same issue with Proxmox kernel 6.8.x releases

snmpd[1031809]: systemstats_linux: unexpected header length in /proc/net/snmp. 237 != 224

**Comment by bvanassche** [comment]
Issues discovered with a Net-SNMP binary from a Linux distributor should be reported in the bug tracking system of that Linux distributor instead of here.

**Comment by fda77** [comment]
The "Linux distributor" told me "its the latest version" - which is buggy and not fixed since some months.
So again whats the problem with a new release?

**Comment by bvanassche** [comment]
> So again whats the problem with a new release?

Is that your way of being friendly and polite towards people from which you are expecting to do unpaid work for you?

A new release will be available several weeks from now. If you don't want to wait that long, and if your Linux distributor doesn't backport patches, feel free to download the Net-SNMP source code and to build and install it.

**Comment by normanr** [comment]
eg: Debian's bug report is here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1069087. I have added a link to the fixing commit so that the maintainer can apply it as patch.

Thanks for helping maintain net-snmp!

**Comment by fda77** [comment]
i've removed net-snmp meanwhile, its unreliable
