### ISSUE TITLE
What is config file path for net-snmp 5.9.4?

### ISSUE THREAD

**Issue by aloktomar26** [net-snmp/net-snmp#789]
I was using net-snmp 5.7.3 and need to update to net-snmp 5.9.4.
What is the default path for snmpd.conf to save the SNMPv3 user details? Also can someone share a snmpd.conf file (for SNMPv3) for reference?

In net-snmp 5.7.3 snmpd.conf was written at path : /opt/var/tmp/SNMP/var/net-snmp/
File content : createUser myUser MD5 "password" DES password

Also, when you place snmpd.conf file at /opt/var/tmp/SNMP/var/net-snmp/, it gets overwritten.

**Comment by abhiz710** [comment]
@bvanassche can you please help on this issue?

**Comment by nielsb** [comment]
That will depend on your configure options. The path that you show is certainly unusual, what system is this?
/Niels

**Comment by abhiz710** [comment]
We are working on Linux

**Comment by aloktomar26** [comment]
The above issue is resolved, but I'm facing a new issue. When switching from SNMPv1 to SNMPv3 and vice versa, crash occurs with the following logs:

Received TERM or STOP signal...  shutting down...

**Comment by hardaker** [comment]
The `net-snmp-config` utility can always display configuration paths that have been compiled, so you can use it to determine what your paths are based on your build flags.

```
$ /net-snmp-config  --snmpconfpath
/usr/local/etc/snmp:/usr/local/share/snmp:/usr/local/lib/snmp:/home/hardaker/.snmp:/var/net-snmp
```
