### ISSUE TITLE
TLS version greater than 1 is not supported in net-snmp 5.9.3

### ISSUE THREAD

**Issue by niksparte** [net-snmp/net-snmp#803]
Hi Everyone,

I have openssl configuration (**/etc/ssl/openssl.cnf**) as below
**[openssl_init]**
**ssl_conf = ssl_sect**
**[ssl_sect]**
**system_default = system_default_sect**
**[system_default_sect]**
**MinProtocol = TLSv1.2**

In above configuration, I have mentioned MinProtocol as TLSv1.2.
When I am trying to get information for net-snmp, I am getting below error messages in "**/var/log/syslog**" file.

2024-03-13T09:56:19.602248+00:00 mytest snmpd[36979]: **TLSTCP: Failed SSL_accept**
2024-03-13T09:56:19.602267+00:00 mytest  snmpd[36979]: **---- OpenSSL Related Errors: ----**
2024-03-13T09:56:19.602276+00:00 mytest  snmpd[36979]: **TLS error: SSL_accept: rc=-1, sslerror = 1 (SSL_ERROR_SSL)**
2024-03-13T09:56:19.602287+00:00 mytest  snmpd[36979]: **TLS Error: no suitable signature algorithm**
2024-03-13T09:56:19.602294+00:00 mytest 7 snmpd[36979]: **---- End of OpenSSL Errors ----**

Any help is much appreciated.

Thank you.

**Comment by nielsb** [comment]
This should be fixed by commit  8570eb2b40dd342

**Comment by hardaker** [comment]
Thanks @nielsb - closing.

**Comment by niksparte** [comment]
Hi @nielsb and @hardaker,

In master, these two "#ifdef - #endif" statements are removed. So where you have committed these changes. In which released branch, I can find these changes?

Please let me know.

Thank you.

**Comment by rajeshgalla963** [comment]
Hi @nielsb and @hardaker, I have recently downloaded 8.9.4 source code zip file from official site net-snmp.org. In the source code the fix is not present, I am getting the same error while snmptrapd trying to connect with client. Do i need to add this code change in my downloaded 8.9.4 source code or is there any ready patch release/code to apply.

**Comment by usvi** [comment]
@rajeshgalla963 : Look at https://github.com/net-snmp/net-snmp/tags . 5.9.4 was tagged year 2023. It cannot include changes from year 2024.
