### ISSUE TITLE
is BUG 3027900 fixed?

### ISSUE THREAD

**Issue by phuong-dut-es** [net-snmp/net-snmp#81]
I still got BUG 3027900 about memcmp.lo when i cross-compile the net-snmp source code to run on arm64? DId you find anyway to fix it?

**Comment by bvanassche** [comment]
Please provide more information: what version of Net-SNMP are you using, which command was used to compile it and what are the symptoms that you see? Does compilation fail or does Net-SNMP fail to start?

**Comment by phuong-dut-es** [comment]
I'm using Net-snmp 5.9 with openssl 1.1.1d, when i cross compile using aarch-linux-gnu-gcc to cross-compile for arm64 architechture this error is show: 
Make[4] : *** No rule to make target 'memcmp.lo', needed by libnetsnmp.la . stop.

The configure i use is:
- for openssl: ./Configurate linux-aarch64 --cross-compile-prefix=aarch64-linux-gnu- --prefix=/some/directory
- for net-snmp: ./configurate --host=arm-linux --target=arm-linux --with-cc= aarch64-linux-gnu-gcc --with-ar=aarch64-linux-gnu-ar --prefix=/some/directory --disable-embedded-perl  --disable-perl-cc-checks --without-perl-modules  --with-openssl=/directory/that/i/make/install/openssl

**Comment by bvanassche** [comment]
A fix has been checked in on the v5.8 and master branches. Please retest with the latest version of the master branch.
