### ISSUE TITLE
Compilation error - snmptrapd_sql.c:541:50: error: assignment to ‘_Bool *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]

### ISSUE THREAD

**Issue by pornmailbox** [net-snmp/net-snmp#815]
While compile net-snmp-5.9.4 with gcc-14.1.0 I've got this error.

snmptrapd_sql.c:541:50: error: assignment to ‘_Bool *’ from incompatible pointer type ‘char *’ [-Wincompatible-pointer-types]
  541 |         _tbind[TBIND_v3_SECURITY_ENGINE].is_null = &_no_v3;
      |                                                  ^
make: *** [Makefile:100: snmptrapd_sql.lo] Error 1
make: *** Waiting for unfinished jobs....

Proposed simple patch to resolve the issue shown below: 
...
'diff '--color=auto' -Naur a/apps/snmptrapd_sql.c b/apps/snmptrapd_sql.c
--- a/apps/snmptrapd_sql.c<---->2023-08-15 23:32:01.000000000 +0300
+++ b/apps/snmptrapd_sql.c<---->2024-05-15 17:56:20.225494663 +0300
@@ -201,7 +201,7 @@
  * static bind structures, plus 2 static buffers to bind to.
  */
 static MYSQL_BIND _tbind[TBIND_MAX], _vbind[VBIND_MAX];
-static char       _no_v3;
+static _Bool       _no_v3;
.
 static void _sql_process_queue(u_int dontcare, void *meeither);'
...

**Comment by bvanassche** [comment]
I'm concerned that the above patch would break compatibility for older versions of the MySQL library. How about this patch?
```
diff --git a/apps/snmptrapd_sql.c b/apps/snmptrapd_sql.c
index 5713a21e103f..9b9df7ba264e 100644
--- a/apps/snmptrapd_sql.c
+++ b/apps/snmptrapd_sql.c
@@ -201,7 +201,7 @@ typedef struct sql_buf_t {
  * static bind structures, plus 2 static buffers to bind to.
  */
 static MYSQL_BIND _tbind[TBIND_MAX], _vbind[VBIND_MAX];
-static char       _no_v3;
+static typeof(*((MYSQL_BIND*)NULL)->is_null) _no_v3;
 
 static void _sql_process_queue(u_int dontcare, void *meeither);
 
```

**Comment by pornmailbox** [comment]
> I'm concerned that the above patch would break compatibility for older versions of the MySQL library. How about this patch?
> 
> ```
> diff --git a/apps/snmptrapd_sql.c b/apps/snmptrapd_sql.c
> index 5713a21e103f..9b9df7ba264e 100644
> --- a/apps/snmptrapd_sql.c
> +++ b/apps/snmptrapd_sql.c
> @@ -201,7 +201,7 @@ typedef struct sql_buf_t {
>   * static bind structures, plus 2 static buffers to bind to.
>   */
>  static MYSQL_BIND _tbind[TBIND_MAX], _vbind[VBIND_MAX];
> -static char       _no_v3;
> +static typeof(*((MYSQL_BIND*)NULL)->is_null) _no_v3;
>  
>  static void _sql_process_queue(u_int dontcare, void *meeither);
>  
> ```

This patch is better. net-snmp-5.9.4 compiled fine.
