### ISSUE TITLE
Need binaries of net-snmp 5.9.4

### ISSUE THREAD

**Issue by swarnsaurabh** [net-snmp/net-snmp#819]
I was trying to create binaries of net-snmp 5.9.4 for windows. But not getting any success. 
Can someone please provide steps to create net-snmp 5.9.4 binaries for windows. 

last binaries available on net-snmp site is of 5.7.0
If binaries for net-snmp 5.9.4 is available with someone, can this be please shared here?

Thanks.

**Comment by bvanassche** [comment]
Please take a look at https://sourceforge.net/projects/net-snmp/files/net-snmp/5.9.4/.

**Comment by swarnsaurabh** [comment]
Steps mentioned in the Readme file for creating the binary is as below:
1. Uninstall Net-SNMP.
 2. Remove the C:\usr directory completely.
 3. Open a command prompt
 4. Run the Microsoft Visual Studio vcvarsall.bat script.
 5. Change the current working directory to the Net-SNMP win32\dist directory.
 6. Run the .\build-binary.bat script.
 7. Copy the net-snmp-${version}.x86.exe installer to the desired location.
 
net-snmp-5.9.4\win32\dist directory is not available in the downloaded net-snmp-5.9.4.zip.
Also build-binary.bat is not available.

How to proceed without these files?
