### ISSUE TITLE
Building net-snmp for windows

### ISSUE THREAD

**Issue by gagagou** [net-snmp/net-snmp#820]
Hello there ! 

I'm going tought an issue and i'm not able to find a solution. 
I've downloaded the source from sourceforge and installed visual studio on my windows computer.
I'm launching vcvarsall.bat and running the build.bat under win32.
Everything is fine until i'm exporting the usr folder to an another windows. 
I got the vcruntime140D.dll and ucrtbased.dll missing. I've installed the C++ Redistributable in x86 and 64, rebooted the windows but still missing. 
I've no issue on the building computer. 
Is there a way to build it with those element embeded in it ? 

thanks !

**Comment by Flow86** [comment]
> vcruntime140D.dll

this is the Debug variant of the C++ Redistributable - that one is only there if visual studio is installed on the machine.

You should build net-snmp in release mode to distribute it to different computers (there you need to install the appropriate C++ Redistributable though)
