### ISSUE TITLE
Max TLS Version ist set to TLS 1.0, hardcoded 

### ISSUE THREAD

**Issue by flash7777** [net-snmp/net-snmp#857]
hotfix:

sed -i 's|TLS1_VERSION|TLS1_3_VERSION|g' snmplib/transports/snmpTLSTCPDomain.c

comment:

it would be much better to have it in any config somewhere.
 minVersion:  ..
 maxVersion: ..

**Comment by bvanassche** [comment]
Which Net-SNMP version are you using? Please take a look at commit b0a4ae309dad0ed05f6915838b9d5d1fecb94b91.

**Comment by flash7777** [comment]
5.9.4-5

**Comment by flash7777** [comment]
i see. on HEAD its gone...

	#ifdef SSL_CTX_set_max_proto_version
		if (tlsdata->ssl_context)
		    SSL_CTX_set_max_proto_version(tlsdata->ssl_context, TLS1_3_VERSION);
	#endif
