### ISSUE TITLE
snmpv3 add and delete user causes fail of operation some times.

### ISSUE THREAD

**Issue by satishkumar444** [net-snmp/net-snmp#9]
My Version : net-snmp-5.4.4
---------------------------------
Description 
-------------
SNMP user add/delete is completing within few seconds most of the time. In some cases this operation is taking a long time in NET SNMP stack. 

In order to reproduce  we followed these steps: 
-----------------------------------------------
We have a curl scipts which will add the snmpv3 users add and remove continuously to stress our product.. however we noticed after some time the user addition or removal is not happening the soap response of it as failed.

While debugging we found one of the possible error 🥇 👍
-----------------------------------------------------------------
read_config_store open failure on /var/net-snmp/snmpd.conf
&
/etc/snmp/snmpd.conf: Too many open files

These error looks like some file descriptor leak.
When i searched the above error logs in google, I found with below possible fix (Patch) but 
nothing has resolved my problem.

https://bugzilla.redhat.com/show_bug.cgi?id=561875
https://stackoverflow.com/questions/880557/socket-accept-too-many-open-files

Kindly, suggest me something or any patch is available for snmpv3 user or removal.

**Comment by bvanassche** [comment]
Net-SNMP v5.4 is no longer supported. Please upgrade to version v5.8.
