### ISSUE TITLE
snmpd 5.8 crashed in Check_HR_FileSys_AutoFs() on Fedora 30

### ISSUE THREAD

**Issue by jnav** [net-snmp/net-snmp#98]
snmpd crashes every time when i run snmpwalk on it using following command:

`snmpwalk -v 2c -c public localhost 1.3.6.1.2.1.25.2.3`

the daemon is being started using systemd:
`/usr/sbin/snmpd -LSd-6d -f`

Important note - snmpwalk works with different OIDs but on this one it just crashes and core dump is created (attached)

Is Check_HR_FileSys_AutoFS related to Linux? I red somewhere that it should be related only to AIX system.

i am attaching core dump, messages file and configuration below

[snmpd-crash-details.zip](https://github.com/net-snmp/net-snmp/files/4482797/snmpd-crash-details.zip)

### package installed
net-snmp-5.8-16.fc30.x86_64
net-snmp-agent-libs-5.8-16.fc30.x86_64
net-snmp-utils-5.8-16.fc30.x86_64
erlang-snmp-21.3.8.4-1.fc30.x86_64
net-snmp-libs-5.8-16.fc30.x86_64

### config in /etc/snmp/snmpd.conf contains
com2sec readonly 192.168.1.0/24 mysecretcs
group   readonlyGroup   v2c     readonly
view    systemview    included   .1
access  notConfigGroup ""      any       noauth    exact  systemview none none
access  readonlyGroup  ""      any       noauth    prefix  systemview none none
syslocation Unknown (edit /etc/snmp/snmpd.conf)
syscontact Root <root@localhost> (configure /etc/snmp/snmp.local.conf)
dontLogTCPWrappersConnects yes
rocommunity public 127.0.0.1

### /var/log/messages contains following:
Apr 15 19:14:56 MYHOST audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=snmpd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Apr 15 19:14:57 MYHOST audit[5185]: ANOM_ABEND auid=4294967295 uid=0 gid=0 ses=4294967295 pid=5185 comm="snmpd" exe="/usr/sbin/snmpd" sig=11 res=1
Apr 15 19:14:57 MYHOST kernel: snmpd[5185]: segfault at 814 ip 00007f0aef314dee sp 00007fffa78c4868 error 4 in libnetsnmpmibs.so.35.0.0[7f0aef2fe000+f9000]
Apr 15 19:14:58 MYHOST audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=snmpd comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Apr 15 19:14:58 MYHOST systemd[1]: snmpd.service: Main process exited, code=dumped, status=11/SEGV
Apr 15 19:14:58 MYHOST systemd[1]: snmpd.service: Failed with result 'core-dump'.
Apr 15 19:14:58 MYHOST systemd-coredump[5190]: Process 5185 (snmpd) of user 0 dumped core.#012#012Stack trace of thread 5185:#012#0  0x00007f0aef314dee Check_HR_FileSys_AutoFs (libnetsnmpmibs.so.35)#012#1  0x00007f0aef313f62 var_hrstore (libnetsnmpmibs.so.35)#012#2  0x00007f0aef5b0ad9 netsnmp_old_api_helper (libnetsnmpagent.so.35)#012#3  0x00007f0aef5c0417 netsnmp_call_handlers (libnetsnmpagent.so.35)#012#4  0x00007f0aef5d1455 handle_var_requests (libnetsnmpagent.so.35)#012#5  0x00007f0aef5d1b4f handle_getnext_loop (libnetsnmpagent.so.35)#012#6  0x00007f0aef5d2752 netsnmp_handle_request (libnetsnmpagent.so.35)#012#7  0x00007f0aef5d2d5b handle_snmp_packet (libnetsnmpagent.so.35)#012#8  0x00007f0aef16c0cf _sess_process_packet (libnetsnmp.so.35)#012#9  0x00007f0aef16d176 _sess_read (libnetsnmp.so.35)#012#10 0x00007f0aef16dcad snmp_sess_read2 (libnetsnmp.so.35)#012#11 0x00007f0aef16dcfb snmp_read2 (libnetsnmp.so.35)#012#12 0x0000563541374d82 receive (snmpd)#012#13 0x00005635413741d5 main (snmpd)#012#14 0x00007f0aeef57f33 __libc_start_main (libc.so.6)#012#15 0x00005635413744ae _start (snmpd)
Apr 15 19:14:58 MYHOST abrt-notification[5230]: Process 16496 (snmpd) crashed in Check_HR_FileSys_AutoFs()

**Comment by jridky** [comment]
This issue was fixed in net-snmp-5.8-19, that is currently in updates-testing repository for F30.

To get this update, please, run `# dnf upgrade net-snmp --enablerepo=updates-testing`.

**Comment by jnav** [comment]
Thank you Jiri, this solved my issue and snmpd is stable again
