### ISSUE TITLE
Why write ifXTable cache to /var/lib/snmp/snmpd.conf if we cannot parse it upon restart?

### ISSUE THREAD

**Issue by stannous** [net-snmp/net-snmp#99]
While I know this is just a warning message, it's annoying and seems, IMHO, to be a bug.
If we cannot parse ifXTable entries from the persistent cache /var/lib/snmp/snmpd.conf,
why do we even bother saving it there?   Am I missing something?

Can we either stop writing ifXTable entries there or add some code to parse and use it?

Thanks,
Sam Tannous

```
##############################################################
#
# ifXTable persistent data
#
ifXTable .1 14:0 18:0x $
ifXTable .2 14:0 18:0x $
ifXTable .3 14:0 18:0x $

```

```
2020-04-21T21:01:45.913131+00:00 cel-redxp-01 snmpd[25630]: /var/lib/snmp/snmpd.conf: line 100: Warning: Unknown token: ifXTable.
2020-04-21T21:01:45.913692+00:00 cel-redxp-01 snmpd[25630]: /var/lib/snmp/snmpd.conf: line 101: Warning: Unknown token: ifXTable.
2020-04-21T21:01:45.914233+00:00 cel-redxp-01 snmpd[25630]: /var/lib/snmp/snmpd.conf: line 102: Warning: Unknown token: ifXTable.
```

**Comment by EZenderink** [comment]
I second this, we noticed a similar issue on our side. After the persistent config file has been generated by snmp, and we restart the snmp application, the agent prints the following:

     /tmp/etc/snmp/persistent/SNMP.conf: line 65: Warning: Unknown token: ifXTable.
     /tmp/etc/snmp/persistent/SNMP.conf: line 66: Warning: Unknown token: ifXTable.
     /tmp/etc/snmp/persistent/SNMP.conf: line 67: Warning: Unknown token: ifXTable.

In our case this table has no use for us, thus we tried disabling the mib that ifXTable is part of using  `shutdown_ifTable();` and `shutdown_ifXTable();` after the `init_mib_modules();`, but this did not resolve the issue.

However disabling the MIB during configuration of net-snmp using the `-with-out-mib-module="if-mib"` argument works. However this is a workaround, not a fix!

**Comment by fenner** [comment]
There *is* code to register ifXTable, in the same function that registers the dump function.  Most parts of snmpd use `snmpd_register_config_handler()` but it looks like the mfd-generated code uses `register_config_handler()`, and I wonder if this is why it's not being handled properly.  (Like, is it actually expecting it in the [snmp] context, not [snmpd]?)

**Comment by ColdForest** [comment]
It would be nice to have this resolved in the upcoming v5.8.1 final release. We definitely use the persistent storage feature for ifXTable entries, both the ifLinkUpDownTrapEnable and ifAlias column objects, so I'm hoping any resolution here doesn't include elimination of this feature.

**Comment by rstory** [comment]
I've committed a fix that works for me (https://github.com/net-snmp/net-snmp/commit/e772b8017d7e235437a45622bf8aa05f3ef3d084) in V5-8-patches.. Can anyone test and confirm it works for them too?

**Comment by ColdForest** [comment]
My quick build of this branch and quick run of the agent appears to confirm this is fixed. I'm not sure of any other implied effects of the commit (changing ...POST_READ_CONFIG to ..PRE_READ_CONFIG) so I can't report anything more regarding the validity of the change.

BTW, my first attempt at testing this was to simply apply the commit to my v5.8.1-pre2 snapshot and this didn't eliminate the messages - likely because there are other changes in the V5-8-patches branch that are necessary to support the change (?).

Thx.

**Comment by rstory** [comment]
@ColdForest That's odd. This is an extremely simple patch that just uses an earlier callback to make sure the config token is registered before the config file is parses. Everything needed for this has been in the code for many years.  If you still have that snapshot, maybe try 'make clean all' to make sure the file is rebuilt?

**Comment by ColdForest** [comment]
@rstory Yes, a full rebuild with just this change from v5.8.1pre2 also eliminates the warning messages. Thx for confirming that this should have always been the case.

**Comment by rstory** [comment]
great. I think someone also merged this into master, so I'm closing this issue..
